import * as XLSX from 'xlsx';
import contract from './contracts/blueJacketContractV1.json' with { type: 'json' };
import { typed, text } from './normalization';
import type { CanonicalAudit, ParsedSource, RawTyped } from './types';

type Field = { source:string; sheet:string; coordinate:string; header:string; output_field:string; type: Parameters<typeof typed>[1]; required:string };
const allFields=contract.parser_contracts as Field[];
export const SOURCE_IDS=(contract.source_motor_map as Array<{source:string}>).map(x=>x.source) as string[];
export const SOURCE_FILE_NAMES=Object.fromEntries(SOURCE_IDS.map(source=>[source,source]));
const sourceContract=(source:string) => allFields.filter(x=>x.source===source || (source.startsWith('379') && x.source==='379 25.txt / 379 26.txt'));
const audit=(source:string,file:string,code:string,message:string,action:string,row?:number):CanonicalAudit=>({code,severity:'BLOCKED',source,file,message,action,row});
const col=(coordinate:string)=>{const m=coordinate.match(/^([A-Z]+)(?:\b|\/|:)/);return m?[...m[1]].reduce((n,c)=>n*26+c.charCodeAt(0)-64,0)-1:-1};
const cell=(row:unknown[], coordinate:string)=>row[col(coordinate)];
const key=(value:unknown)=>text(value).toUpperCase().replace(/\s+/g,' ');
const result=(source:string,file:File,sheet:string,rows:Array<Record<string,RawTyped>>,audits:CanonicalAudit[]):ParsedSource=>({source,fileName:file.name,sheet,rows,audits});
const TOP_RETAIL_ROUTE_SOURCE="08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx";
const MONTHLY_TOP_TARGET_HEADER=/^META (?:JAN|FEV|MAR|ABR|MAI|JUN|JUL|AGO|SET|OUT|NOV|DEZ)(?:['./ -]?(?:\d{2}|\d{4}))?$/;
const headerMatches=(source:string,field:Field,actual:unknown)=>source===TOP_RETAIL_ROUTE_SOURCE&&field.output_field==='top_target'?MONTHLY_TOP_TARGET_HEADER.test(key(actual)):key(actual)===key(field.header);

/** Strict tabular reader. It is invoked only by the parser named for a source. */
async function tabular(source:string,file:File, options:{sheet?:string; filter?:(row:unknown[])=>boolean}={}) {
 const sourceFields=sourceContract(source), wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,raw:true});
 const expected=options.sheet ?? sourceFields[0]?.sheet ?? '';
 const fs=sourceFields.filter(field=>field.sheet===expected);
 const knownSheetAliases:Record<string,string>={'Nova Base de Premissas - Q3.xlsx':'Exportação PDVs (9)'};
 const actual=wb.SheetNames.find(n=>n===(knownSheetAliases[source]??expected));
 if(!actual)return result(source,file,expected,[],[audit(source,file.name,'PARSER_SCHEMA_CHANGED',`Aba esperada: ${expected}; recebidas: ${wb.SheetNames.join(', ')||'(nenhuma)'}.`,'Validar e aprovar a nova versão antes de processar.')]);
 const matrix=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[actual],{header:1,defval:'',raw:true});
 const columns=fs.filter(f=>col(f.coordinate)>=0), required=columns.filter(f=>f.required==='SIM'&&!f.header.startsWith('('));
 const h=matrix.findIndex(row=>required.filter(f=>headerMatches(source,f,row[col(f.coordinate)])).length>=Math.max(1,Math.ceil(required.length*.7)));
 if(h<0)return result(source,file,actual,[],[audit(source,file.name,'PARSER_REQUIRED_COLUMN_MISSING',`Cabeçalho contratado não encontrado: ${required.map(f=>f.header).join(' | ')}.`,'Corrigir a fonte ou validar formalmente a nova estrutura.')]);
 const issues:CanonicalAudit[]=[];for(const f of required)if(!headerMatches(source,f,matrix[h][col(f.coordinate)]))issues.push(audit(source,file.name,'PARSER_SCHEMA_CHANGED',`Posição ${f.coordinate}: esperado “${f.header}”; recebido “${text(matrix[h][col(f.coordinate)])||'(vazio)'}”.`,'Validar nova versão do relatório antes de recalcular.',h+1));
 if(issues.length)return result(source,file,actual,[],issues);
 const rows=matrix.slice(h+1).filter(row=>row.some(v=>text(v))).filter(row=>!options.filter||options.filter(row)).map((row,i)=>{const out:Record<string,RawTyped>={};for(const f of columns)out[f.output_field]=typed(cell(row,f.coordinate),f.type);out.__source_row={raw:h+2+i,typed:h+2+i};out.__schema_version={raw:'v1',typed:'v1'};return out});
 return result(source,file,actual,rows,[]);
}
/** Approved report variants with merged headings (286/105) retain exact labels,
 * but their visual merged cells shift the contractual Excel letters. */
async function mergedReport(source:string,file:File){
 const fs=sourceContract(source),wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,raw:true}),sheet=wb.Sheets[wb.SheetNames[0]];
 if(!sheet)return result(source,file,'Report',[],[audit(source,file.name,'PARSER_SCHEMA_CHANGED','Aba Report ausente.','Gerar o relatório oficial 286/105 novamente.')]);
 const matrix=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,defval:'',raw:true});const headers=fs.filter(f=>col(f.coordinate)>=0).map(f=>f.header);
 const h=matrix.findIndex(r=>headers.filter(x=>r.map(key).includes(key(x))).length>=Math.ceil(headers.length*.65));
 if(h<0)return result(source,file,'Report',[],[audit(source,file.name,'PARSER_REQUIRED_COLUMN_MISSING','Cabeçalhos do relatório oficial não encontrados.','Validar layout 286/105 antes de processar.')]);
 const indexes=new Map<string,number>();for(const header of headers){const i=matrix[h].map(key).indexOf(key(header));if(i>=0&&!indexes.has(header))indexes.set(header,i)}
 const rows=matrix.slice(h+1).filter(r=>r.some(v=>text(v))).map((r,i)=>{const out:Record<string,RawTyped>={};for(const f of fs.filter(x=>col(x.coordinate)>=0)){const index=indexes.get(f.header);out[f.output_field]=typed(index===undefined?'':r[index],f.type)}out.__source_row={raw:h+2+i,typed:h+2+i};out.__schema_version={raw:'v1',typed:'v1'};return out});return result(source,file,'Report',rows,[]);
}
function record(source:string,file:File,row:number,names:string[], values:string[]){const fs=sourceContract(source),out:Record<string,RawTyped>={};names.forEach((name,i)=>{const f=fs.find(x=>x.output_field===name);if(f)out[name]=typed(values[i]??'',f.type)});out.__source_row={raw:row,typed:row};out.__schema_version={raw:'v1',typed:'v1'};return out}
async function parse379(source:string,file:File){const rows:Record<string,RawTyped>[]=[],issues:CanonicalAudit[]=[];for(const [index,line] of (await file.text()).split(/\r?\n/).entries()){if(!/^\d{2}\/\d{2}\/\d{4}\s+\d/.test(line))continue;const m=line.match(/^(\d{2}\/\d{2}\/\d{4})\s+(\S+)\s+(\S+)\s+(\S+)\s+([\d.,-]+)\s+([\d.,-]+)\s+([\d.,-]+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+([\d.,-]+)\s+([\d.,-]+)/);if(!m){issues.push(audit(source,file.name,'PARSER_SCHEMA_CHANGED','Linha de movimento 379 não correspondeu ao bloco posicional aprovado.','Validar nova versão antes de recalcular.',index+1));continue}const r=record(source,file,index+1,['movement_date','invoice_number','invoice_series','legacy_product_code','quantity_raw','value_raw','discount_raw','operation_code','cfop','order_number','supplier_document','customer_document','legacy_rca_code','net_weight','gross_weight'],m.slice(1));const pair=`${r.operation_code?.typed}/${r.cfop?.typed}`;r.movement_class={raw:pair,typed:['51201/5403','51216/5403','51234/5403','51201/5102','51216/5102','51234/5102'].includes(pair)?'SALE':['13201/1411','13216/1411','13234/1411','13201/1202','13216/1202','13234/1202'].includes(pair)?'RETURN':'OTHER'};rows.push(r)}return result(source,file,'TXT linha 420 chars',rows,issues)}
async function parse310(source:string,file:File){const rows:Record<string,RawTyped>[]=[],issues:CanonicalAudit[]=[];let customer='';for(const [index,line] of (await file.text()).split(/\r?\n/).entries()){const c=line.match(/(?:Cliente|CGC\/CPF)\s*[: ]+(.+)/i);if(c)customer=c[1].trim();const m=line.match(/^\s*(\d{6,})\s+(.+?)\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(.+?)\s*$/);if(!m)continue;const r=record(source,file,index+1,['legacy_product_code','description','volumes','purchase_count','purchase_net_weight','purchase_value','bonus_value','discount_value','return_volume','return_net_weight','return_value','customer_document','seller_code_legacy','group_code','group_description'],m.slice(1));r.customer_name={raw:customer,typed:customer};rows.push(r)}if(!rows.length)issues.push(audit(source,file.name,'PARSER_SCHEMA_CHANGED','Nenhuma linha produto do 310 correspondeu ao layout com Documento + Ven. + Agp. homologado.','Validar o relatório 310 antes de substituir o staging.'));return result(source,file,'TXT',rows,issues)}
async function parse12322File(source:string,file:File){const rows:Record<string,RawTyped>[]=[];const pattern=/^\s*(\d+)\s+(\d{2}\/\d{2}\/\d{2})\s+(\d{2}\/\d{2}\/\d{2})\s+(\d+)\s+(.+?)\s{2,}(\d{3}\.\d{2})\s+(\d{4})\s+([\d.]+,\d{2})\s+([\d.]+,\d{2})\s+([\d.]+,\d{2})\s+(\d{3})\s+([A-Z]{2})\s*(.*?)\s+(\d+)\s*$/;for(const [index,line] of (await file.text()).replace(/\f/g,'\n').split(/\r?\n/).entries()){const m=line.match(pattern);if(!m)continue;const r=record(source,file,index+1,['invoice_raw','invoice_issue_date','accounting_date','supplier_document','supplier_name','operation_code','representative_raw','invoice_value','discount','exchange_discount','series','state','observations','order_number'],m.slice(1));r.receipt_class={raw:r.operation_code.raw,typed:r.operation_code.typed==='212.01'?'MERCHANDISE':r.operation_code.typed==='299.40'?'SUPPLIES':'OTHER'};rows.push(r)}return result(source,file,'TXT NF',rows,[])}
async function parse218File(file:File){const source='entrada-notas-218.xls',fs=sourceContract(source),invoiceFields=fs.filter(f=>f.sheet==='Report - bloco NF'),wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,raw:true}),matrix=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets.Report,{header:1,defval:'',raw:true});let invoice:unknown[]=[];const rows:Record<string,RawTyped>[]=[];for(let i=0;i<matrix.length;i++){const row=matrix[i];if(key(row[0])==='DT. ENTRADA'){invoice=matrix[i+1]??[];if(text(invoice[col('E')])){const header:Record<string,RawTyped>={};for(const f of invoiceFields)header[f.output_field]=typed(invoice[col(f.coordinate)],f.type);header.__receipt_scope={raw:'INVOICE',typed:'INVOICE'};header.__source_row={raw:i+2,typed:i+2};header.__schema_version={raw:'v2',typed:'v2'};rows.push(header)}}if(key(row[4])==='CÓDIGO'&&key(row[5])==='PRODUTO'){for(let j=i+1;j<matrix.length&&text(matrix[j][4]);j++){const item=matrix[j],out:Record<string,RawTyped>={};for(const f of fs){const v=f.output_field.startsWith('receipt_')||['received_units','current_financial_cost','previous_financial_cost','fiscal_code','operation_code'].includes(f.output_field)?item[col(f.coordinate)]:invoice[col(f.coordinate)];out[f.output_field]=typed(v,f.type)}out.__receipt_scope={raw:'ITEM',typed:'ITEM'};out.__source_row={raw:j+1,typed:j+1};out.__schema_version={raw:'v2',typed:'v2'};rows.push(out)} }}return result(source,file,'Report',rows,[])}
async function parseSortimentoFile(file:File){const source="Sortimento Recomendado - Q3'26.xlsx", wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true,raw:true});const variants=[
 {sheet:'Jul26 - Base_Sortimento_Naciona',dataset:'JUL_BASE',headers:['STATUS','COD CMD','COD','EAN','CATEGORIA MASTER','CATEGORIA','SUBCATEGORIA','MARCA','SUBMARCA','SEGMENTO','SUBSEGMENTO','CONTENTS','AMOUNT','PROMO','LANÇAMENTO','DESCRIÇÃO']},
 {sheet:'Ago & Set26 - Base_Sortimento_N',dataset:'AUG_SEP_BASE',headers:['STATUS','COD','','EAN','CATEGORIA MASTER','CATEGORIA','SUBCATEGORIA','MARCA','SUBMARCA','SEGMENTO','SUBSEGMENTO','CONTENTS','AMOUNT','PROMO','LANÇAMENTO','DESCRIÇÃO']},
 {sheet:'SORTIMENTO HAIR CARE AGO26 &SET',dataset:'HAIR_OVERRIDE',headers:['STATUS','COD ANTIGO','EAN ANTIGO','COD NOVO','EAN NOVO','CATEGORIA MASTER','CATEGORIA','SUBCATEGORIA','MARCA','SUBMARCA','SEGMENTO','SUBSEGMENTO','CONTENTS','AMOUNT','PROMO','LANÇAMENTO','DESCRIÇÃO']},
 {sheet:'Descontinuados Q326',dataset:'DISCONTINUED_Q3',headers:['STATUS','COD','EAN','CATEGORIA MASTER','CATEGORIA','SUBCATEGORIA','MARCA','SUBMARCA','SEGMENTO','SUBSEGMENTO','CONTENTS','AMOUNT','PROMO','LANÇAMENTO','DESCRIÇÃO']}
 ];const rows:Record<string,RawTyped>[]=[],issues:CanonicalAudit[]=[];for(const variant of variants){const sheet=wb.Sheets[variant.sheet];if(!sheet){issues.push(audit(source,file.name,'PARSER_SCHEMA_CHANGED',`Aba obrigatória ausente: ${variant.sheet}.`,'Gerar o workbook oficial de Sortimento.',undefined));continue}const matrix=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,defval:'',raw:true});const h=matrix.findIndex(r=>variant.headers.every((header,i)=>key(r[i])===key(header)));if(h<0){issues.push(audit(source,file.name,'PARSER_SCHEMA_CHANGED',`Fingerprint de ${variant.dataset} não encontrado na aba ${variant.sheet}.`,'Validar nova versão do Sortimento antes de recalcular.'));continue}const fields=sourceContract(source).filter(f=>f.sheet===variant.sheet);for(let i=h+1;i<matrix.length;i++){const row=matrix[i];if(!text(row[0]))continue;const out:Record<string,RawTyped>={};for(const f of fields){const index=col(f.coordinate);if(index>=0)out[f.output_field]=typed(row[index],f.type)}out.sortimentDataset={raw:variant.dataset,typed:variant.dataset};out.__source_sheet={raw:variant.sheet,typed:variant.sheet};out.__source_row={raw:i+1,typed:i+1};out.__schema_version={raw:'v1',typed:'v1'};rows.push(out)}}return result(source,file,'4 subcontratos',rows,issues)}
async function parseBussolaFile(file:File){const source='Bussola de Metas AGOSTO - 2026 DEFINITIVA.xlsx',started=performance.now(),wb=XLSX.read(await file.arrayBuffer(),{type:'array',raw:true,sheets:'Metas',cellFormula:false}),sheet=wb.Sheets.Metas;if(!sheet)return result(source,file,'Metas',[],[audit(source,file.name,'PARSER_SCHEMA_CHANGED','Aba Metas ausente.','Gerar a Bússola oficial.')]);const range=XLSX.utils.decode_range(sheet['!ref']||'A1:DY1');range.e.r=Math.min(range.e.r,2000);const matrix=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,range,defval:'',raw:true});const signature=['Supervisor','St','Pas.','Nome','CNPJ','Indústria','Meta PNA','Meta. Pos. Ind.'];const h=matrix.findIndex(r=>signature.every(x=>r.map(key).includes(key(x))));if(h<0)return result(source,file,'Metas',[],[audit(source,file.name,'PARSER_SCHEMA_CHANGED','Fingerprint da Bússola não encontrado.','Validar layout Metas.',undefined)]);const fs=sourceContract(source),rows:Record<string,RawTyped>[]=[];for(let i=h+1;i<matrix.length;i++){const r=matrix[i];if(![0,1,4,7,16,21].some(n=>text(r[n])))continue;const out:Record<string,RawTyped>={};for(const f of fs.filter(f=>col(f.coordinate)>=0&&col(f.coordinate)<=28))out[f.output_field]=typed(r[col(f.coordinate)],f.type);out.__source_row={raw:i+1,typed:i+1};out.__schema_version={raw:'v1',typed:'v1'};out.__processing_ms={raw:performance.now()-started,typed:performance.now()-started};rows.push(out)}return result(source,file,'Metas',rows,[])}

export const parse37925=(f:File)=>parse379('379 25.txt',f); export const parse37926=(f:File)=>parse379('379 26.txt',f); export const parse310Total2026=(f:File)=>parse310('310 total 2026.txt',f); export const parse12322=(f:File)=>parse12322File('12.322.txt',f);
export const parse8022=(f:File)=>tabular('vendas-8022.xls',f);export const parse105=(f:File)=>mergedReport('posicao-estoque-105.xls',f);export const parse286=(f:File)=>mergedReport('cadastro-itens-286.xls',f);export const parse8013=(f:File)=>tabular('estoque-8013.xls',f);export const parse218=parse218File;export const parseCarteira=(f:File)=>tabular('CARTEIRA 24.08.xlsx',f);export const parsePctabpr=(f:File)=>tabular('pctabpr 13.xlsx',f,{filter:r=>String(cell(r,'B')).trim()==='11'&&key(cell(r,'F'))==='A'});export const parseListaPreco=(f:File)=>tabular('Lista_de_Preco (8).xlsx',f);export const parseLancamentos=(f:File)=>tabular('lançamentos.xlsx',f);export const parseNovosRcas=(f:File)=>mergedReport('NOVOS RCAS.xlsx',f);export const parsePremissas=(f:File)=>tabular('Nova Base de Premissas - Q3.xlsx',f);export const parseCarteiraClientes=(f:File)=>tabular('relatorio_carteira_clientes.xls',f);export const parseRoteiroTop=(f:File)=>tabular("08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx",f);export const parseBussola=parseBussolaFile;export const parseSortimento=parseSortimentoFile;
const parsers:Record<string,(file:File)=>Promise<ParsedSource>>={'379 25.txt':parse37925,'379 26.txt':parse37926,'310 total 2026.txt':parse310Total2026,'12.322.txt':parse12322,'vendas-8022.xls':parse8022,'posicao-estoque-105.xls':parse105,'cadastro-itens-286.xls':parse286,'estoque-8013.xls':parse8013,'entrada-notas-218.xls':parse218,'CARTEIRA 24.08.xlsx':parseCarteira,'pctabpr 13.xlsx':parsePctabpr,'Lista_de_Preco (8).xlsx':parseListaPreco,'lançamentos.xlsx':parseLancamentos,'NOVOS RCAS.xlsx':parseNovosRcas,'Nova Base de Premissas - Q3.xlsx':parsePremissas,'relatorio_carteira_clientes.xls':parseCarteiraClientes,"08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx":parseRoteiroTop,'Bussola de Metas AGOSTO - 2026 DEFINITIVA.xlsx':parseBussola,"Sortimento Recomendado - Q3'26.xlsx":parseSortimento};
export function parseSource(source:string,file:File){const parser=parsers[source];return parser?parser(file):Promise.resolve(result(source,file,'',[],[audit(source,file.name,'PARSER_SCHEMA_CHANGED','Fonte sem parser específico aprovado.','Adicionar parser específico antes de processar.')]));}
export const parseWorkbookSource=parseSource;export const parseTextSource=parseSource;
