import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import {
  AdminRegistryRepository, InMemoryAdminRegistryStorage, applyRegistrySeed, diagnoseLaunchRecords, diagnoseRcaRecords,
  emptyAdminRegistryState, previewRegistrySeed, setRegistryRecordActive, upsertManualLaunch, upsertManualRca,
  validateAdminRegistryState, type AdminRegistryState, type RcaRegistryRecord,
} from '../src/canonical/adminRegistry.ts';
import { canonicalAdminRegistryHash, canonicalInputHash } from '../src/canonical/adminRegistryIdentity.ts';
import { cloudSyncTestHelpers, type CloudRestoreDependencies, type CloudSnapshot, type DeviceSyncIdentity } from '../src/canonical/cloudSync.ts';
import { CANONICAL_ENGINE_VERSION, REQUIRED_SOURCE_IDS, type SourceStorageSnapshot } from '../src/canonical/sourceImport.ts';
import { stagingManifestHashV2, canonicalInputHashV3 } from '../src/canonical/sourceReplacementIdentity.ts';
import { EMPTY_SOURCE_REPLACEMENT_PROOF } from '../src/canonical/sourceReplacementState.ts';
import { sourceStorageSnapshotManifestHash } from '../src/canonical/sourceSnapshotIdentity.ts';
import type { ActiveCanonicalBundle } from '../src/canonical/runtime.ts';
import { rcaTargetRegistryHash } from '../src/canonical/targetIdentity.ts';
import type { ParsedSource, RawTyped } from '../src/canonical/types.ts';
import { sourceStorageV1Fixture, V20_ENGINE, V21_ENGINE } from './phase5b-fixtures.ts';

const NOW='2026-09-06T15:00:00.000Z',LATER='2026-09-06T16:00:00.000Z';
const sourceText=(relative:string)=>readFileSync(new URL(relative,import.meta.url),'utf8');
const cell=(typed:unknown,raw:unknown=typed):RawTyped=>({raw,typed});
const parsed=(source:string,fileName:string,rows:ParsedSource['rows']):ParsedSource=>({source,fileName,sheet:'test',rows,audits:[]});
const row=(fields:Record<string,unknown>,sourceRow:number)=>Object.fromEntries([...Object.entries(fields).map(([key,value])=>[key,cell(value)]),['__source_row',cell(sourceRow)]]) as ParsedSource['rows'][number];
const rcaSource=(name='RCA Principal')=>parsed('NOVOS RCAS.xlsx','NOVOS RCAS.xlsx',[row({current_rca_code_principal:'00123',legacy_rca_code_principal:'00099',rca_name_raw_principal:name,coordinator_code_principal:'0007',coordinator_name_principal:'Coord P',current_rca_code_auxiliar:'00456',legacy_rca_code_auxiliar:'00321',rca_name_raw_auxiliar:'RCA Aux',coordinator_code_auxiliar:'0008',coordinator_name_auxiliar:'Coord A'},2)]);
const launchSource=(description='Produto A')=>parsed('lançamentos.xlsx','lançamentos.xlsx',[row({launch_winthor_code:'0010',launch_description:description,launch_type:'NOVA LINHA',launch_ean:'7891234567890',launch_status:'ATIVO'},2)]);
const topSource=(overrides:Record<string,unknown>={},fileName="08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx")=>parsed("08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx",fileName,[row({cnpj:'12345678000199',top_network:'Rede A',banner:'Bandeira A',manager_cnpj:'98765432000188',group_code:'001',top_category:'TOP',top_target:1000,...overrides},2)]);
const repository=(initial:unknown|null=null)=>{const storage=new InMemoryAdminRegistryStorage(initial);return{storage,repo:new AdminRegistryRepository(storage)}};

test('R1 — repository faz round-trip integral do snapshot v1',async()=>{const{repo}=repository();const state=emptyAdminRegistryState(NOW);assert.deepEqual(await repo.replace(state),state);assert.deepEqual(await repo.load(),state);});
test('R2 — schema inválido é rejeitado integralmente',()=>{assert.throws(()=>validateAdminRegistryState({...emptyAdminRegistryState(NOW),schemaVersion:'v2'}),/ADMIN_REGISTRY_STATE_INVALID/);assert.throws(()=>validateAdminRegistryState({...emptyAdminRegistryState(NOW),topRetailers:[{nope:true}]}),/ADMIN_REGISTRY_RECORD_INVALID/);});
test('R3 — falha de persistência mantém a versão anterior',async()=>{const{storage,repo}=repository(emptyAdminRegistryState(NOW));const before=await repo.load();storage.failNextWrite();await assert.rejects(()=>repo.mutate(state=>{state.updatedAt=LATER},LATER),/ADMIN_REGISTRY_TEST_WRITE_FAILED/);assert.deepEqual(await repo.load(),before);});
test('R4 — metadados timestamps/origin/active sobrevivem ao round-trip',async()=>{const{repo}=repository();await upsertManualRca(repo,{currentCode:'001',legacyCode:null,name:null,coordinatorCode:null,coordinatorName:null,role:'PRINCIPAL',validFromCompetence:null,validToCompetence:null,note:'manual'},undefined,NOW);const record=(await repo.load())!.rcas[0];assert.equal(record.origin,'MANUAL');assert.equal(record.active,true);assert.equal(record.createdAt,NOW);});
test('R5 — seed RCA preserva contrato real Principal',async()=>{const{repo}=repository();const result=await applyRegistrySeed(repo,'rcas',rcaSource(),NOW);const p=result.state.rcas.find(r=>r.role==='PRINCIPAL')!;assert.deepEqual([p.currentCode,p.legacyCode,p.name,p.coordinatorCode,p.coordinatorName,p.role],['00123','00099','RCA Principal','0007','Coord P','PRINCIPAL']);});
test('R6 — Principal e Auxiliar permanecem registros distintos',async()=>{const{repo}=repository();const result=await applyRegistrySeed(repo,'rcas',rcaSource(),NOW);assert.deepEqual(result.state.rcas.map(r=>r.role).sort(),['AUXILIAR','PRINCIPAL']);assert.notEqual(result.state.rcas[0].id,result.state.rcas[1].id);});
test('R7 — reseed RCA idêntico é idempotente',async()=>{const{repo}=repository();await applyRegistrySeed(repo,'rcas',rcaSource(),NOW);const before=await repo.load();const preview=previewRegistrySeed('rcas',rcaSource(),before,NOW);assert.deepEqual([preview.counts.new,preview.counts.updatable,preview.counts.equal],[0,0,2]);await applyRegistrySeed(repo,'rcas',rcaSource(),NOW);assert.deepEqual(await repo.load(),before);});
test('R8 — registro RCA MANUAL nunca é sobrescrito por SOURCE_SEED',async()=>{const{repo}=repository();await applyRegistrySeed(repo,'rcas',rcaSource(),NOW);const p=(await repo.load())!.rcas.find(r=>r.role==='PRINCIPAL')!;await upsertManualRca(repo,{currentCode:p.currentCode,legacyCode:p.legacyCode,name:'Nome manual',coordinatorCode:p.coordinatorCode,coordinatorName:p.coordinatorName,role:p.role,validFromCompetence:null,validToCompetence:null,note:null},p.id,LATER);assert.equal(previewRegistrySeed('rcas',rcaSource('Fonte nova'),await repo.load(),LATER).counts.manualProtected,1);await applyRegistrySeed(repo,'rcas',rcaSource('Fonte nova'),LATER);assert.equal((await repo.load())!.rcas.find(r=>r.id===p.id)?.name,'Nome manual');});
test('R9 — legacy RCA apontando para dois currentCode gera conflito',()=>{const source=parsed('NOVOS RCAS.xlsx','NOVOS RCAS.xlsx',[row({current_rca_code_principal:'100',legacy_rca_code_principal:'999',rca_name_raw_principal:'A'},2),row({current_rca_code_principal:'200',legacy_rca_code_principal:'999',rca_name_raw_principal:'B'},3)]);assert.ok(previewRegistrySeed('rcas',source,null,NOW).counts.conflicts>=2);});
test('R10 — inativar e reativar RCA não apaga histórico do registro',async()=>{const{repo}=repository();await applyRegistrySeed(repo,'rcas',rcaSource(),NOW);const original=(await repo.load())!.rcas[0];await setRegistryRecordActive(repo,'rcas',original.id,false,LATER);const inactive=(await repo.load())!.rcas.find(r=>r.id===original.id)!;assert.equal(inactive.active,false);assert.equal(inactive.createdAt,original.createdAt);assert.equal(inactive.origin,'MANUAL');await setRegistryRecordActive(repo,'rcas',original.id,true,LATER);assert.equal((await repo.load())!.rcas.find(r=>r.id===original.id)?.active,true);});
test('R11/R12 — seed Lançamentos preserva COD/DESCRIÇÃO/TIPO/EAN/STATUS e EAN textual',async()=>{const{repo}=repository();const launch=(await applyRegistrySeed(repo,'launches',launchSource(),NOW)).state.launches[0];assert.deepEqual([launch.winthorCode,launch.description,launch.type,launch.ean,launch.status],['0010','Produto A','NOVA LINHA','7891234567890','ATIVO']);assert.equal(typeof launch.ean,'string');});
test('R13 — lançamento manual exige EAN ou Winthor',async()=>{const{repo}=repository();await assert.rejects(()=>upsertManualLaunch(repo,{winthorCode:null,ean:null,description:null,type:null,status:null,validFromCompetence:null,validToCompetence:null,note:null},undefined,NOW),/ADMIN_REGISTRY_LAUNCH_IDENTITY_REQUIRED/);});
test('R14 — mesmo EAN com dois Winthor gera conflito',()=>{const source=parsed('lançamentos.xlsx','lançamentos.xlsx',[row({launch_winthor_code:'10',launch_ean:'7891234567890',launch_description:'A'},2),row({launch_winthor_code:'20',launch_ean:'7891234567890',launch_description:'B'},3)]);assert.ok(previewRegistrySeed('launches',source,null,NOW).counts.conflicts>=2);});
test('R15 — edição manual de lançamento sobrevive a reseed',async()=>{const{repo}=repository();await applyRegistrySeed(repo,'launches',launchSource(),NOW);const launch=(await repo.load())!.launches[0];await upsertManualLaunch(repo,{winthorCode:launch.winthorCode,ean:launch.ean,description:'Descrição manual',type:launch.type,status:launch.status,validFromCompetence:null,validToCompetence:null,note:null},launch.id,LATER);await applyRegistrySeed(repo,'launches',launchSource('Descrição fonte nova'),LATER);assert.equal((await repo.load())!.launches[0].description,'Descrição manual');});
test('R16 — seed Top usa competência explícita do nome do Roteiro',()=>{const preview=previewRegistrySeed('topRetailers',topSource(),null,NOW);assert.equal(preview.competence,'2026-08');assert.equal((preview.items.find(item=>item.record)?.record as {competence:string}).competence,'2026-08');});
test('R17/R18 — Top preserva CNPJ14, rede, bandeira, gestor, agrupamento, categoria e target',async()=>{const{repo}=repository();const top=(await applyRegistrySeed(repo,'topRetailers',topSource({cnpj:'1234567800019'}),NOW)).state.topRetailers[0];assert.equal(top.customerCnpj.length,14);assert.deepEqual([top.network,top.banner,top.managerCnpj,top.groupCode,top.category,top.topTarget],['Rede A','Bandeira A','98765432000188','001','TOP',1000]);});
test('R19 — Top competence+CNPJ exatamente igual deduplica no preview',()=>{const base=topSource().rows[0];const source=parsed("08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx","08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx",[base,{...base,__source_row:cell(3)}]);const preview=previewRegistrySeed('topRetailers',source,null,NOW);assert.equal(preview.counts.new,1);assert.equal(preview.counts.conflicts,0);});
test('R20 — Top competence+CNPJ divergente gera conflito',()=>{const source=parsed("08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx","08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx",[topSource().rows[0],row({cnpj:'12345678000199',top_network:'Rede B',banner:'B',manager_cnpj:'98765432000188',group_code:'002',top_category:'TOP',top_target:2000},3)]);assert.ok(previewRegistrySeed('topRetailers',source,null,NOW).counts.conflicts>=1);});
test('R21 — Roteiro sem competência explícita bloqueia seed',()=>assert.throws(()=>previewRegistrySeed('topRetailers',topSource({},'Roteiro Top.xlsx'),null,NOW),/ADMIN_REGISTRY_TOP_COMPETENCE_UNRESOLVED/));
test('R22–R24 — Registry entra por snapshot validado sem leitura de IndexedDB/CompetenceStore dentro das funções determinísticas',()=>{const motors=sourceText('../src/canonical/motors.ts'),rca=sourceText('../src/canonical/rcaResolver.ts'),top=sourceText('../src/canonical/topRetailM2.ts');for(const content of[motors,rca,top])assert.doesNotMatch(content,/adminRegistryIndexedDb|indexedDB|competenceStore|CompetenceStore/);assert.match(rca,/createRcaResolver\(parsedSources: ParsedSource\[\], registry: AdminRegistryState \| null = null\)/);assert.match(top,/materializeTopRetailRouteInM2\(m2: CanonicalList, sources: ParsedSource\[\], registry: AdminRegistryState \| null = null\)/);});
test('R25 — editar Registry preserva stagingManifestHash físico legado e altera somente registry/input identity v19',async()=>{const sourceSnapshot:SourceStorageSnapshot={format:'blue-jacket-source-storage/v1',exportedAt:NOW,staging:REQUIRED_SOURCE_IDS.map((source,index)=>({source,manifest:{source,fileName:`${source}.test`,fileHash:`physical-${index}`,parserVersion:`parser-${index}`,schemaVersion:'v1',parsedRows:0,warnings:0,errors:0,updatedAt:NOW,status:'VALID'},parsed:{source,fileName:`${source}.test`,sheet:'test',rows:[],audits:[]}}))} as SourceStorageSnapshot;const sourceHashA=await sourceStorageSnapshotManifestHash(sourceSnapshot),sourceHashB=await sourceStorageSnapshotManifestHash({...sourceSnapshot,exportedAt:LATER});assert.equal(sourceHashA,sourceHashB);const a:AdminRegistryState={...emptyAdminRegistryState(NOW),rcas:[{id:'r25',currentCode:'100',legacyCode:null,name:'A',coordinatorCode:null,coordinatorName:null,role:'PRINCIPAL',active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW}]};const b=structuredClone(a);b.rcas[0].name='B';const ah=await canonicalAdminRegistryHash(a),bh=await canonicalAdminRegistryHash(b);assert.notEqual(ah,bh);assert.notEqual(await canonicalInputHash(sourceHashA,ah),await canonicalInputHash(sourceHashB,bh));});
test('R26 — engine canônica corrente é v21 e v20/v19 permanecem reconhecíveis apenas como legado',()=>{assert.equal(CANONICAL_ENGINE_VERSION,V21_ENGINE);assert.notEqual(CANONICAL_ENGINE_VERSION,V20_ENGINE);const recovery=sourceText('../src/canonical/bundleRecovery.ts');assert.match(recovery,/browser-stage4-product-assortment-v20-targets-by-competence/);assert.match(recovery,/browser-stage4-product-assortment-v19-admin-registry-authority/);assert.match(recovery,/rebuildFromStaging/);});
test('R27 — Registry participa da orquestração canônica sem storage dentro das funções determinísticas',()=>{const motors=sourceText('../src/canonical/motors.ts'),sourceImport=sourceText('../src/canonical/sourceImport.ts'),authority=sourceText('../src/canonical/adminRegistryCanonicalAuthority.ts');assert.match(sourceImport,/loadAdminRegistryState/);assert.match(sourceImport,/canonicalAdminRegistryHash/);assert.match(sourceImport,/applyAdminRegistryCanonicalAuthority/);assert.doesNotMatch(motors,/indexedDB|adminRegistryIndexedDb|competenceStore|CompetenceStore/);assert.doesNotMatch(authority,/indexedDB|adminRegistryIndexedDb|competenceStore|CompetenceStore/);});

const identity:DeviceSyncIdentity={workspaceId:'7a7a7a7a-7a7a-4a7a-8a7a-7a7a7a7a7a7a',secret:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'};
const sources=sourceStorageV1Fixture();
const settings={networkTargetByCompetence:{},networkAllocationByCompetence:{},sellOutTargetByCompetence:{},positivityTargetByCompetence:{},legacySellOutTarget:null,legacyPositivityTarget:null,inboundForecastByInvoice:{}};
const active:ActiveCanonicalBundle={status:'ACTIVE',motorBuildId:'BUILD_PHASE3A',stagingManifestHash:'hash',adminRegistryHash:'admin',rcaTargetRegistryHash:'target',sourceContractVersion:'v2',sourceReplacementProofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,sourceReplacements:[],canonicalInputHash:'input',schemaVersion:'v1',engineVersion:V21_ENGINE,approvedAt:NOW,rowCounts:{M1_ITEM_ESTOQUE:0,M2_CLIENTE_RCA:0,M3_MOVIMENTO_VENDAS:0,M4_HISTORICO_TRANSICAO:0},factTypeCounts:{SALE:0,INBOUND_ORDER:0,RECEIPT:0,TARGET:0}};
const adminA:AdminRegistryState={...emptyAdminRegistryState(NOW),rcas:[{id:'a',currentCode:'100',legacyCode:null,name:'A',coordinatorCode:null,coordinatorName:null,role:'PRINCIPAL',active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW}]};
const adminB:AdminRegistryState={...emptyAdminRegistryState(LATER),launches:[{id:'b',winthorCode:'10',ean:'7891234567890',description:'B',type:null,status:'ATIVO',active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:LATER,updatedAt:LATER}]};
test('R28 — snapshot novo transporta registry',()=>{const snapshot=cloudSyncTestHelpers.buildCloudSnapshot(active,sources,settings,null,NOW,adminB);assert.deepEqual(snapshot.adminRegistryState,adminB);assert.equal(snapshot.format,'blue-jacket-device-sync/v1');});
test('R29 — encrypt/decrypt mantém registry com SourceStorage v1 real 19/19',async()=>{const snapshot=cloudSyncTestHelpers.buildCloudSnapshot(active,sources,settings,null,NOW,adminB);const decrypted=await cloudSyncTestHelpers.decrypt(identity,await cloudSyncTestHelpers.encrypt(identity,snapshot));assert.deepEqual(decrypted.adminRegistryState,adminB);assert.equal(decrypted.sources.staging.length,19);});
test('R30 — snapshot legado sem registry e sem ReplacementState continua válido',async()=>{const legacy:CloudSnapshot={format:'blue-jacket-device-sync/v1',createdAt:NOW,active,sources,settings};const decrypted=await cloudSyncTestHelpers.decrypt(identity,await cloudSyncTestHelpers.encrypt(identity,legacy));assert.equal('adminRegistryState'in decrypted,false);assert.equal('sourceReplacementState'in decrypted,false);});
function cloudHarness(initial:AdminRegistryState|null,failFirstBuild=false){let currentAdmin=initial?structuredClone(initial):null,currentSources=structuredClone(sources),currentSettings=structuredClone(settings),replacement:unknown=null,builds=0;const deps:CloudRestoreDependencies={exportSources:async()=>structuredClone(currentSources),loadSettings:()=>structuredClone(currentSettings),loadCompetence:()=>null,loadAdminRegistry:async()=>currentAdmin?structuredClone(currentAdmin):null,loadTargetState:()=>null,loadSourceReplacementState:()=>replacement as null,restoreSources:async next=>{currentSources=structuredClone(next)},restoreSettings:next=>{currentSettings=structuredClone(next as typeof settings);return currentSettings},replaceCompetence:()=>null,replaceAdminRegistry:async next=>{currentAdmin=next?structuredClone(next):null;return currentAdmin},replaceSourceReplacementState:next=>{replacement=next;return next},build:async()=>{builds+=1;if(failFirstBuild&&builds===1)throw new Error('PHASE3A_REBUILD_FAILED');const sourceHash=await stagingManifestHashV2(currentSources.staging,[]),adminHash=await canonicalAdminRegistryHash(currentAdmin),targetHash=await rcaTargetRegistryHash(null),inputHash=await canonicalInputHashV3(sourceHash,adminHash,targetHash,EMPTY_SOURCE_REPLACEMENT_PROOF);return{...active,motorBuildId:`BUILD_${builds}`,stagingManifestHash:sourceHash,adminRegistryHash:adminHash,rcaTargetRegistryHash:targetHash,canonicalInputHash:inputHash}}};return{deps,read:()=>({currentAdmin,builds,replacement})};}
test('R31 — snapshot legado preserva registry local existente e usa proof físico EMPTY',async()=>{const h=cloudHarness(adminA);const rebuilt=await cloudSyncTestHelpers.applyCloudSnapshot({format:'blue-jacket-device-sync/v1',createdAt:NOW,active:null,sources,settings},h.deps);assert.deepEqual(h.read().currentAdmin,adminA);assert.equal(rebuilt.sourceReplacementProofHash,EMPTY_SOURCE_REPLACEMENT_PROOF);});
test('R32 — snapshot novo restaura registry remoto',async()=>{const h=cloudHarness(adminA);await cloudSyncTestHelpers.applyCloudSnapshot({format:'blue-jacket-device-sync/v1',createdAt:NOW,active:null,sources,settings,adminRegistryState:adminB},h.deps);assert.deepEqual(h.read().currentAdmin,adminB);});
test('R33 — falha posterior executa rollback do registry local',async()=>{const h=cloudHarness(adminA,true);await assert.rejects(()=>cloudSyncTestHelpers.applyCloudSnapshot({format:'blue-jacket-device-sync/v1',createdAt:NOW,active:null,sources,settings,adminRegistryState:adminB},h.deps),/PHASE3A_REBUILD_FAILED/);assert.deepEqual(h.read().currentAdmin,adminA);assert.equal(h.read().builds,2);});
test('R34 — ENVIAR CÓPIA ATUAL reutiliza uploadCurrentDeviceSnapshot existente',()=>{const page=sourceText('../src/pages/admin/SincronizacaoPage.tsx');assert.match(page,/ENVIAR CÓPIA ATUAL/);assert.match(page,/sendCurrentDeviceSnapshot/);assert.match(page,/uploadCurrentDeviceSnapshot\(deviceSync\)/);});

test('Fase 3A — Cadastros continua funcional, seed controlado e os 19 formatos permanecem suportados',()=>{const admin=sourceText('../src/pages/admin/AdminPage.tsx'),page=sourceText('../src/pages/admin/CadastrosPage.tsx'),shared=sourceText('../src/pages/admin/registry/RegistryPanelShared.tsx'),seed=sourceText('../src/canonical/adminRegistrySeed.ts');assert.match(admin,/<CadastrosPage \/>/);assert.doesNotMatch(admin,/CadastrosPlaceholder/);const r=page.indexOf("label: 'RCAs'"),l=page.indexOf("label: 'Lançamentos'"),t=page.indexOf("label: 'Top Varejistas'");assert.ok(r>=0&&r<l&&l<t);assert.match(page,/metricLabel="Uso nos motores" metricValue="ATIVO"/);assert.match(seed,/loadSourceStaging/);assert.doesNotMatch(seed,/parseSource|parsers/);assert.match(shared,/Pré-visualizar importação/);assert.equal(REQUIRED_SOURCE_IDS.length,19);});
test('Fase 3A — Bundle continua técnico M1–M4; identidade administrativa usa hashes, nunca AdminRegistryState',()=>{const bundle=sourceText('../src/canonical/bundleStore.ts'),recovery=sourceText('../src/canonical/bundleRecovery.ts'),cloud=sourceText('../src/canonical/cloudSync.ts');assert.match(bundle,/adminRegistryHash/);assert.match(bundle,/canonicalInputHash/);assert.doesNotMatch(bundle,/AdminRegistryState|adminRegistryState/);assert.doesNotMatch(recovery,/AdminRegistryState|adminRegistryState/);assert.doesNotMatch(bundle,/adminRegistry\.json|rcas\.json|launchRegistry\.json|topRetailRegistry\.json/i);assert.match(bundle,/'M1_ITEM_ESTOQUE', 'M2_CLIENTE_RCA', 'M3_MOVIMENTO_VENDAS', 'M4_HISTORICO_TRANSICAO'/);assert.match(cloud,/adminRegistryState/);});
test('Fase 3A — diagnósticos básicos identificam conflitos ativos',()=>{const rcas=[{id:'1',currentCode:'10',legacyCode:'9',name:'A',coordinatorCode:null,coordinatorName:null,role:'PRINCIPAL',active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW},{id:'2',currentCode:'20',legacyCode:'9',name:'B',coordinatorCode:null,coordinatorName:null,role:'PRINCIPAL',active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW}] as RcaRegistryRecord[];assert.ok(diagnoseRcaRecords(rcas).some(item=>item.code==='RCA_LEGACY_AMBIGUOUS'));assert.ok(diagnoseLaunchRecords([{id:'a',winthorCode:'1',ean:'7891234567890',description:null,type:null,status:null,active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW},{id:'b',winthorCode:'2',ean:'7891234567890',description:null,type:null,status:null,active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW}]).some(item=>item.code==='LAUNCH_EAN_AMBIGUOUS'));});
