import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import * as XLSX from 'xlsx';
import { emptyAdminRegistryState, type AdminRegistryState, type LaunchRegistryRecord, type RcaRegistryRecord, type TopRetailRegistryRecord } from '../src/canonical/adminRegistry.ts';
import { canonicalAdminRegistryHash, canonicalInputHash } from '../src/canonical/adminRegistryIdentity.ts';
import { applyAdminRegistryCanonicalAuthority } from '../src/canonical/adminRegistryCanonicalAuthority.ts';
import { resolveLaunchAuthority } from '../src/canonical/adminRegistryAuthority.ts';
import { createRcaResolver } from '../src/canonical/rcaResolver.ts';
import { materializeTopRetailRouteInM2 } from '../src/canonical/topRetailM2.ts';
import { CANONICAL_ENGINE_VERSION, REQUIRED_SOURCE_IDS, sourceImportTestHelpers } from '../src/canonical/sourceImport.ts';
import { canonicalInputHashV3, stagingManifestHashV2 } from '../src/canonical/sourceReplacementIdentity.ts';
import { EMPTY_SOURCE_REPLACEMENT_PROOF } from '../src/canonical/sourceReplacementState.ts';
import { createSystemDataOperationCoordinator } from '../src/canonical/systemDataOperationCoordinator.ts';
import { createRegistryUpdateCoordinator, executeRegistryUpdateTransaction, type RegistryTransactionDependencies, type RegistryUpdateControls, type RegistryUpdateRuntime } from '../src/pages/admin/registryUpdateFlow.ts';
import { cloudSyncTestHelpers, type CloudRestoreDependencies, type CloudSnapshot, type CloudUploadDependencies, type DeviceSyncIdentity } from '../src/canonical/cloudSync.ts';
import { recoverTechnicalBundle } from '../src/canonical/bundleRecovery.ts';
import { canonicalBundleTestHelpers, type BundleImportResult, type PreparedCanonicalBundle } from '../src/canonical/bundleStore.ts';
import { createExcelWorkbook, exportPayload } from '../src/canonical/exporters.ts';
import type { ActiveCanonicalBundle } from '../src/canonical/runtime.ts';
import { canonicalInputHashV2, rcaTargetRegistryHash } from '../src/canonical/targetIdentity.ts';
import { emptyTargetState, type TargetState } from '../src/canonical/targetStore.ts';
import type { CanonicalBundle, CanonicalList, ParsedSource, RawTyped } from '../src/canonical/types.ts';
import { sourceStorageV1Fixture, V20_ENGINE, V21_ENGINE } from './phase5b-fixtures.ts';

const NOW='2026-09-06T16:30:00.000Z',LATER='2026-09-06T17:30:00.000Z';
const ENGINE=V21_ENGINE; const V20=V20_ENGINE; const V19='browser-stage4-product-assortment-v19-admin-registry-authority';
const sourceText=(relative:string)=>readFileSync(new URL(relative,import.meta.url),'utf8');
const cell=(typed:unknown,raw:unknown=typed):RawTyped=>({raw,typed});
const row=(fields:Record<string,unknown>,sourceRow=2)=>Object.fromEntries([...Object.entries(fields).map(([key,value])=>[key,cell(value)]),['__source_row',cell(sourceRow)]]) as Record<string,RawTyped>;
const parsed=(source:string,fileName:string,rows:ParsedSource['rows']):ParsedSource=>({source,fileName,sheet:'test',rows,audits:[]});
const rcaPhysical=(current='10',legacy='9',name='Fonte A',coordinator='1')=>parsed('NOVOS RCAS.xlsx','NOVOS RCAS.xlsx',[row({current_rca_code_principal:current,legacy_rca_code_principal:legacy,rca_name_raw_principal:name,coordinator_code_principal:coordinator,coordinator_name_principal:`Coord ${coordinator}`})]);
const launchPhysical=(status='A')=>parsed('lançamentos.xlsx','lançamentos.xlsx',[row({launch_winthor_code:'10',launch_ean:'7891234567890',launch_description:'Produto',launch_type:'NOVA LINHA',launch_status:status})]);
const topPhysical=(competence:'2026-08'|'2026-09'='2026-08',network='Fonte Rede')=>parsed("08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx",competence==='2026-08'?"08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx":"09.26 Roteiro Ativo Top Varejistas Set'26 - Final.xlsx",[row({cnpj:'12345678000199',top_network:network,banner:'Fonte Banner',manager_cnpj:'98765432000188',group_code:'F1',top_category:'FONTE',top_target:100})]);
function rca(overrides:Partial<RcaRegistryRecord>={}):RcaRegistryRecord{return{id:'R1',currentCode:'10',legacyCode:'9',name:'Registry B',coordinatorCode:'2',coordinatorName:'Coord 2',role:'PRINCIPAL',active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW,...overrides}}
function launch(overrides:Partial<LaunchRegistryRecord>={}):LaunchRegistryRecord{return{id:'L1',winthorCode:'10',ean:'7891234567890',description:'Produto',type:'NOVA LINHA',status:'B',active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW,...overrides}}
function top(overrides:Partial<TopRetailRegistryRecord>={}):TopRetailRegistryRecord{return{id:'T1',competence:'2026-08',customerCnpj:'12345678000199',network:'Registry Rede',banner:'Registry Banner',managerCnpj:'11111111000111',groupCode:'R1',category:'REGISTRY',topTarget:200,active:true,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW,...overrides}}
function registry(parts:Partial<Pick<AdminRegistryState,'rcas'|'launches'|'topRetailers'>>={}):AdminRegistryState{return{...emptyAdminRegistryState(NOW),rcas:parts.rcas??[],launches:parts.launches??[],topRetailers:parts.topRetailers??[]}}
function list(id:CanonicalList['id'],records:CanonicalList['records']=[],competence='2026-09'):CanonicalList{return{id,records,sources:[],generatedAt:NOW,competence,snapshotDate:`${competence}-06`,warnings:[],errors:[]}}
function emptyBundle(overrides:Partial<Record<CanonicalList['id'],CanonicalList>>={}):CanonicalBundle{return{version:'v1',generatedAt:NOW,parsedSources:[],lists:{M1_ITEM_ESTOQUE:overrides.M1_ITEM_ESTOQUE??list('M1_ITEM_ESTOQUE'),M2_CLIENTE_RCA:overrides.M2_CLIENTE_RCA??list('M2_CLIENTE_RCA'),M3_MOVIMENTO_VENDAS:overrides.M3_MOVIMENTO_VENDAS??list('M3_MOVIMENTO_VENDAS'),M4_HISTORICO_TRANSICAO:overrides.M4_HISTORICO_TRANSICAO??list('M4_HISTORICO_TRANSICAO')}}}
const targetEmpty=()=>emptyTargetState(NOW);
async function completeV21(id:string,sourceHash:string,registryHash:string,target:TargetState|null=targetEmpty()):Promise<ActiveCanonicalBundle>{const th=await rcaTargetRegistryHash(target),ih=await canonicalInputHashV3(sourceHash,registryHash,th,EMPTY_SOURCE_REPLACEMENT_PROOF);return{status:'ACTIVE',motorBuildId:id,stagingManifestHash:sourceHash,adminRegistryHash:registryHash,rcaTargetRegistryHash:th,sourceContractVersion:'v2',sourceReplacementProofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,sourceReplacements:[],canonicalInputHash:ih,schemaVersion:'v1',engineVersion:ENGINE,approvedAt:NOW,rowCounts:{M1_ITEM_ESTOQUE:0,M2_CLIENTE_RCA:0,M3_MOVIMENTO_VENDAS:0,M4_HISTORICO_TRANSICAO:0},factTypeCounts:{SALE:0,INBOUND_ORDER:0,RECEIPT:0,TARGET:0}}}
async function completeV20(id:string,sourceHash:string,registryHash:string,target:TargetState|null=targetEmpty()):Promise<ActiveCanonicalBundle>{const th=await rcaTargetRegistryHash(target),ih=await canonicalInputHashV2(sourceHash,registryHash,th);return{status:'ACTIVE',motorBuildId:id,stagingManifestHash:sourceHash,adminRegistryHash:registryHash,rcaTargetRegistryHash:th,canonicalInputHash:ih,schemaVersion:'v1',engineVersion:V20,approvedAt:NOW,rowCounts:{M1_ITEM_ESTOQUE:0,M2_CLIENTE_RCA:0,M3_MOVIMENTO_VENDAS:0,M4_HISTORICO_TRANSICAO:0},factTypeCounts:{SALE:0,INBOUND_ORDER:0,RECEIPT:0,TARGET:0}}}
function completeLegacy(id:string,sourceHash:string,engineVersion:string,adminRegistryHash?:string,canonicalInputHash?:string):ActiveCanonicalBundle{return{status:'ACTIVE',motorBuildId:id,stagingManifestHash:sourceHash,...(adminRegistryHash?{adminRegistryHash}:{}),...(canonicalInputHash?{canonicalInputHash}:{}),schemaVersion:'v1',engineVersion,approvedAt:NOW,rowCounts:{M1_ITEM_ESTOQUE:0,M2_CLIENTE_RCA:0,M3_MOVIMENTO_VENDAS:0,M4_HISTORICO_TRANSICAO:0},factTypeCounts:{SALE:0,INBOUND_ORDER:0,RECEIPT:0,TARGET:0}}}
const identity:DeviceSyncIdentity={workspaceId:'11111111-1111-4111-8111-111111111111',secret:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'};
const settings={networkTargetByCompetence:{},networkAllocationByCompetence:{},sellOutTargetByCompetence:{},positivityTargetByCompetence:{},legacySellOutTarget:null,legacyPositivityTarget:null,inboundForecastByInvoice:{}};
const sourceSnapshot=sourceStorageV1Fixture();

// C1–C6 identity
test('C1 — adminRegistryHash é determinístico com arrays em ordem diferente',async()=>{const a=registry({rcas:[rca({id:'R1'}),rca({id:'R2',currentCode:'20',legacyCode:'19'})],launches:[launch({id:'L1'}),launch({id:'L2',winthorCode:'20',ean:'7891234567891'})],topRetailers:[top({id:'T1'}),top({id:'T2',customerCnpj:'22345678000199'})]});const b={...a,rcas:[...a.rcas].reverse(),launches:[...a.launches].reverse(),topRetailers:[...a.topRetailers].reverse()};assert.equal(await canonicalAdminRegistryHash(a),await canonicalAdminRegistryHash(b));});
test('C2 — metadados não canônicos não alteram adminRegistryHash',async()=>{const a=registry({rcas:[rca()]});const b=structuredClone(a);b.rcas[0].createdAt=LATER;b.rcas[0].updatedAt=LATER;b.rcas[0].note='x';assert.equal(await canonicalAdminRegistryHash(a),await canonicalAdminRegistryHash(b));});
test('C3 — qualquer mudança semântica de RCA, Launch ou Top altera adminRegistryHash',async()=>{const base=registry({rcas:[rca()],launches:[launch()],topRetailers:[top()]}),h=await canonicalAdminRegistryHash(base);assert.notEqual(h,await canonicalAdminRegistryHash({...base,rcas:[rca({name:'Outro'})]}));assert.notEqual(h,await canonicalAdminRegistryHash({...base,launches:[launch({status:'Outro'})]}));assert.notEqual(h,await canonicalAdminRegistryHash({...base,topRetailers:[top({topTarget:999})]}));});
test('C4 — canonicalInputHash v1 continua dependendo somente de sourceHash + registryHash + formato',async()=>{const a=await canonicalInputHash('SOURCE_A','REG_A');assert.equal(a,await canonicalInputHash('SOURCE_A','REG_A'));assert.notEqual(a,await canonicalInputHash('SOURCE_B','REG_A'));assert.notEqual(a,await canonicalInputHash('SOURCE_A','REG_B'));});
test('C5 — ActiveCanonicalBundle corrente contém identidade v21 completa e v20 permanece legado',()=>{const active=sourceImportTestHelpers.activeFromLists(emptyBundle().lists,'SOURCE','REGISTRY','TARGET','INPUT');assert.equal(active.stagingManifestHash,'SOURCE');assert.equal(active.adminRegistryHash,'REGISTRY');assert.equal(active.rcaTargetRegistryHash,'TARGET');assert.equal(active.canonicalInputHash,'INPUT');assert.equal(active.sourceContractVersion,'v2');assert.equal(active.sourceReplacementProofHash,EMPTY_SOURCE_REPLACEMENT_PROOF);assert.deepEqual(active.sourceReplacements,[]);assert.equal(active.engineVersion,ENGINE);assert.notEqual(active.engineVersion,V20);});
test('C6 — motorBuildId usa prefixo do canonicalInputHash v21',()=>{const input='abcdef1234567890',active=sourceImportTestHelpers.activeFromLists(emptyBundle().lists,'S','R','T',input);assert.match(active.motorBuildId,new RegExp(`-${input.slice(0,10)}$`));});

// C7–C16 RCA
test('C7 — Registry null preserva semanticamente M1-M4 físicos',()=>{const before=emptyBundle({M1_ITEM_ESTOQUE:list('M1_ITEM_ESTOQUE',[{a:1}]),M2_CLIENTE_RCA:list('M2_CLIENTE_RCA',[{b:2}]),M3_MOVIMENTO_VENDAS:list('M3_MOVIMENTO_VENDAS',[{c:3}]),M4_HISTORICO_TRANSICAO:list('M4_HISTORICO_TRANSICAO',[{d:4}])});const snapshot=structuredClone(before);assert.deepEqual(applyAdminRegistryCanonicalAuthority(before,[],null),snapshot);});
test('C8 — SOURCE_SEED idêntico reproduz autoridade da fonte física',()=>{const physical=createRcaResolver([rcaPhysical()]).resolveCurrent('10');const seeded=createRcaResolver([rcaPhysical()],registry({rcas:[rca({origin:'SOURCE_SEED',name:'Fonte A',coordinatorCode:'1',coordinatorName:'Coord 1'})]})).resolveCurrent('10');assert.deepEqual([seeded.currentCode,seeded.legacyCode,seeded.name,seeded.coordinatorCode],[physical.currentCode,physical.legacyCode,physical.name,physical.coordinatorCode]);const p=resolveLaunchAuthority(null,launchPhysical().rows[0],{winthorCode:'10',eans:['7891234567890'],competence:'2026-09'});const s=resolveLaunchAuthority(registry({launches:[launch({origin:'SOURCE_SEED',status:'A'})]}),launchPhysical().rows[0],{winthorCode:'10',eans:['7891234567890'],competence:'2026-09'});assert.equal(p.authority,'IMPORTED_SOURCE');assert.equal(s.authority,'ADMIN_REGISTRY');});
test('C9 — RCA MANUAL CURRENT vence fonte em M2/M3',()=>{const r=createRcaResolver([rcaPhysical()],registry({rcas:[rca()]})).resolveCurrent('10',undefined,'2026-09');assert.equal(r.name,'Registry B');assert.equal(r.coordinatorCode,'2');assert.equal(r.authority,'MANUAL_REGISTRY');});
test('C10 — RCA SOURCE_SEED vence fonte física',()=>{const r=createRcaResolver([rcaPhysical()],registry({rcas:[rca({origin:'SOURCE_SEED',name:'Seed B'})]})).resolveCurrent('10',undefined,'2026-09');assert.equal(r.name,'Seed B');assert.equal(r.authority,'ADMIN_REGISTRY');});
test('C11 — RCA MANUAL inativo funciona como tombstone',()=>{const r=createRcaResolver([rcaPhysical()],registry({rcas:[rca({active:false})]})).resolveCurrent('10',undefined,'2026-09');assert.equal(r.canonicalId,null);assert.equal(r.auditCode,'ADMIN_REGISTRY_RCA_TOMBSTONE');});
test('C12 — RCA MANUAL ambíguo não cai para fonte inferior',()=>{const r=createRcaResolver([rcaPhysical()],registry({rcas:[rca({id:'R1',name:'A'}),rca({id:'R2',name:'B',coordinatorCode:'3'})]})).resolveCurrent('10',undefined,'2026-09');assert.equal(r.status,'AMBIGUOUS_RCA_CODE');assert.equal(r.canonicalId,null);assert.equal(r.auditCode,'ADMIN_REGISTRY_RCA_AMBIGUOUS');});
test('C13 — namespace LEGACY respeita de-para MANUAL do Registry',()=>{const r=createRcaResolver([rcaPhysical()],registry({rcas:[rca({currentCode:'20',legacyCode:'9'})]})).resolveLegacy('9',undefined,'2026-09');assert.equal(r.currentCode,'20');assert.equal(r.canonicalId,'RCA:20');});
test('C14 — vigência RCA em M3 usa competência do fato',()=>{const resolver=createRcaResolver([rcaPhysical()],registry({rcas:[rca({name:'Setembro',validFromCompetence:'2026-09'})]}));assert.equal(resolver.resolveCurrent('10',undefined,'2026-08').name,'Fonte A');assert.equal(resolver.resolveCurrent('10',undefined,'2026-09').name,'Setembro');});
test('C15 — M4 LEGACY aplica vigência pela movement_date',()=>{const bundle=emptyBundle({M4_HISTORICO_TRANSICAO:list('M4_HISTORICO_TRANSICAO',[{legacy_rca_code:'9',movement_date:'2026-08-20',rca_canonical_id:'RCA:10',row_type:'SALE_379'},{legacy_rca_code:'9',movement_date:'2026-09-20',rca_canonical_id:'RCA:10',row_type:'SALE_379'}])});applyAdminRegistryCanonicalAuthority(bundle,[rcaPhysical()],registry({rcas:[rca({currentCode:'20',legacyCode:'9',validFromCompetence:'2026-09'})]}));assert.equal(bundle.lists.M4_HISTORICO_TRANSICAO.records[0].rca_canonical_id,'RCA:10');assert.equal(bundle.lists.M4_HISTORICO_TRANSICAO.records[1].rca_canonical_id,'RCA:20');});
test('C16 — vigência limitada sem competência não é adivinhada; ilimitada aplica',()=>{const limited=createRcaResolver([rcaPhysical()],registry({rcas:[rca({validFromCompetence:'2026-09'})]})).resolveCurrent('10');assert.equal(limited.status,'ADMIN_REGISTRY_VALIDITY_UNRESOLVED');assert.equal(limited.canonicalId,null);assert.equal(createRcaResolver([rcaPhysical()],registry({rcas:[rca()]})).resolveCurrent('10').name,'Registry B');});

// C17–C21 Launch
function launchBundle(competence='2026-09'){return emptyBundle({M1_ITEM_ESTOQUE:list('M1_ITEM_ESTOQUE',[{item_canonical_id:'ITEM:10',winthor_code:'10',internal_ean:'7891234567890',industry_ean:null,is_launch:true,launch_status:'A',mapping_status:'MATCHED',source_lineage:'lançamentos.xlsx'}],competence)})}
test('C17 — Lançamento MANUAL vence status da planilha',()=>{const bundle=launchBundle();applyAdminRegistryCanonicalAuthority(bundle,[launchPhysical('A')],registry({launches:[launch({status:'B'})]}));assert.equal(bundle.lists.M1_ITEM_ESTOQUE.records[0].launch_status,'B');});
test('C18 — Lançamento SOURCE_SEED vence fonte física',()=>{const bundle=launchBundle();applyAdminRegistryCanonicalAuthority(bundle,[launchPhysical('A')],registry({launches:[launch({origin:'SOURCE_SEED',status:'SEED'})]}));assert.equal(bundle.lists.M1_ITEM_ESTOQUE.records[0].launch_status,'SEED');});
test('C19 — tombstone de Lançamento impede ressurreição pela planilha',()=>{const bundle=launchBundle();applyAdminRegistryCanonicalAuthority(bundle,[launchPhysical('A')],registry({launches:[launch({active:false})]}));assert.equal(bundle.lists.M1_ITEM_ESTOQUE.records[0].is_launch,false);assert.equal(bundle.lists.M1_ITEM_ESTOQUE.records[0].launch_status,null);});
test('C20 — ambiguidade de Lançamento não seleciona fonte inferior e gera audit',()=>{const bundle=launchBundle();applyAdminRegistryCanonicalAuthority(bundle,[launchPhysical('A')],registry({launches:[launch({id:'L1',status:'B'}),launch({id:'L2',status:'C'})]}));assert.equal(bundle.lists.M1_ITEM_ESTOQUE.records[0].is_launch,false);assert.ok(bundle.lists.M1_ITEM_ESTOQUE.warnings.some(a=>a.code==='ADMIN_REGISTRY_LAUNCH_AMBIGUOUS'));});
test('C21 — Lançamento Registry fora da vigência não substitui fonte',()=>{const bundle=launchBundle('2026-09');applyAdminRegistryCanonicalAuthority(bundle,[launchPhysical('A')],registry({launches:[launch({status:'OUTUBRO',validFromCompetence:'2026-10'})]}));assert.equal(bundle.lists.M1_ITEM_ESTOQUE.records[0].launch_status,'A');});

// C22–C27 Top
function topM2(competence='2026-08'){return list('M2_CLIENTE_RCA',[{customer_canonical_id:'CUSTOMER:12345678000199',cnpj:'12345678000199',top_network:null,top_banner:null,manager_cnpj:null,top_group_code:null,top_category:null,top_target:null,source_lineage:'BASE'}],competence)}
test('C22 — Top MANUAL vence Roteiro na mesma competência',()=>{const r=materializeTopRetailRouteInM2(topM2(),[topPhysical()],registry({topRetailers:[top()]})).records[0];assert.equal(r.top_network,'Registry Rede');assert.equal(r.manager_cnpj,'11111111000111');assert.equal(r.top_target,200);});
test('C23 — Top SOURCE_SEED vence fonte',()=>{const m=materializeTopRetailRouteInM2(topM2(),[topPhysical()],registry({topRetailers:[top({origin:'SOURCE_SEED',network:'Seed Rede'})]}));assert.equal(m.records[0].top_network,'Seed Rede');assert.equal(m.records[0].network_resolution_status,'ADMIN_REGISTRY');});
test('C24 — Top MANUAL inativo remove cliente do universo Top mensal',()=>{assert.equal(materializeTopRetailRouteInM2(topM2(),[topPhysical()],registry({topRetailers:[top({active:false})]})).records[0].top_network,null);});
test('C25 — Roteiro agosto nunca vira fallback de setembro',()=>{const m=materializeTopRetailRouteInM2(topM2('2026-09'),[topPhysical('2026-08')],null);assert.equal(m.records[0].top_network,null);});
test('C26 — Registry setembro materializa Top mesmo com Roteiro físico agosto',()=>{const m=materializeTopRetailRouteInM2(topM2('2026-09'),[topPhysical('2026-08')],registry({topRetailers:[top({competence:'2026-09',network:'Setembro Registry'})]}));assert.equal(m.records[0].top_network,'Setembro Registry');assert.equal(m.records[0].top_route_competence,'2026-09');});
test('C27 — Top MANUAL ambíguo não escolhe vencedor silencioso',()=>{const m=materializeTopRetailRouteInM2(topM2(),[topPhysical()],registry({topRetailers:[top({id:'T1'}),top({id:'T2',network:'Conflito'})]}));assert.equal(m.records[0].top_network,null);assert.ok(m.warnings.some(a=>a.code==='ADMIN_REGISTRY_TOP_AMBIGUOUS'));});

// C28–C32 transaction/lifecycle
async function transactionHarness(options:{failBuild?:boolean;failSync?:boolean}={}){let currentRegistry:AdminRegistryState|null=registry({rcas:[rca({name:'A'})]});const target=targetEmpty(),sourceHash='SOURCE',oldRh=await canonicalAdminRegistryHash(currentRegistry);let active:ActiveCanonicalBundle|null=await completeV21('BUILD_A',sourceHash,oldRh,target);const next=registry({rcas:[rca({name:'B'})]}),phases:string[]=[];const runtime:RegistryUpdateRuntime={getActive:()=>active,activate:value=>{active=value},deactivate:()=>{active=null}};const deps:RegistryTransactionDependencies={loadRegistry:async()=>currentRegistry?structuredClone(currentRegistry):null,replaceRegistry:async state=>{currentRegistry=state?structuredClone(state):null;return currentRegistry},loadTargetState:()=>structuredClone(target),build:async state=>{if(options.failBuild)throw new Error('BUILD_FAIL');return completeV21('BUILD_B',sourceHash,await canonicalAdminRegistryHash(state),target)},registryHash:canonicalAdminRegistryHash,targetHash:rcaTargetRegistryHash,inputHash:canonicalInputHashV3,sync:async()=>{if(options.failSync)throw new Error('SYNC_FAIL');return{status:'NOT_PAIRED'}},engineVersion:ENGINE};const mutate=async()=>{currentRegistry=structuredClone(next);return'OK'};const controls:RegistryUpdateControls={setPhase:phase=>{phases.push(phase)}};return{read:()=>({currentRegistry,active,phases}),mutate,runtime,deps,controls};}
test('C28 — Registry SAVE → BUILD → ACTIVATE produz hashes correspondentes v21',async()=>{const h=await transactionHarness(),result=await executeRegistryUpdateTransaction(h.mutate,h.runtime,h.controls,h.deps);assert.equal(result.phase,'SUCCESS');assert.equal(h.read().active?.motorBuildId,'BUILD_B');assert.equal((h.read().currentRegistry?.rcas[0] as RcaRegistryRecord).name,'B');assert.deepEqual(h.read().phases,['MUTATING','BUILDING','ACTIVATING','SYNCING']);assert.equal(h.read().active?.sourceContractVersion,'v2');assert.equal(h.read().active?.sourceReplacementProofHash,EMPTY_SOURCE_REPLACEMENT_PROOF);});
test('C29 — falha de build restaura Registry A e Build A',async()=>{const h=await transactionHarness({failBuild:true});await assert.rejects(()=>executeRegistryUpdateTransaction(h.mutate,h.runtime,h.controls,h.deps),/BUILD_FAIL/);assert.equal((h.read().currentRegistry?.rcas[0] as RcaRegistryRecord).name,'A');assert.equal(h.read().active?.motorBuildId,'BUILD_A');});
test('C30 — falha de sync preserva Registry B e Build B localmente',async()=>{const h=await transactionHarness({failSync:true}),result=await executeRegistryUpdateTransaction(h.mutate,h.runtime,h.controls,h.deps);assert.equal(result.phase,'LOCAL_SUCCESS_SYNC_FAILED');assert.equal((h.read().currentRegistry?.rcas[0] as RcaRegistryRecord).name,'B');assert.equal(h.read().active?.motorBuildId,'BUILD_B');});
test('C31 — REGISTRY_UPDATE é global single-flight contra Bases/Sync/Restore/Bundle e vice-versa',async()=>{const c=createSystemDataOperationCoordinator();let release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve});const r=c.run('REGISTRY_UPDATE',async()=>pending);await Promise.resolve();for(const owner of ['BASE_UPDATE','SYNC_SEND','SYNC_RESTORE','BUNDLE_RECOVERY'] as const)assert.deepEqual(await c.run(owner,async()=>undefined),{status:'BUSY',owner:'REGISTRY_UPDATE'});release();await r;let releaseBase!:()=>void;const p2=new Promise<void>(resolve=>{releaseBase=resolve}),base=c.run('BASE_UPDATE',async()=>p2);await Promise.resolve();assert.deepEqual(await c.run('REGISTRY_UPDATE',async()=>undefined),{status:'BUSY',owner:'BASE_UPDATE'});releaseBase();await base;});
test('C32 — lifecycle de Registry Update sobrevive unsubscribe/remount',async()=>{const c=createRegistryUpdateCoordinator();let release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve});let first=c.getState();const off=c.subscribe(state=>{first=state});const run=c.run(async controls=>{controls.setPhase('BUILDING');await pending;return{phase:'SUCCESS',status:'OK',error:''}});await Promise.resolve();assert.equal(first.phase,'BUILDING');off();let remount=c.getState();const off2=c.subscribe(state=>{remount=state});assert.equal(remount.busy,true);release();await run;assert.equal(remount.phase,'SUCCESS');off2();});

// C33–C36 orchestration/migration
test('C33 — Base Update usa Registry atual e não o reseta',()=>{const content=sourceText('../src/canonical/sourceImport.ts');assert.match(content,/loadAdminRegistryState\(\)/);assert.match(content,/canonicalAdminRegistryHash\(registry\)/);assert.doesNotMatch(content,/replaceAdminRegistryState|clearAdminRegistry/);});
test('C34 — incremental é proibido quando engine, registryHash, targetHash ou replacement proof diferem',()=>{const content=sourceText('../src/canonical/sourceImport.ts');assert.match(content,/base\.active\.engineVersion !== CANONICAL_ENGINE_VERSION/);assert.match(content,/base\.active\.adminRegistryHash !== registryHash/);assert.match(content,/base\.active\.rcaTargetRegistryHash !== targetHash/);assert.match(content,/base\.active\.sourceReplacementProofHash !== proofHash/);assert.match(content,/buildCanonicalFromStoredSources\(/);});
test('C35 — v18/v19/v20 são legado e migram para engine v21 pelas fontes',()=>{assert.equal(CANONICAL_ENGINE_VERSION,ENGINE);assert.notEqual(V20,ENGINE);const data=sourceText('../src/store/DataContext.tsx');assert.match(data,/legacyToMigrate/);assert.match(data,/rebuildForCanonicalEngine/);assert.match(data,/activeCanonical.*engineVersion===CANONICAL_ENGINE_VERSION/);});
test('C36 — migração para v21 usa Registry, TargetState e ReplacementState locais existentes',()=>{const data=sourceText('../src/store/DataContext.tsx'),sourceImport=sourceText('../src/canonical/sourceImport.ts');assert.match(data,/buildCanonicalFromStoredSources/);assert.match(data,/bootstrapTargetStateFromReportSettings/);assert.match(sourceImport,/loadAdminRegistryState/);assert.match(sourceImport,/loadTargetState/);assert.match(sourceImport,/loadSourceReplacementState/);assert.match(sourceImport,/applyAdminRegistryCanonicalAuthority/);});

// C37–C40 Cloud
function uploadDeps(active:ActiveCanonicalBundle,reg:AdminRegistryState|null,target:TargetState|null,onPut:()=>void):CloudUploadDependencies{return{getActive:()=>active,exportSources:async()=>sourceSnapshot,sourceManifestHash:(snapshot,replaced=[])=>stagingManifestHashV2(snapshot.staging,replaced),registryHash:canonicalAdminRegistryHash,targetHash:rcaTargetRegistryHash,replacementProofHash:async()=>({proofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,replacements:[],replacedSourceIds:[]}),inputHash:canonicalInputHashV3,loadSettings:()=>settings,loadCompetence:()=>null,loadAdminRegistry:async()=>reg,loadTargetState:()=>target,loadSourceReplacementState:()=>null,encryptSnapshot:async()=>new Uint8Array([1]),uploadPayload:async()=>{onPut();return{updatedAt:NOW,bytes:1}},saveState:()=>undefined,now:()=>NOW}}
test('C37 — Cloud snapshot v21 consistente valida source/registry/target/proof/input e faz 1 PUT',async()=>{const reg=registry({rcas:[rca()]}),target=targetEmpty(),rh=await canonicalAdminRegistryHash(reg),sourceHash=await stagingManifestHashV2(sourceSnapshot.staging,[]),active=await completeV21('BUILD',sourceHash,rh,target);let puts=0;const result=await cloudSyncTestHelpers.uploadCurrentDeviceSnapshotWithDependencies(identity,uploadDeps(active,reg,target,()=>{puts+=1}));assert.equal(result.active.canonicalInputHash,active.canonicalInputHash);assert.equal(puts,1);});
test('C38 — Registry diferente durante captura aborta antes do PUT',async()=>{const a=registry({rcas:[rca({name:'A'})]}),b=registry({rcas:[rca({name:'B'})]}),target=targetEmpty(),sourceHash=await stagingManifestHashV2(sourceSnapshot.staging,[]),active=await completeV21('BUILD',sourceHash,await canonicalAdminRegistryHash(a),target);let puts=0;await assert.rejects(()=>cloudSyncTestHelpers.uploadCurrentDeviceSnapshotWithDependencies(identity,uploadDeps(active,b,target,()=>{puts+=1})),/SYNC_SNAPSHOT_CHANGED_DURING_CAPTURE/);assert.equal(puts,0);});
test('C39 — restore Cloud sources+Registry+Target produz build v21 com hashes restaurados',async()=>{const remote=registry({rcas:[rca({name:'Remote'})]}),target=targetEmpty(),rh=await canonicalAdminRegistryHash(remote),sourceHash=await stagingManifestHashV2(sourceSnapshot.staging,[]),remoteActive=await completeV21('REMOTE',sourceHash,rh,target);let current:AdminRegistryState|null=registry({rcas:[rca({name:'Local'})]}),currentTarget:TargetState|null=target;const deps:CloudRestoreDependencies={exportSources:async()=>sourceSnapshot,loadSettings:()=>settings,loadCompetence:()=>null,loadAdminRegistry:async()=>current,loadTargetState:()=>currentTarget,loadSourceReplacementState:()=>null,restoreSources:async()=>undefined,restoreSettings:()=>settings,replaceCompetence:()=>null,replaceAdminRegistry:async state=>{current=state;return current},replaceTargetState:state=>{currentTarget=state;return currentTarget},replaceSourceReplacementState:state=>state,build:async()=>remoteActive};const snapshot:CloudSnapshot={format:'blue-jacket-device-sync/v1',createdAt:NOW,active:remoteActive,sources:sourceSnapshot,settings,adminRegistryState:remote,targetState:target};const rebuilt=await cloudSyncTestHelpers.applyCloudSnapshot(snapshot,deps);assert.equal(rebuilt.adminRegistryHash,rh);assert.equal((current?.rcas[0] as RcaRegistryRecord).name,'Remote');assert.equal(rebuilt.sourceReplacementProofHash,EMPTY_SOURCE_REPLACEMENT_PROOF);});
test('C40 — snapshot Cloud legado sem Registry/ReplacementState preserva Registry local mas usa proof físico EMPTY',async()=>{const local=registry({rcas:[rca({name:'Local'})]}),target=targetEmpty();let current:AdminRegistryState|null=local;const sourceHash=await stagingManifestHashV2(sourceSnapshot.staging,[]),rebuilt=await completeV21('NEW',sourceHash,await canonicalAdminRegistryHash(local),target);const deps:CloudRestoreDependencies={exportSources:async()=>sourceSnapshot,loadSettings:()=>settings,loadCompetence:()=>null,loadAdminRegistry:async()=>current,loadTargetState:()=>target,loadSourceReplacementState:()=>null,restoreSources:async()=>undefined,restoreSettings:()=>settings,replaceCompetence:()=>null,replaceAdminRegistry:async state=>{current=state;return current},replaceSourceReplacementState:state=>state,build:async()=>rebuilt};await cloudSyncTestHelpers.applyCloudSnapshot({format:'blue-jacket-device-sync/v1',createdAt:NOW,active:null,sources:sourceSnapshot,settings},deps);assert.deepEqual(current,local);assert.equal(rebuilt.sourceReplacementProofHash,EMPTY_SOURCE_REPLACEMENT_PROOF);});

// C41–C46 Bundle
function prepared(active:ActiveCanonicalBundle):PreparedCanonicalBundle{const manifest={bundleFormat:'blue-jacket-canonical-bundle/v1' as const,motorBuildId:active.motorBuildId,stagingManifestHash:active.stagingManifestHash,...(active.adminRegistryHash?{adminRegistryHash:active.adminRegistryHash}:{}),...(active.rcaTargetRegistryHash?{rcaTargetRegistryHash:active.rcaTargetRegistryHash}:{}),...(active.sourceContractVersion?{sourceContractVersion:active.sourceContractVersion}:{}),...(active.sourceReplacementProofHash?{sourceReplacementProofHash:active.sourceReplacementProofHash}:{}),...(active.sourceReplacements?{sourceReplacements:active.sourceReplacements}:{}),...(active.canonicalInputHash?{canonicalInputHash:active.canonicalInputHash}:{}),schemaVersion:active.schemaVersion,engineVersion:active.engineVersion,rowCounts:active.rowCounts,files:{},createdAt:active.approvedAt};return{...activeToImport(active),bytes:new Uint8Array(),manifest}}
function activeToImport(active:ActiveCanonicalBundle):BundleImportResult{return{motorBuildId:active.motorBuildId,stagingManifestHash:active.stagingManifestHash,...(active.adminRegistryHash?{adminRegistryHash:active.adminRegistryHash}:{}),...(active.rcaTargetRegistryHash?{rcaTargetRegistryHash:active.rcaTargetRegistryHash}:{}),...(active.sourceContractVersion?{sourceContractVersion:active.sourceContractVersion}:{}),...(active.sourceReplacementProofHash?{sourceReplacementProofHash:active.sourceReplacementProofHash}:{}),...(active.sourceReplacements?{sourceReplacements:active.sourceReplacements}:{}),...(active.canonicalInputHash?{canonicalInputHash:active.canonicalInputHash}:{}),schemaVersion:active.schemaVersion,engineVersion:active.engineVersion,rowCounts:active.rowCounts,active}}
test('C41 — Bundle v21 com registry+target+proof locais correspondentes ativa compatível',async()=>{const active=await completeV21('BUNDLE','SOURCE','REG'),targetHash=active.rcaTargetRegistryHash!;let persisted=0,activated:ActiveCanonicalBundle|null=null;const result=await recoverTechnicalBundle({currentEngineVersion:ENGINE,inspectBundle:async()=>prepared(active),persistBundle:async value=>{persisted+=1;return activeToImport(value.active)},rebuildFromStaging:async()=>{throw new Error('NO_REBUILD')},activate:value=>{activated=value},localAdminRegistryHash:'REG',localRcaTargetRegistryHash:targetHash,localSourceReplacementProofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,localSourceReplacements:[]});assert.equal(result.mode,'COMPATIBLE');assert.equal(persisted,1);assert.equal(activated?.motorBuildId,'BUNDLE');});
test('C42 — Bundle v21 com Registry diferente não ativa listas importadas',async()=>{const imported=await completeV21('BUNDLE_A','SOURCE','REG_A'),rebuilt=await completeV21('BUILD_B','SOURCE','REG_B');let persisted=0,activated='';const result=await recoverTechnicalBundle({currentEngineVersion:ENGINE,inspectBundle:async()=>prepared(imported),persistBundle:async value=>{persisted+=1;return activeToImport(value.active)},rebuildFromStaging:async()=>rebuilt,activate:value=>{activated=value.motorBuildId},localAdminRegistryHash:'REG_B',localRcaTargetRegistryHash:rebuilt.rcaTargetRegistryHash!,localSourceReplacementProofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,localSourceReplacements:[]});assert.equal(result.mode,'REBUILT');assert.equal(persisted,0);assert.equal(activated,'BUILD_B');});
test('C43 — Bundle v18/v19/v20 é legado e rebuilda v21',async()=>{const imported=await completeV20('V20','LEGACY_SOURCE','REG'),rebuilt=await completeV21('V21','SOURCE_V2','REG');const result=await recoverTechnicalBundle({currentEngineVersion:ENGINE,inspectBundle:async()=>prepared(imported),persistBundle:async value=>activeToImport(value.active),rebuildFromStaging:async()=>rebuilt,activate:()=>undefined,localAdminRegistryHash:'REG',localRcaTargetRegistryHash:rebuilt.rcaTargetRegistryHash!,localSourceReplacementProofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,localSourceReplacements:[],localLegacyStagingManifestHash:'LEGACY_SOURCE'});assert.equal(result.mode,'REBUILT');assert.equal(result.active.engineVersion,ENGINE);assert.notEqual(result.active.engineVersion,V20);});
test('C44 — mismatch de staging legado continua rejeitado no recovery',async()=>{const imported=await completeV20('A','SOURCE_A','REG'),rebuilt=await completeV21('B','SOURCE_V2','OTHER');await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:ENGINE,inspectBundle:async()=>prepared(imported),persistBundle:async value=>activeToImport(value.active),rebuildFromStaging:async()=>rebuilt,activate:()=>undefined,localAdminRegistryHash:'OTHER',localRcaTargetRegistryHash:rebuilt.rcaTargetRegistryHash!,localSourceReplacementProofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,localSourceReplacements:[],localLegacyStagingManifestHash:'SOURCE_B'}),/BUNDLE_STAGING_SNAPSHOT_MISMATCH/);});
test('C45 — colisão de motorBuildId exige identidade completa incluindo target e replacement proof',async()=>{const active=await completeV21('SAME_ID','SOURCE','REG_A'),manifest={motorBuildId:'SAME_ID',stagingManifestHash:'SOURCE',adminRegistryHash:'REG_A',rcaTargetRegistryHash:active.rcaTargetRegistryHash,sourceContractVersion:'v2',sourceReplacementProofHash:'OTHER_PROOF',sourceReplacements:[],canonicalInputHash:'OTHER_INPUT',engineVersion:ENGINE,schemaVersion:'v1'};assert.equal(canonicalBundleTestHelpers.manifestIdentityMatchesActive(manifest,active),false);assert.match(sourceText('../src/canonical/bundleStore.ts'),/generatedBuildMatchesActive\(active\)/);});
test('C46 — persistência de Bundle mantém rollback da versão anterior',()=>{const content=sourceText('../src/canonical/bundleStore.ts');assert.match(content,/const previous = await repository\.get/);assert.match(content,/if \(previous\) await repository\.put\(previous\)/);assert.match(content,/BUNDLE_STORAGE_VERIFY_FAILED/);});

// C47–C48 exports
test('C47 — JSON provenance inclui registry, target, contract, proof, replacements e canonicalInputHash',()=>{const provenance={motorBuildId:'B',stagingManifestHash:'S',adminRegistryHash:'R',rcaTargetRegistryHash:'T',sourceContractVersion:'v2',sourceReplacementProofHash:'P',sourceReplacements:[{source:'lançamentos.xlsx',scope:'GLOBAL'}],canonicalInputHash:'I',schemaVersion:'v1',engineVersion:ENGINE};const payload=exportPayload(list('M1_ITEM_ESTOQUE'),provenance);assert.equal(payload.adminRegistryHash,'R');assert.equal(payload.rcaTargetRegistryHash,'T');assert.equal(payload.sourceContractVersion,'v2');assert.equal(payload.sourceReplacementProofHash,'P');assert.deepEqual(payload.sourceReplacements,[{source:'lançamentos.xlsx',scope:'GLOBAL'}]);assert.equal(payload.canonicalInputHash,'I');assert.equal(payload.engineVersion,ENGINE);});
test('C48 — Excel METADATA inclui identidade canônica completa v21',()=>{const provenance={motorBuildId:'B',stagingManifestHash:'S',adminRegistryHash:'R',rcaTargetRegistryHash:'T',sourceContractVersion:'v2',sourceReplacementProofHash:'P',sourceReplacements:[{source:'lançamentos.xlsx',scope:'GLOBAL'}],canonicalInputHash:'I',schemaVersion:'v1',engineVersion:ENGINE};const workbook=createExcelWorkbook(list('M1_ITEM_ESTOQUE'),provenance),values=XLSX.utils.sheet_to_json(workbook.Sheets.METADATA,{header:1}) as unknown[][],map=new Map(values.slice(1).map(r=>[r[0],r[1]]));assert.equal(map.get('adminRegistryHash'),'R');assert.equal(map.get('rcaTargetRegistryHash'),'T');assert.equal(map.get('sourceContractVersion'),'v2');assert.equal(map.get('sourceReplacementProofHash'),'P');assert.equal(map.get('sourceReplacements'),'[{"source":"lançamentos.xlsx","scope":"GLOBAL"}]');assert.equal(map.get('canonicalInputHash'),'I');assert.equal(map.get('engineVersion'),ENGINE);});

test('Fase 3B — exatamente 19 fontes físicas permanecem suportadas no contrato legado',()=>{assert.equal(REQUIRED_SOURCE_IDS.length,19);for(const source of ['NOVOS RCAS.xlsx','lançamentos.xlsx',"08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx",'Bussola de Metas AGOSTO - 2026 DEFINITIVA.xlsx'])assert.ok(REQUIRED_SOURCE_IDS.includes(source));});
test('Fase 3B — motores determinísticos não leem IndexedDB nem CompetenceStore diretamente',()=>{for(const file of ['../src/canonical/motors.ts','../src/canonical/rcaResolver.ts','../src/canonical/topRetailM2.ts','../src/canonical/adminRegistryCanonicalAuthority.ts','../src/canonical/targetAuthority.ts']){const content=sourceText(file);assert.doesNotMatch(content,/indexedDB|competenceStore|loadCompetenceState|currentCompetence/);}});
