import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import * as XLSX from 'xlsx';
import { emptyAdminRegistryState, type AdminRegistryState, type RcaRegistryRecord } from '../src/canonical/adminRegistry.ts';
import { canonicalAdminRegistryHash, canonicalInputHash } from '../src/canonical/adminRegistryIdentity.ts';
import { cloudSyncTestHelpers, type CloudRestoreDependencies, type CloudUploadDependencies, type DeviceSyncIdentity } from '../src/canonical/cloudSync.ts';
import type { CompetenceState } from '../src/canonical/competenceStore.ts';
import { createExcelWorkbook, exportPayload } from '../src/canonical/exporters.ts';
import { buildSellOutViewModel } from '../src/canonical/operationalViewModels.ts';
import { createSellOutWorkbook, createTopNetworksWorkbook, sellOutExportPayload, topNetworksExportPayload } from '../src/canonical/operationalExporters.ts';
import type { ReportSettings } from '../src/canonical/reportSettings.ts';
import type { ActiveCanonicalBundle } from '../src/canonical/runtime.ts';
import { CANONICAL_ENGINE_VERSION, REQUIRED_SOURCE_IDS } from '../src/canonical/sourceImport.ts';
import { canonicalInputHashV3, stagingManifestHashV2 } from '../src/canonical/sourceReplacementIdentity.ts';
import { EMPTY_SOURCE_REPLACEMENT_PROOF } from '../src/canonical/sourceReplacementState.ts';
import { createSystemDataOperationCoordinator } from '../src/canonical/systemDataOperationCoordinator.ts';
import { applyTargetAuthorityToM3, BUSSOLA_SOURCE_ID, materializeEffectiveTargetFacts, resolveTargetAuthority } from '../src/canonical/targetAuthority.ts';
import { canonicalInputHashV2, rcaTargetRegistryHash, targetStateHash } from '../src/canonical/targetIdentity.ts';
import { applyBussolaTargetSeedPreview, previewBussolaTargetSeed } from '../src/canonical/targetSeed.ts';
import { InMemoryTargetStateStorage, TargetStateRepository, bootstrapTargetStateFromReportSettings, emptyTargetState, validateTargetState, withGeneralTargets, withManualRcaTarget, type RcaTargetRecord, type TargetState } from '../src/canonical/targetStore.ts';
import { buildTopRetailNetworksViewModel } from '../src/canonical/topRetailNetworksModel.ts';
import { assertTargetCompetenceOpen, createTargetUpdateCoordinator, executeTargetUpdateTransaction, type TargetTransactionDependencies, type TargetUpdateRuntime } from '../src/pages/admin/targetUpdateFlow.ts';
import type { CanonicalList, ParsedSource, RawTyped } from '../src/canonical/types.ts';
import { sourceStorageV1Fixture, V20_ENGINE, V21_ENGINE } from './phase5b-fixtures.ts';

const NOW='2026-09-06T18:00:00.000Z',LATER='2026-09-06T19:00:00.000Z';
const sourceText=(relative:string)=>readFileSync(new URL(relative,import.meta.url),'utf8');
const typed=(value:unknown):RawTyped=>({raw:value,typed:value});
const rawRow=(values:Record<string,unknown>,sourceRow=2)=>Object.fromEntries([...Object.entries(values).map(([key,value])=>[key,typed(value)]),['__source_row',typed(sourceRow)]]) as Record<string,RawTyped>;
const parsed=(source:string,fileName:string,rows:ParsedSource['rows']):ParsedSource=>({source,fileName,sheet:'test',rows,audits:[]});
const canonicalList=(id:CanonicalList['id'],records:Record<string,unknown>[],competence='2026-08'):CanonicalList=>({id,records,sources:[],generatedAt:NOW,competence,snapshotDate:`${competence}-31`,warnings:[],errors:[]});
function rcaTarget(overrides:Partial<RcaTargetRecord>={}):RcaTargetRecord{return{id:'TARGET-1',competence:'2026-08',rcaCanonicalId:'RCA:10',sourceRcaCode:'9',salesTarget:1000,positivityTarget:10,active:true,origin:'MANUAL',createdAt:NOW,updatedAt:NOW,note:null,...overrides}}
function targetState(overrides:Partial<TargetState['records'][number]>={},targets:RcaTargetRecord[]=[rcaTarget()]):TargetState{return{format:'blue-jacket-target-state/v1',schemaVersion:'v1',createdAt:NOW,updatedAt:NOW,records:[{competence:'2026-08',sellOutTarget:5000,positivityTarget:50,networkTarget:3000,rcaTargets:targets,createdAt:NOW,updatedAt:NOW,...overrides}]}}
function settings(overrides:Partial<ReportSettings>={}):ReportSettings{return{networkTargetByCompetence:{},networkAllocationByCompetence:{},sellOutTargetByCompetence:{},positivityTargetByCompetence:{},legacySellOutTarget:null,legacyPositivityTarget:null,inboundForecastByInvoice:{},...overrides}}
function competence(status:'OPEN'|'CLOSED'='OPEN'):CompetenceState{return{schemaVersion:'v1',initializedAt:NOW,updatedAt:NOW,currentCompetence:status==='OPEN'?'2026-08':null,records:[{id:'2026-08',status,createdAt:NOW,updatedAt:NOW,origin:'MANUAL'}]}}
function adminRegistry(records:RcaRegistryRecord[]):AdminRegistryState{return{...emptyAdminRegistryState(NOW),rcas:records}}
function adminRca(overrides:Partial<RcaRegistryRecord>={}):RcaRegistryRecord{return{id:'RCA-REG-1',currentCode:'10',legacyCode:'9',name:'RCA Teste',coordinatorCode:'1',coordinatorName:'Supervisor',role:'PRINCIPAL',active:true,validFromCompetence:null,validToCompetence:null,origin:'MANUAL',sourceRow:null,note:null,createdAt:NOW,updatedAt:NOW,...overrides}}
function bussola(rows:Record<string,unknown>[],fileName='Bussola de Metas AGOSTO - 2026 DEFINITIVA.xlsx'){return parsed(BUSSOLA_SOURCE_ID,fileName,rows.map((item,index)=>rawRow(item,index+2)))}
const bussolaRow=(overrides:Record<string,unknown>={})=>({pasta_type:'MCD',industry_name:'COLGATE',target_rca_code:'9',target_rca_name:'RCA Teste',sales_target_pna:900,positivity_target:9,...overrides});
async function activeFor(target:TargetState|null,id='BUILD-A',stagingManifestHash='SOURCE-HASH'):Promise<ActiveCanonicalBundle>{const adminRegistryHash=await canonicalAdminRegistryHash(null),targetRegistryHash=await rcaTargetRegistryHash(target),canonicalInputHash=await canonicalInputHashV3(stagingManifestHash,adminRegistryHash,targetRegistryHash,EMPTY_SOURCE_REPLACEMENT_PROOF);return{status:'ACTIVE',motorBuildId:id,stagingManifestHash,adminRegistryHash,rcaTargetRegistryHash:targetRegistryHash,sourceContractVersion:'v2',sourceReplacementProofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,sourceReplacements:[],canonicalInputHash,schemaVersion:'v1',engineVersion:CANONICAL_ENGINE_VERSION,approvedAt:NOW,rowCounts:{M1_ITEM_ESTOQUE:0,M2_CLIENTE_RCA:0,M3_MOVIMENTO_VENDAS:0,M4_HISTORICO_TRANSICAO:0},factTypeCounts:{SALE:0,INBOUND_ORDER:0,RECEIPT:0,TARGET:0}}}

// GRUPO 1 — TARGET STORE
test('F4-01 — TargetState round-trip preserva zero, null e RCA',()=>{const storage=new InMemoryTargetStateStorage(),repo=new TargetStateRepository(storage),state=targetState({sellOutTarget:0,positivityTarget:null,networkTarget:0},[rcaTarget({salesTarget:0,positivityTarget:0})]);repo.replace(state);assert.deepEqual(repo.load(),state);assert.equal(repo.load()!.records[0].sellOutTarget,0);assert.equal(repo.load()!.records[0].positivityTarget,null)});
test('F4-02 — schema TargetState inválido é rejeitado integralmente',()=>assert.throws(()=>validateTargetState({...targetState(),schemaVersion:'v2'}),/TARGET_STATE_INVALID/));
test('F4-03 — competência TargetState exige YYYY-MM real',()=>assert.throws(()=>validateTargetState(targetState({competence:'2026-13'})),/TARGET_COMPETENCE_INVALID/));
test('F4-04 — competência duplicada é rejeitada',()=>{const state=targetState();state.records.push(structuredClone(state.records[0]));assert.throws(()=>validateTargetState(state),/TARGET_COMPETENCE_DUPLICATE/)});
test('F4-05 — identidade RCA inválida é rejeitada',()=>assert.throws(()=>validateTargetState(targetState({},[rcaTarget({rcaCanonicalId:'10'})])),/TARGET_RCA_IDENTITY_INVALID/));
test('F4-06 — repository restaura estado anterior quando a persistência falha',()=>{const storage=new InMemoryTargetStateStorage(targetState()),repo=new TargetStateRepository(storage);storage.failNextWrite();assert.throws(()=>repo.replace(withGeneralTargets(repo.load(),'2026-08',{sellOutTarget:6000,positivityTarget:60,networkTarget:3500},LATER)),/TARGET_STATE_TEST_WRITE_FAILED/);assert.equal(repo.load()!.records[0].sellOutTarget,5000)});
test('F4-07 — CLOSED é bloqueado também na camada transacional',()=>assert.throws(()=>assertTargetCompetenceOpen('2026-08',competence('CLOSED')),/TARGET_COMPETENCE_NOT_OPEN/));
test('F4-08 — race OPEN→CLOSED antes da persistência aborta sem gravar Target B',async()=>{let current=targetState(),active=await activeFor(current),mutated=false;const original=structuredClone(current);const deps:TargetTransactionDependencies={loadTarget:()=>structuredClone(current),replaceTarget:state=>{current=structuredClone(state!);return current},loadCompetence:()=>mutated?competence('CLOSED'):competence('OPEN'),build:async()=>active,targetHash:targetStateHash,rcaHash:rcaTargetRegistryHash,inputHash:canonicalInputHashV3,sync:async()=>({status:'NOT_PAIRED'}),engineVersion:CANONICAL_ENGINE_VERSION};const runtime:TargetUpdateRuntime={getActive:()=>active,activate:next=>{active=next},deactivate:()=>undefined};await assert.rejects(()=>executeTargetUpdateTransaction('2026-08',state=>{mutated=true;return withGeneralTargets(state,'2026-08',{sellOutTarget:6000,positivityTarget:60,networkTarget:3000},LATER)},runtime,{setPhase:()=>undefined},deps),/TARGET_COMPETENCE_NOT_OPEN/);assert.deepEqual(current,original)});

// GRUPO 2 — MIGRAÇÃO REPORT SETTINGS
test('F4-09 — bootstrap copia metas 08 e 09 exatamente sem vazamento',()=>{const repo=new TargetStateRepository(new InMemoryTargetStateStorage()),result=bootstrapTargetStateFromReportSettings(settings({sellOutTargetByCompetence:{'2026-08':5000,'2026-09':6000},positivityTargetByCompetence:{'2026-08':50,'2026-09':60},networkTargetByCompetence:{'2026-08':3000,'2026-09':4000}}),repo,NOW);assert.equal(result.status,'INITIALIZED');assert.deepEqual(result.state.records.map(r=>[r.competence,r.sellOutTarget,r.positivityTarget,r.networkTarget]),[['2026-08',5000,50,3000],['2026-09',6000,60,4000]]);assert.ok(result.state.records.every(r=>r.rcaTargets.length===0))});
test('F4-10 — bootstrap é idempotente e não sobrescreve TargetState administrativo',()=>{const repo=new TargetStateRepository(new InMemoryTargetStateStorage(targetState({sellOutTarget:7777}))),result=bootstrapTargetStateFromReportSettings(settings({sellOutTargetByCompetence:{'2026-08':1}}),repo,LATER);assert.equal(result.status,'PRESERVED');assert.equal(result.state.records[0].sellOutTarget,7777)});
test('F4-11 — legacy global não entra no bootstrap automático',()=>{const repo=new TargetStateRepository(new InMemoryTargetStateStorage()),result=bootstrapTargetStateFromReportSettings(settings({legacySellOutTarget:9999,legacyPositivityTarget:99}),repo,NOW);assert.equal(result.state.records.length,0)});
test('F4-12 — código de migração explícita limpa legado somente após TargetState persistido/releitura',()=>{const text=sourceText('../src/pages/admin/targetUpdateFlow.ts'),persistAt=text.indexOf('runCanonicalTargetMutation'),clearAt=text.indexOf("next.legacySellOutTarget = null");assert.ok(persistAt>=0&&clearAt>persistAt);assert.match(text,/loadReportSettings\(\);[\s\S]*legacySellOutTarget = null/)});

// GRUPO 3/4 — HASHES + CANONICAL INPUT
test('F4-13 — targetStateHash é determinístico sob reordenação',async()=>{const a=targetState({},[rcaTarget({id:'A'}),rcaTarget({id:'B',rcaCanonicalId:'RCA:20'})]),b=structuredClone(a);b.records[0].rcaTargets.reverse();assert.equal(await targetStateHash(a),await targetStateHash(b));assert.equal(await rcaTargetRegistryHash(a),await rcaTargetRegistryHash(b))});
test('F4-14 — timestamp e note não alteram hashes semânticos',async()=>{const a=targetState(),b=structuredClone(a);b.createdAt=LATER;b.updatedAt=LATER;b.records[0].createdAt=LATER;b.records[0].updatedAt=LATER;b.records[0].rcaTargets[0].createdAt=LATER;b.records[0].rcaTargets[0].updatedAt=LATER;b.records[0].rcaTargets[0].note='técnica';assert.equal(await targetStateHash(a),await targetStateHash(b));assert.equal(await rcaTargetRegistryHash(a),await rcaTargetRegistryHash(b))});
test('F4-15 — meta geral muda targetStateHash mas não rcaTargetRegistryHash',async()=>{const a=targetState(),b=withGeneralTargets(a,'2026-08',{sellOutTarget:6000,positivityTarget:50,networkTarget:3500},LATER);assert.notEqual(await targetStateHash(a),await targetStateHash(b));assert.equal(await rcaTargetRegistryHash(a),await rcaTargetRegistryHash(b))});
test('F4-16 — meta RCA muda ambos os hashes',async()=>{const a=targetState(),b=structuredClone(a);b.records[0].rcaTargets[0].salesTarget=2000;assert.notEqual(await targetStateHash(a),await targetStateHash(b));assert.notEqual(await rcaTargetRegistryHash(a),await rcaTargetRegistryHash(b))});
test('F4-17 — canonical input v19 continua determinístico e distinto do v20',async()=>{const v19=await canonicalInputHash('S','A'),v20=await canonicalInputHashV2('S','A','T');assert.equal(v19,await canonicalInputHash('S','A'));assert.notEqual(v19,v20)});
test('F4-18 — canonical input v20 usa source + admin + RCA target hash',async()=>{const base=await canonicalInputHashV2('S','A','T');assert.notEqual(base,await canonicalInputHashV2('S2','A','T'));assert.notEqual(base,await canonicalInputHashV2('S','A2','T'));assert.notEqual(base,await canonicalInputHashV2('S','A','T2'))});
test('F4-19 — meta geral não altera canonicalInputHash v2; meta RCA altera',async()=>{const a=targetState(),general=withGeneralTargets(a,'2026-08',{sellOutTarget:9999,positivityTarget:50,networkTarget:3000},LATER),rca=structuredClone(a);rca.records[0].rcaTargets[0].salesTarget=9999;const ha=await rcaTargetRegistryHash(a);assert.equal(await canonicalInputHashV2('S','A',ha),await canonicalInputHashV2('S','A',await rcaTargetRegistryHash(general)));assert.notEqual(await canonicalInputHashV2('S','A',ha),await canonicalInputHashV2('S','A',await rcaTargetRegistryHash(rca)))});
test('F4-20 — engine corrente é exatamente v21 e v20 permanece legado',()=>{assert.equal(CANONICAL_ENGINE_VERSION,V21_ENGINE);assert.notEqual(CANONICAL_ENGINE_VERSION,V20_ENGINE)});

// GRUPO 5 — TARGET AUTHORITY
test('F4-21 — MANUAL ativo vence SOURCE_SEED',()=>{const state=targetState({},[rcaTarget({id:'M',origin:'MANUAL',salesTarget:2000}),rcaTarget({id:'S',origin:'SOURCE_SEED',salesTarget:1000})]),r=resolveTargetAuthority(state,'2026-08','RCA:10');assert.equal(r.authority,'MANUAL');assert.equal(r.record?.salesTarget,2000)});
test('F4-22 — SOURCE_SEED é usado quando não há MANUAL',()=>{const r=resolveTargetAuthority(targetState({},[rcaTarget({origin:'SOURCE_SEED'})]),'2026-08','RCA:10');assert.equal(r.authority,'SOURCE_SEED');assert.equal(r.record?.salesTarget,1000)});
test('F4-23 — MANUAL inactive é tombstone',()=>{const r=resolveTargetAuthority(targetState({},[rcaTarget({active:false}),rcaTarget({id:'S',origin:'SOURCE_SEED'})]),'2026-08','RCA:10');assert.equal(r.tombstone,true);assert.equal(r.record,null)});
test('F4-24 — MANUAL divergente fica AMBIGUOUS sem vencedor',()=>{const r=resolveTargetAuthority(targetState({},[rcaTarget({id:'M1',salesTarget:1000}),rcaTarget({id:'M2',salesTarget:2000})]),'2026-08','RCA:10');assert.equal(r.ambiguous,true);assert.equal(r.record,null)});
test('F4-25 — SOURCE_SEED divergente fica AMBIGUOUS sem vencedor',()=>{const r=resolveTargetAuthority(targetState({},[rcaTarget({id:'S1',origin:'SOURCE_SEED',salesTarget:1000}),rcaTarget({id:'S2',origin:'SOURCE_SEED',salesTarget:2000})]),'2026-08','RCA:10');assert.equal(r.ambiguous,true);assert.equal(r.record,null)});
test('F4-26 — agosto não interfere na autoridade de setembro',()=>{const r=resolveTargetAuthority(targetState(),'2026-09','RCA:10');assert.equal(r.authority,'NONE');assert.equal(r.record,null)});
test('F4-27 — Bússola física permanece fallback sem Target Registry',()=>{const result=materializeEffectiveTargetFacts([bussola([bussolaRow()])],null,adminRegistry([adminRca()]));assert.equal(result.facts.length,1);assert.equal(result.facts[0].source,'BUSSOLA');assert.equal(result.facts[0].sales_target,900)});
test('F4-28 — Registry MANUAL substitui Bússola e registra lineage próprio',()=>{const result=materializeEffectiveTargetFacts([bussola([bussolaRow()])],targetState(),adminRegistry([adminRca()]));assert.equal(result.facts.length,1);assert.equal(result.facts[0].source,'ADMIN_TARGET_REGISTRY');assert.equal(result.facts[0].source_lineage,'AdminTargetRegistry:MANUAL');assert.equal(result.facts[0].sales_target,1000)});

// GRUPO 6 — SEED BÚSSOLA
test('F4-29 — preview seed usa staging injetado, filtro MCD+COLGATE e RCA resolver oficial',async()=>{let loads=0;const stage=bussola([bussolaRow(),bussolaRow({pasta_type:'OUTRO',target_rca_code:'8'}),bussolaRow({industry_name:'OUTRA',target_rca_code:'7'})]);const preview=await previewBussolaTargetSeed('2026-08',null,{loadBussola:async()=>{loads+=1;return{parsed:stage}},loadRegistry:async()=>adminRegistry([adminRca()])});assert.equal(loads,1);assert.equal(preview.counts.new,1);assert.equal(preview.source,BUSSOLA_SOURCE_ID)});
test('F4-30 — seed cross-month 08→09 fica bloqueado',async()=>{const preview=await previewBussolaTargetSeed('2026-09',null,{loadBussola:async()=>({parsed:bussola([bussolaRow()])}),loadRegistry:async()=>adminRegistry([adminRca()])});assert.equal(preview.counts.competenceMismatch,1);assert.throws(()=>applyBussolaTargetSeedPreview(null,preview),/TARGET_SEED_COMPETENCE_MISMATCH/)});
test('F4-31 — RCA unresolved aparece no preview e não aplica',async()=>{const preview=await previewBussolaTargetSeed('2026-08',null,{loadBussola:async()=>({parsed:bussola([bussolaRow()])}),loadRegistry:async()=>emptyAdminRegistryState(NOW)});assert.equal(preview.counts.rcaUnresolved,1);assert.equal(applyBussolaTargetSeedPreview(null,preview,NOW).records[0].rcaTargets.length,0)});
test('F4-32 — MANUAL é protegido contra reseed',async()=>{const preview=await previewBussolaTargetSeed('2026-08',targetState(),{loadBussola:async()=>({parsed:bussola([bussolaRow({sales_target_pna:9999})])}),loadRegistry:async()=>adminRegistry([adminRca()])});assert.equal(preview.counts.manualProtected,1);assert.equal(applyBussolaTargetSeedPreview(targetState(),preview,LATER).records[0].rcaTargets[0].salesTarget,1000)});
test('F4-33 — SOURCE_SEED seguro pode ser atualizado pelo reseed',async()=>{const current=targetState({},[rcaTarget({origin:'SOURCE_SEED',salesTarget:100})]),preview=await previewBussolaTargetSeed('2026-08',current,{loadBussola:async()=>({parsed:bussola([bussolaRow({sales_target_pna:900})])}),loadRegistry:async()=>adminRegistry([adminRca()])});assert.equal(preview.counts.updatable,1);assert.equal(applyBussolaTargetSeedPreview(current,preview,LATER).records[0].rcaTargets[0].salesTarget,900)});
test('F4-34 — SOURCE_SEED ausente da Bússola atual não é apagado',async()=>{const current=targetState({},[rcaTarget({origin:'SOURCE_SEED'})]),preview=await previewBussolaTargetSeed('2026-08',current,{loadBussola:async()=>({parsed:bussola([])}),loadRegistry:async()=>adminRegistry([adminRca()])});assert.equal(preview.counts.missingFromSource,1);assert.equal(applyBussolaTargetSeedPreview(current,preview,LATER).records[0].rcaTargets.length,1)});
test('F4-35 — seed oficial não chama parser, File ou upload',()=>{const text=sourceText('../src/canonical/targetSeed.ts');assert.match(text,/loadSourceStaging\(BUSSOLA_SOURCE_ID\)/);assert.doesNotMatch(text,/parseSource|new File|processSourceUpdates|upload/i)});

// GRUPO 7 — M3 TARGET
test('F4-36 — applyTargetAuthorityToM3 preserva SALE/INBOUND/RECEIPT e substitui somente TARGET',()=>{const original=canonicalList('M3_MOVIMENTO_VENDAS',[{fact_type:'SALE',marker:'S'},{fact_type:'INBOUND_ORDER',marker:'I'},{fact_type:'RECEIPT',marker:'R'},{fact_type:'TARGET',marker:'OLD'}]),nonTargets=structuredClone(original.records.slice(0,3)),next=applyTargetAuthorityToM3(original,[bussola([bussolaRow()])],targetState(),adminRegistry([adminRca()]));assert.deepEqual(next.records.slice(0,3),nonTargets);assert.equal(next.records.length,4);assert.equal(next.records[3].source,'ADMIN_TARGET_REGISTRY')});
test('F4-37 — SOURCE_SEED materializa TARGET com lineage explícito',()=>{const fact=materializeEffectiveTargetFacts([],targetState({},[rcaTarget({origin:'SOURCE_SEED'})]),null).facts[0];assert.equal(fact.source,'ADMIN_TARGET_REGISTRY');assert.equal(fact.source_lineage,'AdminTargetRegistry:SOURCE_SEED');assert.equal(fact.competence,'2026-08')});
test('F4-38 — tombstone impede reentrada da Bússola no M3',()=>assert.equal(materializeEffectiveTargetFacts([bussola([bussolaRow()])],targetState({},[rcaTarget({active:false})]),adminRegistry([adminRca()])).facts.length,0));
test('F4-39 — ambiguidade superior gera audit e zero fallback Bússola',()=>{const result=materializeEffectiveTargetFacts([bussola([bussolaRow()])],targetState({},[rcaTarget({id:'A'}),rcaTarget({id:'B',salesTarget:2000})]),adminRegistry([adminRca()]));assert.equal(result.facts.length,0);assert.ok(result.audits.some(a=>a.code==='AMBIGUOUS_TARGET'))});

function sellOutLists(salesTarget:number,positivityTarget:number){const m1=canonicalList('M1_ITEM_ESTOQUE',[{item_canonical_id:'ITEM:1',winthor_code:'1',category_master:'ORAL CARE',physical_stock_units:0}]),m2=canonicalList('M2_CLIENTE_RCA',[{cnpj:'12345678000199',rca_canonical_id:'RCA:10',rca_name:'RCA Teste',rca_current_code:'10',coordinator_name:'Supervisor'}]),m3=canonicalList('M3_MOVIMENTO_VENDAS',[{fact_type:'SALE',competence:'2026-08',event_date:'2026-08-10',cnpj:'12345678000199',rca_canonical_id:'RCA:10',transaction_rca_code:'10',winthor_product_code:'1',order_status:'FATURADO',value:100},{fact_type:'SALE',competence:'2026-08',event_date:'2026-08-11',cnpj:'12345678000199',rca_canonical_id:'RCA:10',transaction_rca_code:'10',winthor_product_code:'1',order_status:'A FATURAR',value:50},{fact_type:'TARGET',competence:'2026-08',rca_canonical_id:'RCA:10',transaction_rca_code:'10',sales_target:salesTarget,positivity_target:positivityTarget}]);return{m1,m2,m3}}
test('F4-40 — alterar apenas meta RCA não muda realizado/faturado/a faturar/positividade',()=>{const a=buildSellOutViewModel(sellOutLists(1000,10)),b=buildSellOutViewModel(sellOutLists(2000,20));assert.deepEqual([a.totals.realized,a.totals.invoiced,a.totals.toInvoice,a.totals.positiveCustomers],[b.totals.realized,b.totals.invoiced,b.totals.toInvoice,b.totals.positiveCustomers]);assert.notEqual(a.vendorRows[0].achievement,b.vendorRows[0].achievement);assert.notEqual(a.vendorRows[0].positivityAchievement,b.vendorRows[0].positivityAchievement)});
test('F4-41 — Gerencial reflete salesTarget e positivityTarget efetivos do M3',()=>{const model=buildSellOutViewModel(sellOutLists(2345,23));assert.equal(model.vendorRows[0].salesTarget,2345);assert.equal(model.vendorRows[0].positivityTarget,23)});
test('F4-42 — cinco linhas comerciais permanecem invariantes quando só a meta muda',()=>assert.deepEqual(buildSellOutViewModel(sellOutLists(1000,10)).salesByLine,buildSellOutViewModel(sellOutLists(9999,99)).salesByLine));

function networkModel(targetAmount:number,networkTarget=3000,sellOutTarget=5000){const m2=canonicalList('M2_CLIENTE_RCA',[{cnpj:'12345678000199',customer_name:'Loja',top_network:'Rede A',manager_cnpj:'12345678000199',top_group_code:'G1',top_target:2000,top_route_competence:'2026-08',rca_canonical_id:'RCA:10'}]),m3=canonicalList('M3_MOVIMENTO_VENDAS',[{fact_type:'SALE',competence:'2026-08',event_date:'2026-08-10',cnpj:'12345678000199',order_status:'FATURADO',value:500},{fact_type:'TARGET',competence:'2026-08',rca_canonical_id:'RCA:10',sales_target:targetAmount,positivity_target:10}]);return buildTopRetailNetworksViewModel({m2,m3,sellOutTarget,networkTargetTotal:networkTarget,generatedAt:NOW})}
test('F4-43 — Meta Indústria continua SUM(M3 TARGET.sales_target)',()=>assert.equal(networkModel(12345).totals.industryTarget,12345));
test('F4-44 — alterar Target RCA altera Meta Indústria sem alterar Top Target',()=>{const a=networkModel(1000),b=networkModel(2000);assert.notEqual(a.totals.industryTarget,b.totals.industryTarget);assert.equal(a.totals.topTarget,b.totals.topTarget)});
test('F4-45 — Meta Redes Geral permanece parâmetro separado de Meta Indústria e Top',()=>{const model=networkModel(1000,7777,5000);assert.equal(model.totals.networkTarget,7777);assert.equal(model.totals.industryTarget,1000);assert.equal(model.totals.topTarget,2000)});
test('F4-46 — representatividade homologada preserva referência Top × T&C ÷ Meta Indústria',()=>{const model=networkModel(1000,3000,5000);assert.equal(model.rows[0].tcReferenceTarget,10000);assert.equal(model.rows[0].targetWeight,1);assert.equal(model.rows[0].networkTarget,3000)});

// TARGET UPDATE LIFECYCLE
test('F4-47 — meta geral persiste e sincroniza sem rebuild quando RCA hash não muda',async()=>{let current=targetState(),active=await activeFor(current),builds=0,syncs=0;const phases:string[]=[];const deps:TargetTransactionDependencies={loadTarget:()=>structuredClone(current),replaceTarget:state=>{current=structuredClone(state!);return current},loadCompetence:()=>competence('OPEN'),build:async()=>{builds+=1;return active},targetHash:targetStateHash,rcaHash:rcaTargetRegistryHash,inputHash:canonicalInputHashV3,sync:async()=>{syncs+=1;return{status:'NOT_PAIRED'}},engineVersion:CANONICAL_ENGINE_VERSION};const runtime:TargetUpdateRuntime={getActive:()=>active,activate:next=>{active=next},deactivate:()=>undefined};const result=await executeTargetUpdateTransaction('2026-08',state=>withGeneralTargets(state,'2026-08',{sellOutTarget:6000,positivityTarget:50,networkTarget:3000},LATER),runtime,{setPhase:phase=>phases.push(phase)},deps);assert.equal(result.phase,'SUCCESS');assert.equal(builds,0);assert.equal(syncs,1);assert.deepEqual(phases,['MUTATING','SYNCING'])});
test('F4-48 — meta RCA executa MUTATING→BUILDING→ACTIVATING→SYNCING',async()=>{let current=targetState(),active=await activeFor(current);const phases:string[]=[];const deps:TargetTransactionDependencies={loadTarget:()=>structuredClone(current),replaceTarget:state=>{current=structuredClone(state!);return current},loadCompetence:()=>competence('OPEN'),build:async target=>activeFor(target,'BUILD-B'),targetHash:targetStateHash,rcaHash:rcaTargetRegistryHash,inputHash:canonicalInputHashV3,sync:async()=>({status:'NOT_PAIRED'}),engineVersion:CANONICAL_ENGINE_VERSION};const runtime:TargetUpdateRuntime={getActive:()=>active,activate:next=>{active=next},deactivate:()=>undefined};const result=await executeTargetUpdateTransaction('2026-08',state=>withManualRcaTarget(state,{competence:'2026-08',rcaCanonicalId:'RCA:10',sourceRcaCode:'9',salesTarget:2000,positivityTarget:20},'TARGET-1',LATER),runtime,{setPhase:phase=>phases.push(phase)},deps);assert.equal(result.phase,'SUCCESS');assert.equal(active.motorBuildId,'BUILD-B');assert.deepEqual(phases,['MUTATING','BUILDING','ACTIVATING','SYNCING'])});
test('F4-49 — falha de build restaura Target A + Build A',async()=>{let current=targetState(),active=await activeFor(current,'BUILD-A');const original=structuredClone(current);const deps:TargetTransactionDependencies={loadTarget:()=>structuredClone(current),replaceTarget:state=>{current=structuredClone(state!);return current},loadCompetence:()=>competence('OPEN'),build:async()=>{throw new Error('BUILD_FAIL')},targetHash:targetStateHash,rcaHash:rcaTargetRegistryHash,inputHash:canonicalInputHashV3,sync:async()=>({status:'NOT_PAIRED'}),engineVersion:CANONICAL_ENGINE_VERSION};const runtime:TargetUpdateRuntime={getActive:()=>active,activate:next=>{active=next},deactivate:()=>undefined};await assert.rejects(()=>executeTargetUpdateTransaction('2026-08',state=>withManualRcaTarget(state,{competence:'2026-08',rcaCanonicalId:'RCA:10',salesTarget:2000,positivityTarget:20},'TARGET-1',LATER),runtime,{setPhase:()=>undefined},deps),/BUILD_FAIL/);assert.deepEqual(current,original);assert.equal(active.motorBuildId,'BUILD-A')});
test('F4-50 — falha de sync após activate preserva Target B + Build B',async()=>{let current=targetState(),active=await activeFor(current,'BUILD-A');const deps:TargetTransactionDependencies={loadTarget:()=>structuredClone(current),replaceTarget:state=>{current=structuredClone(state!);return current},loadCompetence:()=>competence('OPEN'),build:async target=>activeFor(target,'BUILD-B'),targetHash:targetStateHash,rcaHash:rcaTargetRegistryHash,inputHash:canonicalInputHashV3,sync:async()=>{throw new Error('SYNC_FAIL')},engineVersion:CANONICAL_ENGINE_VERSION};const runtime:TargetUpdateRuntime={getActive:()=>active,activate:next=>{active=next},deactivate:()=>undefined};const result=await executeTargetUpdateTransaction('2026-08',state=>withManualRcaTarget(state,{competence:'2026-08',rcaCanonicalId:'RCA:10',salesTarget:2000,positivityTarget:20},'TARGET-1',LATER),runtime,{setPhase:()=>undefined},deps);assert.equal(result.phase,'LOCAL_SUCCESS_SYNC_FAILED');assert.equal(active.motorBuildId,'BUILD-B');assert.equal(current.records[0].rcaTargets[0].salesTarget,2000)});
test('F4-51 — lifecycle Target Update sobrevive unsubscribe/remount',async()=>{const coordinator=createTargetUpdateCoordinator();let release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve});let observed=coordinator.getState();const off=coordinator.subscribe(state=>{observed=state}),run=coordinator.run(async controls=>{controls.setPhase('BUILDING');await pending;return{phase:'SUCCESS',status:'ok',error:''}});await Promise.resolve();assert.equal(observed.phase,'BUILDING');off();let remount=coordinator.getState();const off2=coordinator.subscribe(state=>{remount=state});assert.equal(remount.busy,true);release();await run;assert.equal(remount.phase,'SUCCESS');off2()});

test('F4-52 — TARGET_UPDATE bloqueia todos os owners de dados e não cria fila',async()=>{const coordinator=createSystemDataOperationCoordinator();let release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve}),run=coordinator.run('TARGET_UPDATE',async()=>pending);await Promise.resolve();for(const owner of ['BASE_UPDATE','REGISTRY_UPDATE','SYNC_SEND','SYNC_RESTORE','SYNC_CREATE_AND_SEND','SYNC_PAIR_AND_RESTORE','BUNDLE_RECOVERY','STARTUP_REMOTE_RESTORE','ENGINE_MIGRATION','SOURCE_REPLACEMENT_UPDATE'] as const)assert.deepEqual(await coordinator.run(owner,async()=>undefined),{status:'BUSY',owner:'TARGET_UPDATE'});release();await run;assert.deepEqual(coordinator.getState(),{busy:false,owner:null})});
test('F4-53 — operação inversa bloqueia TARGET_UPDATE e gate libera mesmo após erro',async()=>{const coordinator=createSystemDataOperationCoordinator();let release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve}),base=coordinator.run('BASE_UPDATE',async()=>pending);await Promise.resolve();assert.deepEqual(await coordinator.run('TARGET_UPDATE',async()=>undefined),{status:'BUSY',owner:'BASE_UPDATE'});release();await base;try{await coordinator.run('TARGET_UPDATE',async()=>{throw new Error('X')})}catch{}assert.deepEqual(coordinator.getState(),{busy:false,owner:null})});

test('F4-54 — Base Update v21 injeta AdminRegistry + TargetState + ReplacementState e proíbe incremental por target/proof diferente',()=>{const text=sourceText('../src/canonical/sourceImport.ts');assert.match(text,/loadAdminRegistryState\(\)/);assert.match(text,/loadTargetState\(\)/);assert.match(text,/loadSourceReplacementState\(\)/);assert.match(text,/base\.active\.rcaTargetRegistryHash !== targetHash/);assert.match(text,/base\.active\.sourceReplacementProofHash !== proofHash/);assert.match(text,/buildCanonicalFromStoredSources\(/)});
test('F4-55 — v21 staging identity usa manifest v2 PRESENT\/REPLACED e o contrato legado 19\/19 segue suportado',()=>{const text=sourceText('../src/canonical/sourceReplacementIdentity.ts');assert.match(text,/blue-jacket-staging-manifest\/v2/);assert.match(text,/'PRESENT'/);assert.match(text,/'REPLACED'/);assert.equal(REQUIRED_SOURCE_IDS.length,19);assert.ok(REQUIRED_SOURCE_IDS.includes(BUSSOLA_SOURCE_ID))});
test('F4-56 — DataContext trata v20 e anteriores como legado e rebuilda v21 sem auto-seed da Bússola',()=>{const text=sourceText('../src/store/DataContext.tsx');assert.match(text,/legacyToMigrate/);assert.match(text,/rebuildForCanonicalEngine/);assert.match(text,/CANONICAL_ENGINE_VERSION/);assert.match(text,/bootstrapTargetStateFromReportSettings/);assert.doesNotMatch(text,/applyBussolaTargetSeedPreview|previewBussolaTargetSeed/)});

// CLOUD
const identity:DeviceSyncIdentity={workspaceId:'11111111-1111-4111-8111-111111111111',secret:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'};
const sourceSnapshot=sourceStorageV1Fixture();
async function cloudActiveFor(target:TargetState|null,id='CLOUD'){return activeFor(target,id,await stagingManifestHashV2(sourceSnapshot.staging,[]))}
test('F4-57 — snapshot novo transporta TargetState e encrypt/decrypt o preserva',async()=>{const state=targetState(),active=await cloudActiveFor(state),snapshot=cloudSyncTestHelpers.buildCloudSnapshot(active,sourceSnapshot,settings(),competence('OPEN'),NOW,null,state);assert.deepEqual(snapshot.targetState,state);assert.deepEqual((await cloudSyncTestHelpers.decrypt(identity,await cloudSyncTestHelpers.encrypt(identity,snapshot))).targetState,state)});
test('F4-58 — snapshot legado sem targetState continua válido e preserva TargetState local existente',async()=>{const local=targetState({sellOutTarget:7777}),active=await cloudActiveFor(local);let current=structuredClone(local),replacement:unknown=null;const snapshot:CloudRestoreDependencies={exportSources:async()=>sourceSnapshot,loadSettings:()=>settings(),loadCompetence:()=>competence('OPEN'),loadAdminRegistry:async()=>null,loadTargetState:()=>current,loadSourceReplacementState:()=>replacement as null,restoreSources:async()=>undefined,restoreSettings:value=>value as ReportSettings,replaceCompetence:value=>value as CompetenceState,replaceAdminRegistry:async value=>value,replaceTargetState:value=>{current=structuredClone(value!);return current},replaceSourceReplacementState:value=>{replacement=value;return value},bootstrapTargetState:()=>{throw new Error('BOOTSTRAP_NOT_EXPECTED')},build:async()=>active};await cloudSyncTestHelpers.applyCloudSnapshot({format:'blue-jacket-device-sync/v1',createdAt:NOW,active:null,sources:sourceSnapshot,settings:settings(),competenceState:competence('OPEN')},snapshot);assert.equal(current.records[0].sellOutTarget,7777)});
test('F4-59 — aparelho novo com snapshot legado bootstrapa somente metas competência-específicas',async()=>{const legacySettings=settings({sellOutTargetByCompetence:{'2026-08':5000},positivityTargetByCompetence:{'2026-08':50},networkTargetByCompetence:{'2026-08':3000},legacySellOutTarget:9999});let current:TargetState|null=null,replacement:unknown=null;const deps:CloudRestoreDependencies={exportSources:async()=>sourceSnapshot,loadSettings:()=>settings(),loadCompetence:()=>competence('OPEN'),loadAdminRegistry:async()=>null,loadTargetState:()=>current,loadSourceReplacementState:()=>replacement as null,restoreSources:async()=>undefined,restoreSettings:()=>legacySettings,replaceCompetence:value=>value as CompetenceState,replaceAdminRegistry:async value=>value,replaceTargetState:value=>{current=value;return current},replaceSourceReplacementState:value=>{replacement=value;return value},bootstrapTargetState:restored=>{const repo=new TargetStateRepository(new InMemoryTargetStateStorage());current=bootstrapTargetStateFromReportSettings(restored,repo,NOW).state;return current},build:async()=>cloudActiveFor(current)};await cloudSyncTestHelpers.applyCloudSnapshot({format:'blue-jacket-device-sync/v1',createdAt:NOW,active:null,sources:sourceSnapshot,settings:legacySettings},deps);assert.equal(current!.records[0].sellOutTarget,5000);assert.equal(current!.records[0].rcaTargets.length,0)});
test('F4-60 — TargetState remoto vence restore novo e identidade reconstruída deve coincidir',async()=>{const remote=targetState({sellOutTarget:8888}),active=await cloudActiveFor(remote);let current:TargetState|null=null,replacement:unknown=null;const deps:CloudRestoreDependencies={exportSources:async()=>sourceSnapshot,loadSettings:()=>settings(),loadCompetence:()=>competence('OPEN'),loadAdminRegistry:async()=>null,loadTargetState:()=>current,loadSourceReplacementState:()=>replacement as null,restoreSources:async()=>undefined,restoreSettings:()=>settings(),replaceCompetence:value=>value as CompetenceState,replaceAdminRegistry:async value=>value,replaceTargetState:value=>{current=structuredClone(value!);return current},replaceSourceReplacementState:value=>{replacement=value;return value},build:async()=>active};const rebuilt=await cloudSyncTestHelpers.applyCloudSnapshot(cloudSyncTestHelpers.buildCloudSnapshot(active,sourceSnapshot,settings(),competence('OPEN'),NOW,null,remote),deps);assert.equal(current!.records[0].sellOutTarget,8888);assert.equal(rebuilt.rcaTargetRegistryHash,active.rcaTargetRegistryHash)});
test('F4-61 — RCA target divergente durante captura aborta com PUT 0; sucesso faz 1 PUT',async()=>{const stateA=targetState(),stateB=structuredClone(stateA);stateB.records[0].rcaTargets[0].salesTarget=2000;const active=await cloudActiveFor(stateA);let puts=0;const deps=(state:TargetState):CloudUploadDependencies=>({getActive:()=>active,exportSources:async()=>sourceSnapshot,sourceManifestHash:(snapshot,replaced=[])=>stagingManifestHashV2(snapshot.staging,replaced),registryHash:canonicalAdminRegistryHash,targetHash:rcaTargetRegistryHash,replacementProofHash:async()=>({proofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,replacements:[],replacedSourceIds:[]}),inputHash:canonicalInputHashV3,loadSettings:()=>settings(),loadCompetence:()=>competence('OPEN'),loadAdminRegistry:async()=>null,loadTargetState:()=>state,loadSourceReplacementState:()=>null,encryptSnapshot:async()=>new Uint8Array([1]),uploadPayload:async()=>{puts+=1;return{updatedAt:NOW,bytes:1}},saveState:()=>undefined,now:()=>NOW});await assert.rejects(()=>cloudSyncTestHelpers.uploadCurrentDeviceSnapshotWithDependencies(identity,deps(stateB)),/SYNC_SNAPSHOT_CHANGED_DURING_CAPTURE/);assert.equal(puts,0);await cloudSyncTestHelpers.uploadCurrentDeviceSnapshotWithDependencies(identity,deps(stateA));assert.equal(puts,1)});
test('F4-62 — Cloud mantém protocolo v1, AES-GCM, BJ1 e backend Supabase inalterados',()=>{const text=sourceText('../src/canonical/cloudSync.ts');assert.match(text,/blue-jacket-device-sync\/v1/);assert.match(text,/AES-GCM/);assert.match(text,/BJ1\./);assert.match(text,/wsdmcnvnpjpberzeizjc\.supabase\.co\/functions\/v1\/blue-jacket-sync/)});

// BUNDLE
test('F4-63 — Bundle v21 exige proof/replacements; v20 conserva identidade v2 legacy',()=>{const text=sourceText('../src/canonical/bundleStore.ts');assert.match(text,/sourceReplacementProofHash/);assert.match(text,/sourceReplacements/);assert.match(text,/V20_IDENTITY_REQUIRED/);assert.match(text,/V21_IDENTITY_REQUIRED/)});
test('F4-64 — recovery v21 compara target e replacement identities locais e mismatch força rebuild',()=>{const text=sourceText('../src/canonical/bundleRecovery.ts');assert.match(text,/localRcaTargetRegistryHash/);assert.match(text,/localSourceReplacementProofHash/);assert.match(text,/proofMatches/);assert.match(text,/rebuildFromStaging/)});
test('F4-65 — v19 e v20 são legacy para rebuild, não reinterpretados como v21',()=>{const store=sourceText('../src/canonical/bundleStore.ts'),recovery=sourceText('../src/canonical/bundleRecovery.ts');assert.match(store,/V19_ENGINE/);assert.match(store,/V20_ENGINE/);assert.match(recovery,/V19_ENGINE/);assert.match(recovery,/V20_ENGINE/)});
test('F4-66 — TargetState completo não faz parte do ZIP técnico',()=>{const text=sourceText('../src/canonical/bundleStore.ts');assert.doesNotMatch(text,/loadTargetState|replaceTargetState|TargetState/);assert.match(text,/M1_ITEM_ESTOQUE/);assert.match(text,/M4_HISTORICO_TRANSICAO/)});
test('F4-67 — collision hardening inclui target hash e replacement proof na identidade completa',()=>{const text=sourceText('../src/canonical/bundleStore.ts'),identity=text.match(/function manifestIdentityMatchesActive[\s\S]*?\n}/)?.[0]??'';assert.match(identity,/rcaTargetRegistryHash/);assert.match(identity,/sourceReplacementProofHash/);assert.match(identity,/sourceReplacements/);assert.match(identity,/motorBuildId/)});

// EXPORTS
test('F4-68 — canonical JSON e Excel incluem rcaTargetRegistryHash',()=>{const m3=canonicalList('M3_MOVIMENTO_VENDAS',[]),provenance={motorBuildId:'B',stagingManifestHash:'S',adminRegistryHash:'A',rcaTargetRegistryHash:'T',sourceContractVersion:'v2',sourceReplacementProofHash:EMPTY_SOURCE_REPLACEMENT_PROOF,sourceReplacements:[],canonicalInputHash:'I',schemaVersion:'v1',engineVersion:CANONICAL_ENGINE_VERSION};assert.equal(exportPayload(m3,provenance).rcaTargetRegistryHash,'T');const metadata=XLSX.utils.sheet_to_json(createExcelWorkbook(m3,provenance).Sheets.METADATA,{header:1}) as unknown[][];assert.ok(metadata.some(row=>row[0]==='rcaTargetRegistryHash'&&row[1]==='T'))});
test('F4-69 — Sell Out JSON/Excel metadata recebem targetStateHash sem TargetState completo',()=>{const view={...buildSellOutViewModel(sellOutLists(1000,10)),targetStateHash:'TARGET-FULL-HASH'};assert.equal(sellOutExportPayload(view).targetStateHash,'TARGET-FULL-HASH');const metadata=XLSX.utils.sheet_to_json(createSellOutWorkbook(view).Sheets.METADATA,{header:1}) as unknown[][];assert.ok(metadata.some(row=>row[0]==='targetStateHash'&&row[1]==='TARGET-FULL-HASH'));assert.doesNotMatch(JSON.stringify(sellOutExportPayload(view)),/blue-jacket-target-state\/v1/)});
test('F4-70 — Redes JSON/Excel metadata recebem targetStateHash',()=>{const view={...networkModel(1000),targetStateHash:'TARGET-FULL-HASH'};assert.equal(topNetworksExportPayload(view).targetStateHash,'TARGET-FULL-HASH');const metadata=XLSX.utils.sheet_to_json(createTopNetworksWorkbook(view).Sheets.METADATA,{header:1}) as unknown[][];assert.ok(metadata.some(row=>row[0]==='targetStateHash'&&row[1]==='TARGET-FULL-HASH'))});
test('F4-71 — exports oficiais calculam targetStateHash no instante da exportação com generic forte',()=>{const text=sourceText('../src/canonical/operationalExporters.ts');assert.match(text,/async function withCurrentTargetHash<T>\(view: T\): Promise<T & \{ targetStateHash: string \}>/);assert.match(text,/targetStateHash\(loadTargetState\(\)\)/);assert.doesNotMatch(text,/as any|unknown as SellOutViewModel|@ts-ignore|@ts-expect-error/)});

test('F4-72 — MetasPage é o único editor oficial e contém Metas Gerais + Metas RCA',()=>{const metas=sourceText('../src/pages/MetasPage.tsx'),redes=sourceText('../src/pages/TopRetailNetworksPage.tsx');assert.match(metas,/METAS GERAIS/);assert.match(metas,/METAS POR RCA/);assert.match(metas,/canonicalTargetActions/);assert.doesNotMatch(redes,/setNetworkTargetFor|saveGeneral|upsertRca/)});
test('F4-73 — UI CLOSED é read-only e seed só parte de ação explícita',()=>{const metas=sourceText('../src/pages/MetasPage.tsx');assert.match(metas,/selectedRecord\.status === 'OPEN'/);assert.match(metas,/previewSeed/);assert.match(metas,/applySeed/);assert.doesNotMatch(metas,/useEffect\([\s\S]{0,300}applySeed/)});
test('F4-74 — motores/authority de targets não leem localStorage nem currentCompetence; TargetState é injetado',()=>{const authority=sourceText('../src/canonical/targetAuthority.ts'),sourceImport=sourceText('../src/canonical/sourceImport.ts');assert.doesNotMatch(authority,/localStorage|loadCompetenceState|currentCompetence/);assert.match(sourceImport,/targetState/);assert.match(sourceImport,/applyTargetAuthorityToM3/)});
test('F4-75 — 19 formatos permanecem suportados com Bússola, NOVOS RCAS, lançamentos e Roteiro Top',()=>{assert.equal(REQUIRED_SOURCE_IDS.length,19);for(const source of [BUSSOLA_SOURCE_ID,'NOVOS RCAS.xlsx','lançamentos.xlsx',"08.26 Roteiro Ativo Top Varejistas Ago'26 - Final.xlsx"])assert.ok(REQUIRED_SOURCE_IDS.includes(source))});
