import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { strToU8, zipSync } from 'fflate';
import { recoverTechnicalBundle } from '../src/canonical/bundleRecovery.ts';
import { CANONICAL_ENGINE_VERSION } from '../src/canonical/sourceImport.ts';
import { canonicalInputHashV3 } from '../src/canonical/sourceReplacementIdentity.ts';
import { EMPTY_SOURCE_REPLACEMENT_PROOF } from '../src/canonical/sourceReplacementState.ts';
import { activateCanonicalBundleReference, resolveActiveCanonicalBundle, type ActiveCanonicalBundle } from '../src/canonical/runtime.ts';
import { inspectCanonicalBundle, persistCanonicalBundle, type BundleImportResult, type CanonicalBundleRepository, type PreparedCanonicalBundle, type StoredCanonicalBundle } from '../src/canonical/bundleStore.ts';
import { loadCandidateList } from '../src/canonical/candidateLists.ts';
import { activeV19Fixture, activeV20Fixture, activeV21Fixture, V20_ENGINE, V21_ENGINE } from './phase5b-fixtures.ts';

class MemoryStorage { private data=new Map<string,string>(); get length(){return this.data.size} clear(){this.data.clear()} getItem(key:string){return this.data.get(key)??null} key(index:number){return [...this.data.keys()][index]??null} removeItem(key:string){this.data.delete(key)} setItem(key:string,value:string){this.data.set(key,value)} }
const ids=['M1_ITEM_ESTOQUE','M2_CLIENTE_RCA','M3_MOVIMENTO_VENDAS','M4_HISTORICO_TRANSICAO'] as const;
const REGISTRY_HASH_A='registry-hash-A',REGISTRY_HASH_B='registry-hash-B',TARGET_HASH_A='target-hash-A',TARGET_HASH_B='target-hash-B',PROOF_A=EMPTY_SOURCE_REPLACEMENT_PROOF,PROOF_B='proof-B';
const imported=(bundle:ActiveCanonicalBundle):BundleImportResult=>({motorBuildId:bundle.motorBuildId,stagingManifestHash:bundle.stagingManifestHash,...(bundle.adminRegistryHash?{adminRegistryHash:bundle.adminRegistryHash}:{}),...(bundle.rcaTargetRegistryHash?{rcaTargetRegistryHash:bundle.rcaTargetRegistryHash}:{}),...(bundle.sourceContractVersion?{sourceContractVersion:bundle.sourceContractVersion}:{}),...(bundle.sourceReplacementProofHash?{sourceReplacementProofHash:bundle.sourceReplacementProofHash}:{}),...(bundle.sourceReplacements?{sourceReplacements:bundle.sourceReplacements}:{}),...(bundle.canonicalInputHash?{canonicalInputHash:bundle.canonicalInputHash}:{}),schemaVersion:bundle.schemaVersion,engineVersion:bundle.engineVersion,rowCounts:bundle.rowCounts,active:bundle});
const prepared=(bundle:ActiveCanonicalBundle):PreparedCanonicalBundle=>({...imported(bundle),bytes:new Uint8Array(),manifest:{bundleFormat:'blue-jacket-canonical-bundle/v1',motorBuildId:bundle.motorBuildId,stagingManifestHash:bundle.stagingManifestHash,...(bundle.adminRegistryHash?{adminRegistryHash:bundle.adminRegistryHash}:{}),...(bundle.rcaTargetRegistryHash?{rcaTargetRegistryHash:bundle.rcaTargetRegistryHash}:{}),...(bundle.sourceContractVersion?{sourceContractVersion:bundle.sourceContractVersion}:{}),...(bundle.sourceReplacementProofHash?{sourceReplacementProofHash:bundle.sourceReplacementProofHash}:{}),...(bundle.sourceReplacements?{sourceReplacements:bundle.sourceReplacements}:{}),...(bundle.canonicalInputHash?{canonicalInputHash:bundle.canonicalInputHash}:{}),schemaVersion:bundle.schemaVersion,engineVersion:bundle.engineVersion,rowCounts:bundle.rowCounts,files:{},createdAt:bundle.approvedAt}});
const passthroughPersist=async(value:PreparedCanonicalBundle)=>imported(value.active);
const localV21=(overrides:Record<string,unknown>={})=>({localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A,localSourceReplacementProofHash:PROOF_A,localSourceReplacements:[],...overrides});

// 1
test('bundleRecovery é puro e v21 exige identidades Admin, Target e Replacement injetadas',async()=>{const source=readFileSync(new URL('../src/canonical/bundleRecovery.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/indexedDB|adminRegistryIndexedDb|loadAdminRegistryState|loadTargetState|loadSourceReplacementState/);assert.match(source,/localAdminRegistryHash/);assert.match(source,/localRcaTargetRegistryHash/);assert.match(source,/localSourceReplacementProofHash/);const v21=await activeV21Fixture({motorBuildId:'sem-local',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(v21),persistBundle:passthroughPersist,rebuildFromStaging:async()=>v21,activate:()=>undefined}),/BUNDLE_LOCAL_REGISTRY_IDENTITY_REQUIRED/);await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(v21),persistBundle:passthroughPersist,rebuildFromStaging:async()=>v21,activate:()=>undefined,localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A}),/BUNDLE_LOCAL_REPLACEMENT_IDENTITY_REQUIRED/);});
// 2
test('bundle v21 matching ativa diretamente somente com registry target proof e replacements iguais',async()=>{const storage=new MemoryStorage() as unknown as Storage;const compatible=await activeV21Fixture({motorBuildId:'bundle-v21',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});const result=await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(compatible),persistBundle:passthroughPersist,rebuildFromStaging:async()=>{throw new Error('não deve reconstruir')},activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21()});assert.equal(result.mode,'COMPATIBLE');assert.deepEqual(resolveActiveCanonicalBundle(storage),compatible);});
// 3
test('bundle v21 de Target/proof diferente nunca ativa M1–M4 importado e usa rebuild local',async()=>{const storage=new MemoryStorage() as unknown as Storage;const importedA=await activeV21Fixture({motorBuildId:'bundle-A',stagingManifestHash:'HASH_SHARED',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});const rebuiltB=await activeV21Fixture({motorBuildId:'bundle-B-rebuilt',stagingManifestHash:'HASH_SHARED',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_B});let persists=0;const result=await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(importedA),persistBundle:async value=>{persists+=1;return passthroughPersist(value)},rebuildFromStaging:async()=>rebuiltB,activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21({localRcaTargetRegistryHash:TARGET_HASH_B})});assert.equal(result.mode,'REBUILT');assert.equal(persists,0);assert.deepEqual(resolveActiveCanonicalBundle(storage),rebuiltB);});
// 4
test('bundle v20 é legado e ativa somente novo build v21 reconstruído',async()=>{const storage=new MemoryStorage() as unknown as Storage;const legacy=await activeV20Fixture({motorBuildId:'bundle-v20',stagingManifestHash:'HASH_V20',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});const rebuilt=await activeV21Fixture({motorBuildId:'bundle-v21-rebuilt',stagingManifestHash:'HASH_V2',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});const result=await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(legacy),persistBundle:passthroughPersist,rebuildFromStaging:async()=>rebuilt,activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21(),localLegacyStagingManifestHash:'HASH_V20'});assert.equal(result.mode,'REBUILT');assert.equal(result.active.engineVersion,V21_ENGINE);assert.notEqual(result.active.engineVersion,V20_ENGINE);});
// 5
test('bundle legado sem stagings falha BUNDLE_LEGACY_REBUILD_UNAVAILABLE e nunca ativa engine antiga',async()=>{const storage=new MemoryStorage() as unknown as Storage;const legacy=await activeV20Fixture({motorBuildId:'legacy-missing',stagingManifestHash:'HASH_LEGACY',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(legacy),persistBundle:passthroughPersist,rebuildFromStaging:async()=>{throw new Error('SOURCES_MISSING:19')},activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21(),localLegacyStagingManifestHash:'HASH_LEGACY'}),/BUNDLE_LEGACY_REBUILD_UNAVAILABLE/);assert.equal(resolveActiveCanonicalBundle(storage),null);});
// 6
test('reconstrução que ainda devolve engine antiga é rejeitada antes da ativação',async()=>{const storage=new MemoryStorage() as unknown as Storage;const legacy=await activeV20Fixture({motorBuildId:'legacy-A',stagingManifestHash:'HASH_A',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A}),invalid=await activeV20Fixture({motorBuildId:'still-v20',stagingManifestHash:'HASH_A',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(legacy),persistBundle:passthroughPersist,rebuildFromStaging:async()=>invalid,activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21(),localLegacyStagingManifestHash:'HASH_A'}),/BUNDLE_REBUILD_ENGINE_MISMATCH/);assert.equal(resolveActiveCanonicalBundle(storage),null);});
// 7
test('bundle v19 legacy só reconstrói quando physical staging hash v1 local corresponde',async()=>{const storage=new MemoryStorage() as unknown as Storage;const legacy=await activeV19Fixture({motorBuildId:'bundle-v19',stagingManifestHash:'HASH_V19',adminRegistryHash:REGISTRY_HASH_A});const rebuilt=await activeV21Fixture({motorBuildId:'build-v21',stagingManifestHash:'HASH_V2',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});const result=await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(legacy),persistBundle:passthroughPersist,rebuildFromStaging:async()=>rebuilt,activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21(),localLegacyStagingManifestHash:'HASH_V19'});assert.equal(result.mode,'REBUILT');assert.deepEqual(resolveActiveCanonicalBundle(storage),rebuilt);});
// 8
test('bundle legacy physical hash diferente falha BUNDLE_STAGING_SNAPSHOT_MISMATCH antes de ativar',async()=>{const storage=new MemoryStorage() as unknown as Storage;const legacy=await activeV20Fixture({motorBuildId:'legacy-A',stagingManifestHash:'HASH_A',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A}),rebuilt=await activeV21Fixture({motorBuildId:'build-B',stagingManifestHash:'HASH_V2',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(legacy),persistBundle:passthroughPersist,rebuildFromStaging:async()=>rebuilt,activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21(),localLegacyStagingManifestHash:'HASH_B'}),/BUNDLE_STAGING_SNAPSHOT_MISMATCH/);assert.equal(resolveActiveCanonicalBundle(storage),null);});

class MemoryBundleRepository implements CanonicalBundleRepository { readonly data=new Map<string,StoredCanonicalBundle>(); puts=0; async put(bundle:StoredCanonicalBundle){this.puts+=1;this.data.set(bundle.id,bundle)} async get(id:string){return this.data.get(id)} async delete(id:string){this.data.delete(id)} }
const hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
async function realV21BundleFile({buildId,snapshotHash,owner,registryHash=REGISTRY_HASH_A,targetHash=TARGET_HASH_A,proofHash=PROOF_A,replacements=[]}:{buildId:string;snapshotHash:string;owner:string;registryHash?:string;targetHash?:string;proofHash?:string;replacements?:Array<{source:string;scope:string}>}){const payloads=Object.fromEntries(ids.map(id=>{const records=id==='M3_MOVIMENTO_VENDAS'?[{owner,fact_type:'SALE'}]:[{owner}];return[`${id}.json`,strToU8(JSON.stringify({id,records,sources:[],generatedAt:'2026-09-06T00:00:00Z',competence:'2026-09',snapshotDate:'2026-09-06',warnings:[],errors:[]}))]}));const canonicalInputHash=await canonicalInputHashV3(snapshotHash,registryHash,targetHash,proofHash);const manifest={bundleFormat:'blue-jacket-canonical-bundle/v1',motorBuildId:buildId,stagingManifestHash:snapshotHash,adminRegistryHash:registryHash,rcaTargetRegistryHash:targetHash,sourceContractVersion:'v2',sourceReplacementProofHash:proofHash,sourceReplacements:replacements,canonicalInputHash,schemaVersion:'v1',engineVersion:V21_ENGINE,createdAt:'2026-09-06T00:00:00Z',rowCounts:Object.fromEntries(ids.map(id=>[id,1])),files:Object.fromEntries(ids.map(id=>{const path=`${id}.json`,bytes=payloads[path];return[path,{path,bytes:bytes.byteLength,sha256:hash(bytes)}]}))};const bytes=zipSync({'manifest.json':strToU8(JSON.stringify(manifest)),...payloads},{level:6});return new File([bytes],`${buildId}.zip`,{type:'application/zip'});}
const bundleLoadOptions=(repository:CanonicalBundleRepository,activeStorage:Storage)=>({repository,activeStorage,hasGeneratedBuild:async()=>false});
// 9
test('inspeção não persiste; bundle v21 compatível persiste, relê e ativa M1–M4',async()=>{const repository=new MemoryBundleRepository(),storage=new MemoryStorage() as unknown as Storage;const inspected=await inspectCanonicalBundle(await realV21BundleFile({buildId:'build-v21-real',snapshotHash:'HASH_V21',owner:'V21'}));assert.equal(repository.puts,0);await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>inspected,persistBundle:value=>persistCanonicalBundle(value,repository),rebuildFromStaging:async()=>{throw new Error('não deve reconstruir')},activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21()});for(const id of ids)assert.equal((await loadCandidateList(id,bundleLoadOptions(repository,storage))).records[0]?.owner,'V21');assert.equal(repository.puts,1);assert.equal(resolveActiveCanonicalBundle(storage)?.sourceContractVersion,'v2');});
// 10
test('collision com proof/identidade completa preserva referência e M1–M4 reais do BUILD_B',async()=>{const repository=new MemoryBundleRepository(),storage=new MemoryStorage() as unknown as Storage;const buildB=await inspectCanonicalBundle(await realV21BundleFile({buildId:'COLLISION_X',snapshotHash:'HASH_B',owner:'B'}));await persistCanonicalBundle(buildB,repository);activateCanonicalBundleReference(buildB.active,storage);const bundleA=await inspectCanonicalBundle(await realV21BundleFile({buildId:'COLLISION_X',snapshotHash:'HASH_A',owner:'A',proofHash:PROOF_B}));const putsBefore=repository.puts;const rebuilt=await activeV21Fixture({motorBuildId:'rebuild-A',stagingManifestHash:'HASH_OTHER',adminRegistryHash:REGISTRY_HASH_A,rcaTargetRegistryHash:TARGET_HASH_A});await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>bundleA,persistBundle:value=>persistCanonicalBundle(value,repository),rebuildFromStaging:async()=>rebuilt,activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21()}),/BUNDLE_STAGING_SNAPSHOT_MISMATCH/);assert.equal(repository.puts,putsBefore);assert.deepEqual(resolveActiveCanonicalBundle(storage),buildB.active);for(const id of ids)assert.equal((await loadCandidateList(id,bundleLoadOptions(repository,storage))).records[0]?.owner,'B');});
// 11
test('falha de verificação da persistência restaura atomicamente o bundle anterior',async()=>{const repository=new MemoryBundleRepository(),storage=new MemoryStorage() as unknown as Storage;const buildB=await inspectCanonicalBundle(await realV21BundleFile({buildId:'ATOMIC_X',snapshotHash:'HASH_B',owner:'B'}));await persistCanonicalBundle(buildB,repository);activateCanonicalBundleReference(buildB.active,storage);const bundleA=await inspectCanonicalBundle(await realV21BundleFile({buildId:'ATOMIC_X',snapshotHash:'HASH_A',owner:'A'}));const originalPut=repository.put.bind(repository);let corruptNext=true;repository.put=async value=>{await originalPut(value);if(corruptNext){corruptNext=false;const stored=repository.data.get(value.id)!;repository.data.set(value.id,{...stored,manifest:{...stored.manifest,stagingManifestHash:'CORRUPT'}})}};await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>bundleA,persistBundle:value=>persistCanonicalBundle(value,repository),rebuildFromStaging:async()=>{throw new Error('não deve reconstruir')},activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},...localV21()}),/BUNDLE_STORAGE_VERIFY_FAILED/);assert.deepEqual(resolveActiveCanonicalBundle(storage),buildB.active);assert.equal((await repository.get('ATOMIC_X'))?.manifest.stagingManifestHash,'HASH_B');});
// 12
test('Bases não edita Meta Redes e MetasPage continua como editor oficial via TargetState',()=>{const bases=readFileSync(new URL('../src/pages/admin/BasesPage.tsx',import.meta.url),'utf8'),admin=readFileSync(new URL('../src/pages/admin/AdminPage.tsx',import.meta.url),'utf8'),targets=readFileSync(new URL('../src/pages/MetasPage.tsx',import.meta.url),'utf8');assert.doesNotMatch(bases,/saveNetworkTarget|setNetworkTargetFor|Salvar Meta Redes/);assert.match(admin,/view === 'metas'\) return <MetasPage \/>/);assert.match(targets,/canonicalTargetActions/);assert.match(targets,/Meta Redes Geral/);});
