import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { strToU8, zipSync } from 'fflate';
import { recoverTechnicalBundle } from '../src/canonical/bundleRecovery.ts';
import { CANONICAL_ENGINE_VERSION } from '../src/canonical/sourceImport.ts';
import { activateCanonicalBundleReference, resolveActiveCanonicalBundle, type ActiveCanonicalBundle } from '../src/canonical/runtime.ts';
import { inspectCanonicalBundle, persistCanonicalBundle, type BundleImportResult, type CanonicalBundleRepository, type PreparedCanonicalBundle, type StoredCanonicalBundle } from '../src/canonical/bundleStore.ts';
import { loadCandidateList } from '../src/canonical/candidateLists.ts';

class MemoryStorage { private data=new Map<string,string>(); get length(){return this.data.size} clear(){this.data.clear()} getItem(key:string){return this.data.get(key)??null} key(index:number){return [...this.data.keys()][index]??null} removeItem(key:string){this.data.delete(key)} setItem(key:string,value:string){this.data.set(key,value)} }
const ids=['M1_ITEM_ESTOQUE','M2_CLIENTE_RCA','M3_MOVIMENTO_VENDAS','M4_HISTORICO_TRANSICAO'] as const;
const REGISTRY_HASH_A='registry-hash-A',REGISTRY_HASH_B='registry-hash-B',TARGET_HASH_A='target-hash-A',TARGET_HASH_B='target-hash-B';
const inputV1=(s:string,a:string)=>createHash('sha256').update(JSON.stringify(['blue-jacket-canonical-input/v1',s,a])).digest('hex');
const inputV2=(s:string,a:string,t:string)=>createHash('sha256').update(JSON.stringify(['blue-jacket-canonical-input/v2',s,a,t])).digest('hex');
const V19='browser-stage4-product-assortment-v19-admin-registry-authority';
const activeBase=(id:string,engineVersion:string,stagingManifestHash:string):ActiveCanonicalBundle=>({status:'ACTIVE',motorBuildId:id,stagingManifestHash,schemaVersion:'v1',engineVersion,approvedAt:'2026-09-06T00:00:00Z',rowCounts:{M1_ITEM_ESTOQUE:1,M2_CLIENTE_RCA:1,M3_MOVIMENTO_VENDAS:1,M4_HISTORICO_TRANSICAO:1},factTypeCounts:{SALE:1,INBOUND_ORDER:0,RECEIPT:0,TARGET:0}});
const activeV20=(id:string,stagingManifestHash=`hash-${id}`,adminRegistryHash=REGISTRY_HASH_A,rcaTargetRegistryHash=TARGET_HASH_A):ActiveCanonicalBundle=>({...activeBase(id,CANONICAL_ENGINE_VERSION,stagingManifestHash),adminRegistryHash,rcaTargetRegistryHash,canonicalInputHash:inputV2(stagingManifestHash,adminRegistryHash,rcaTargetRegistryHash)});
const activeV19=(id:string,stagingManifestHash=`hash-${id}`,adminRegistryHash=REGISTRY_HASH_A):ActiveCanonicalBundle=>({...activeBase(id,V19,stagingManifestHash),adminRegistryHash,canonicalInputHash:inputV1(stagingManifestHash,adminRegistryHash)});
const activeLegacy=(id:string,stagingManifestHash=`hash-${id}`,engineVersion='stage3-v1'):ActiveCanonicalBundle=>activeBase(id,engineVersion,stagingManifestHash);
const imported=(bundle:ActiveCanonicalBundle):BundleImportResult=>({motorBuildId:bundle.motorBuildId,stagingManifestHash:bundle.stagingManifestHash,...(bundle.adminRegistryHash?{adminRegistryHash:bundle.adminRegistryHash}:{}),...(bundle.rcaTargetRegistryHash?{rcaTargetRegistryHash:bundle.rcaTargetRegistryHash}:{}),...(bundle.canonicalInputHash?{canonicalInputHash:bundle.canonicalInputHash}:{}),schemaVersion:bundle.schemaVersion,engineVersion:bundle.engineVersion,rowCounts:bundle.rowCounts,active:bundle});
const prepared=(bundle:ActiveCanonicalBundle):PreparedCanonicalBundle=>({...imported(bundle),bytes:new Uint8Array(),manifest:{bundleFormat:'blue-jacket-canonical-bundle/v1',motorBuildId:bundle.motorBuildId,stagingManifestHash:bundle.stagingManifestHash,...(bundle.adminRegistryHash?{adminRegistryHash:bundle.adminRegistryHash}:{}),...(bundle.rcaTargetRegistryHash?{rcaTargetRegistryHash:bundle.rcaTargetRegistryHash}:{}),...(bundle.canonicalInputHash?{canonicalInputHash:bundle.canonicalInputHash}:{}),schemaVersion:bundle.schemaVersion,engineVersion:bundle.engineVersion,rowCounts:bundle.rowCounts,files:{},createdAt:bundle.approvedAt}});
const passthroughPersist=async(value:PreparedCanonicalBundle)=>imported(value.active);

// 1
test('bundleRecovery é puro e v20 exige identidades Admin Registry + RCA Target injetadas',async()=>{const source=readFileSync(new URL('../src/canonical/bundleRecovery.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/indexedDB|adminRegistryIndexedDb|loadAdminRegistryState|loadTargetState/);assert.match(source,/localAdminRegistryHash/);assert.match(source,/localRcaTargetRegistryHash/);await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(activeV20('sem-local')),persistBundle:passthroughPersist,rebuildFromStaging:async()=>activeV20('nao-roda'),activate:()=>undefined}),/BUNDLE_LOCAL_REGISTRY_IDENTITY_REQUIRED/);await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(activeV20('sem-target-local')),persistBundle:passthroughPersist,rebuildFromStaging:async()=>activeV20('nao-roda'),activate:()=>undefined,localAdminRegistryHash:REGISTRY_HASH_A}),/BUNDLE_LOCAL_TARGET_IDENTITY_REQUIRED/);});
// 2
test('bundle v20 compatível restaura referência exata somente com registry e target hashes iguais',async()=>{const storage=new MemoryStorage() as unknown as Storage;const compatible=activeV20('bundle-v20');const result=await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(compatible),persistBundle:passthroughPersist,rebuildFromStaging:async()=>{throw new Error('não deve reconstruir')},activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A});assert.equal(result.mode,'COMPATIBLE');assert.deepEqual(resolveActiveCanonicalBundle(storage),compatible);});
// 3
test('bundle v20 de Target Registry diferente nunca ativa M3 importado e usa rebuild local',async()=>{const storage=new MemoryStorage() as unknown as Storage;const importedA=activeV20('bundle-target-A','HASH_SHARED',REGISTRY_HASH_A,TARGET_HASH_A);const rebuiltB=activeV20('bundle-target-B-rebuilt','HASH_SHARED',REGISTRY_HASH_A,TARGET_HASH_B);let persists=0;const result=await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(importedA),persistBundle:async value=>{persists+=1;return passthroughPersist(value)},rebuildFromStaging:async()=>rebuiltB,activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_B});assert.equal(result.mode,'REBUILT');assert.equal(persists,0);assert.deepEqual(resolveActiveCanonicalBundle(storage),rebuiltB);assert.equal(result.active.rcaTargetRegistryHash,TARGET_HASH_B);assert.equal(result.active.canonicalInputHash,inputV2('HASH_SHARED',REGISTRY_HASH_A,TARGET_HASH_B));});
// 4
test('bundle v19 é legado e ativa somente novo build v20 reconstruído',async()=>{const storage=new MemoryStorage() as unknown as Storage;const legacy=activeV19('bundle-v19','HASH_V19',REGISTRY_HASH_A);const rebuilt=activeV20('bundle-v20-reconstruido','HASH_V19',REGISTRY_HASH_A,TARGET_HASH_A);const result=await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(legacy),persistBundle:passthroughPersist,rebuildFromStaging:async()=>rebuilt,activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A});assert.equal(result.mode,'REBUILT');assert.equal(result.active.motorBuildId,'bundle-v20-reconstruido');assert.equal(resolveActiveCanonicalBundle(storage)?.engineVersion,CANONICAL_ENGINE_VERSION);});
// 5
test('bundle legado sem stagings falha controladamente e nunca ativa engine antiga',async()=>{const storage=new MemoryStorage() as unknown as Storage;await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(activeLegacy('bundle-legado')),persistBundle:passthroughPersist,rebuildFromStaging:async()=>{throw new Error('SOURCES_MISSING:19')},activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A}),/BUNDLE_LEGACY_REBUILD_UNAVAILABLE/);assert.equal(resolveActiveCanonicalBundle(storage),null);});
// 6
test('reconstrução que ainda devolve engine antiga é rejeitada antes da ativação',async()=>{const storage=new MemoryStorage() as unknown as Storage;await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(activeLegacy('bundle-A')),persistBundle:passthroughPersist,rebuildFromStaging:async()=>activeV19('rebuild-invalido','hash-bundle-A'),activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A}),/BUNDLE_REBUILD_ENGINE_MISMATCH/);assert.equal(resolveActiveCanonicalBundle(storage),null);});
// 7
test('bundle legado somente reconstrói quando stagingManifestHash identifica o mesmo snapshot',async()=>{const storage=new MemoryStorage() as unknown as Storage;const legacy=activeLegacy('bundle-A','HASH_A');const rebuilt=activeV20('build-reconstruido','HASH_A');const result=await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(legacy),persistBundle:passthroughPersist,rebuildFromStaging:async()=>rebuilt,activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A});assert.equal(result.mode,'REBUILT');assert.deepEqual(resolveActiveCanonicalBundle(storage),rebuilt);});
// 8
test('bundle legado rejeita rebuild de snapshot diferente antes de ativar',async()=>{const storage=new MemoryStorage() as unknown as Storage;await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>prepared(activeLegacy('bundle-A','HASH_A')),persistBundle:passthroughPersist,rebuildFromStaging:async()=>activeV20('build-B','HASH_B'),activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A}),/BUNDLE_STAGING_SNAPSHOT_MISMATCH/);assert.equal(resolveActiveCanonicalBundle(storage),null);});

class MemoryBundleRepository implements CanonicalBundleRepository { readonly data=new Map<string,StoredCanonicalBundle>(); puts=0; async put(bundle:StoredCanonicalBundle){this.puts+=1;this.data.set(bundle.id,bundle)} async get(id:string){return this.data.get(id)} async delete(id:string){this.data.delete(id)} }
const hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
function realBundleFile({buildId,snapshotHash,engineVersion,owner,registryHash=REGISTRY_HASH_A,targetHash=TARGET_HASH_A}:{buildId:string;snapshotHash:string;engineVersion:string;owner:string;registryHash?:string;targetHash?:string}){const payloads=Object.fromEntries(ids.map(id=>{const records=id==='M3_MOVIMENTO_VENDAS'?[{owner,fact_type:'SALE'}]:[{owner}];return[`${id}.json`,strToU8(JSON.stringify({id,records,sources:[],generatedAt:'2026-09-06T00:00:00Z',competence:'2026-09',snapshotDate:'2026-09-06',warnings:[],errors:[]}))]}));const identity=engineVersion===CANONICAL_ENGINE_VERSION?{adminRegistryHash:registryHash,rcaTargetRegistryHash:targetHash,canonicalInputHash:inputV2(snapshotHash,registryHash,targetHash)}:engineVersion===V19?{adminRegistryHash:registryHash,canonicalInputHash:inputV1(snapshotHash,registryHash)}:{};const manifest={bundleFormat:'blue-jacket-canonical-bundle/v1',motorBuildId:buildId,stagingManifestHash:snapshotHash,...identity,schemaVersion:'v1',engineVersion,createdAt:'2026-09-06T00:00:00Z',rowCounts:Object.fromEntries(ids.map(id=>[id,1])),files:Object.fromEntries(ids.map(id=>{const path=`${id}.json`,bytes=payloads[path];return[path,{path,bytes:bytes.byteLength,sha256:hash(bytes)}]}))};const bytes=zipSync({'manifest.json':strToU8(JSON.stringify(manifest)),...payloads},{level:6});return new File([bytes],`${buildId}.zip`,{type:'application/zip'});}
const bundleLoadOptions=(repository:CanonicalBundleRepository,activeStorage:Storage)=>({repository,activeStorage,hasGeneratedBuild:async()=>false});
// 9
test('inspeção não persiste; bundle v20 compatível persiste, relê e ativa M1–M4',async()=>{const repository=new MemoryBundleRepository(),storage=new MemoryStorage() as unknown as Storage;const inspected=await inspectCanonicalBundle(realBundleFile({buildId:'build-v20',snapshotHash:'HASH_V20',engineVersion:CANONICAL_ENGINE_VERSION,owner:'V20'}));assert.equal(repository.puts,0);await recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>inspected,persistBundle:value=>persistCanonicalBundle(value,repository),rebuildFromStaging:async()=>{throw new Error('não deve reconstruir')},activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A});for(const id of ids)assert.equal((await loadCandidateList(id,bundleLoadOptions(repository,storage))).records[0]?.owner,'V20');assert.equal(repository.puts,1);const resolved=resolveActiveCanonicalBundle(storage);assert.equal(resolved?.rcaTargetRegistryHash,TARGET_HASH_A);assert.equal(resolved?.canonicalInputHash,inputV2('HASH_V20',REGISTRY_HASH_A,TARGET_HASH_A));});
// 10
test('mismatch com colisão de motorBuildId preserva referência e M1–M4 reais do BUILD_B',async()=>{const repository=new MemoryBundleRepository(),storage=new MemoryStorage() as unknown as Storage;const buildB=await inspectCanonicalBundle(realBundleFile({buildId:'COLLISION_X',snapshotHash:'HASH_B',engineVersion:CANONICAL_ENGINE_VERSION,owner:'B'}));await persistCanonicalBundle(buildB,repository);activateCanonicalBundleReference(buildB.active,storage);const bundleA=await inspectCanonicalBundle(realBundleFile({buildId:'COLLISION_X',snapshotHash:'HASH_A',engineVersion:'stage3-v1',owner:'A'}));const putsBefore=repository.puts;await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>bundleA,persistBundle:value=>persistCanonicalBundle(value,repository),rebuildFromStaging:async()=>activeV20('rebuild-A','HASH_OTHER'),activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A}),/BUNDLE_STAGING_SNAPSHOT_MISMATCH/);assert.equal(repository.puts,putsBefore);assert.deepEqual(resolveActiveCanonicalBundle(storage),buildB.active);assert.equal((await repository.get('COLLISION_X'))?.manifest.stagingManifestHash,'HASH_B');for(const id of ids)assert.equal((await loadCandidateList(id,bundleLoadOptions(repository,storage))).records[0]?.owner,'B');});
// 11
test('falha de verificação da persistência restaura atomicamente o bundle anterior',async()=>{const repository=new MemoryBundleRepository(),storage=new MemoryStorage() as unknown as Storage;const buildB=await inspectCanonicalBundle(realBundleFile({buildId:'ATOMIC_X',snapshotHash:'HASH_B',engineVersion:CANONICAL_ENGINE_VERSION,owner:'B'}));await persistCanonicalBundle(buildB,repository);activateCanonicalBundleReference(buildB.active,storage);const bundleA=await inspectCanonicalBundle(realBundleFile({buildId:'ATOMIC_X',snapshotHash:'HASH_A',engineVersion:CANONICAL_ENGINE_VERSION,owner:'A'}));const originalPut=repository.put.bind(repository);let corruptNext=true;repository.put=async value=>{await originalPut(value);if(corruptNext){corruptNext=false;const stored=repository.data.get(value.id)!;repository.data.set(value.id,{...stored,manifest:{...stored.manifest,stagingManifestHash:'CORRUPT'}})}};await assert.rejects(()=>recoverTechnicalBundle({currentEngineVersion:CANONICAL_ENGINE_VERSION,inspectBundle:async()=>bundleA,persistBundle:value=>persistCanonicalBundle(value,repository),rebuildFromStaging:async()=>{throw new Error('não deve reconstruir')},activate:bundle=>{activateCanonicalBundleReference(bundle,storage)},localAdminRegistryHash:REGISTRY_HASH_A,localRcaTargetRegistryHash:TARGET_HASH_A}),/BUNDLE_STORAGE_VERIFY_FAILED/);assert.deepEqual(resolveActiveCanonicalBundle(storage),buildB.active);assert.equal((await repository.get('ATOMIC_X'))?.manifest.stagingManifestHash,'HASH_B');});
// 12
test('Bases não edita Meta Redes e MetasPage continua como editor oficial via TargetState',()=>{const bases=readFileSync(new URL('../src/pages/admin/BasesPage.tsx',import.meta.url),'utf8'),admin=readFileSync(new URL('../src/pages/admin/AdminPage.tsx',import.meta.url),'utf8'),targets=readFileSync(new URL('../src/pages/MetasPage.tsx',import.meta.url),'utf8');assert.doesNotMatch(bases,/saveNetworkTarget|setNetworkTargetFor|Meta Redes Geral|Salvar Meta Redes/);assert.match(admin,/view === 'metas'\) return <MetasPage \/>/);assert.match(targets,/canonicalTargetActions/);assert.match(targets,/Meta Redes Geral/);});
