import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { canonicalAdminRegistryHash } from '../src/canonical/adminRegistryIdentity.ts';
import { cloudSyncTestHelpers, type CloudUploadDependencies, type DeviceSyncIdentity } from '../src/canonical/cloudSync.ts';
import type { ActiveCanonicalBundle } from '../src/canonical/runtime.ts';
import { sourceStorageSnapshotManifestHash } from '../src/canonical/sourceSnapshotIdentity.ts';
import { createSystemDataOperationCoordinator } from '../src/canonical/systemDataOperationCoordinator.ts';
import { CANONICAL_ENGINE_VERSION, REQUIRED_SOURCE_IDS, type SourceStorageSnapshot } from '../src/canonical/sourceImport.ts';
import { canonicalInputHashV2, rcaTargetRegistryHash } from '../src/canonical/targetIdentity.ts';
import { syncActiveBuildIfPaired, type BaseAutoSyncDependencies } from '../src/pages/admin/baseAutoSync.ts';
import { activateBuildAndWaitForAutoSync } from '../src/pages/admin/baseUpdateFlow.ts';

const NOW='2026-09-06T16:00:00.000Z'; const sourceText=(relative:string)=>readFileSync(new URL(relative,import.meta.url),'utf8'); const tick=()=>new Promise<void>(resolve=>queueMicrotask(resolve));
function deferred<T>(){let resolve!:(value:T)=>void;let reject!:(reason?:unknown)=>void;const promise=new Promise<T>((res,rej)=>{resolve=res;reject=rej});return{promise,resolve,reject};}
const identity:DeviceSyncIdentity={workspaceId:'11111111-1111-4111-8111-111111111111',secret:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'};
const build=async(motorBuildId:string,stagingManifestHash='HASH'):Promise<ActiveCanonicalBundle>=>{const adminRegistryHash=await canonicalAdminRegistryHash(null);const rcaTargetHash=await rcaTargetRegistryHash(null);return{status:'ACTIVE',motorBuildId,stagingManifestHash,adminRegistryHash,rcaTargetRegistryHash:rcaTargetHash,canonicalInputHash:await canonicalInputHashV2(stagingManifestHash,adminRegistryHash,rcaTargetHash),schemaVersion:'v1',engineVersion:CANONICAL_ENGINE_VERSION,approvedAt:NOW,rowCounts:{M1_ITEM_ESTOQUE:0,M2_CLIENTE_RCA:0,M3_MOVIMENTO_VENDAS:0,M4_HISTORICO_TRANSICAO:0},factTypeCounts:{SALE:0,INBOUND_ORDER:0,RECEIPT:0,TARGET:0}}};
function makeSources(seed:string):SourceStorageSnapshot{return{format:'blue-jacket-source-storage/v1',exportedAt:NOW,staging:REQUIRED_SOURCE_IDS.map((source,index)=>({source,manifest:{source,fileName:`${source}-${seed}`,fileHash:`${seed}-hash-${index}`,parserVersion:`${seed}-parser-${index}`,schemaVersion:'v1',parsedRows:0,warnings:0,errors:0,updatedAt:NOW,status:'VALID'},parsed:{source,fileName:`${source}-${seed}`,sheet:'test',rows:[],audits:[]}}))} as SourceStorageSnapshot;}
function uploadDependencies(options:{sources:SourceStorageSnapshot;actives:ActiveCanonicalBundle[];onPut:()=>void}):CloudUploadDependencies{let activeRead=0;return{getActive:()=>options.actives[Math.min(activeRead++,options.actives.length-1)]??null,exportSources:async()=>options.sources,sourceManifestHash:sourceStorageSnapshotManifestHash,registryHash:canonicalAdminRegistryHash,targetHash:rcaTargetRegistryHash,inputHash:canonicalInputHashV2,loadSettings:()=>({networkTargetByCompetence:{},networkAllocationByCompetence:{},sellOutTargetByCompetence:{},positivityTargetByCompetence:{},legacySellOutTarget:null,legacyPositivityTarget:null,inboundForecastByInvoice:{}}),loadCompetence:()=>null,loadAdminRegistry:async()=>null,loadTargetState:()=>null,encryptSnapshot:async()=>new Uint8Array([1,2,3]),uploadPayload:async()=>{options.onPut();return{updatedAt:NOW,bytes:3}},saveState:()=>undefined,now:()=>NOW};}

test('S1 — BASE_UPDATE pendente bloqueia SYNC_SEND antes do upload',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();let uploads=0;const base=c.run('BASE_UPDATE',async()=>p.promise);await tick();assert.deepEqual(await c.run('SYNC_SEND',async()=>{uploads+=1}),{status:'BUSY',owner:'BASE_UPDATE'});assert.equal(uploads,0);p.resolve();await base;});
test('S2 — SYNC_SEND pendente bloqueia BASE_UPDATE antes de processSourceUpdates',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();let calls=0;const send=c.run('SYNC_SEND',async()=>p.promise);await tick();assert.deepEqual(await c.run('BASE_UPDATE',async()=>{calls+=1}),{status:'BUSY',owner:'SYNC_SEND'});assert.equal(calls,0);p.resolve();await send;});
test('S3 — unsubscribe/remount não libera gate de SYNC_SEND',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();let state=c.getState();const off=c.subscribe(next=>{state=next});const send=c.run('SYNC_SEND',async()=>p.promise);await tick();assert.deepEqual(state,{busy:true,owner:'SYNC_SEND'});off();let remount=c.getState();const off2=c.subscribe(next=>{remount=next});assert.deepEqual(remount,{busy:true,owner:'SYNC_SEND'});assert.deepEqual(await c.run('BASE_UPDATE',async()=>undefined),{status:'BUSY',owner:'SYNC_SEND'});p.resolve();await send;off2();});
test('S4 — BASE_UPDATE sobrevive remount e mantém Send/Restore/Bundle bloqueados',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();const base=c.run('BASE_UPDATE',async()=>p.promise);await tick();for(const owner of ['SYNC_SEND','SYNC_RESTORE','BUNDLE_RECOVERY'] as const)assert.equal((await c.run(owner,async()=>undefined)).status,'BUSY');p.resolve();await base;});
test('S5 — auto-sync dentro de BASE_UPDATE não readquire gate nem deadlocka e faz um upload',async()=>{const c=createSystemDataOperationCoordinator(),active=await build('BUILD_S5');let uploads=0;const deps:BaseAutoSyncDependencies={getIdentity:()=>identity,getActive:()=>active,upload:async()=>{uploads+=1;return{bytes:10,active,updatedAt:NOW}}};const result=await c.run('BASE_UPDATE',async()=>activateBuildAndWaitForAutoSync(active,()=>undefined,async()=>syncActiveBuildIfPaired(active.motorBuildId,deps)));assert.equal(result.status,'DONE');assert.equal(uploads,1);assert.deepEqual(c.getState(),{busy:false,owner:null});assert.doesNotMatch(sourceText('../src/pages/admin/baseAutoSync.ts'),/systemDataOperationCoordinator/);});
test('S6 — SYNC_RESTORE pendente bloqueia BASE_UPDATE',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();const restore=c.run('SYNC_RESTORE',async()=>p.promise);await tick();assert.deepEqual(await c.run('BASE_UPDATE',async()=>undefined),{status:'BUSY',owner:'SYNC_RESTORE'});p.resolve();await restore;});
test('S7 — BASE_UPDATE pendente bloqueia restore antes da restauração',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();let restores=0;const base=c.run('BASE_UPDATE',async()=>p.promise);await tick();assert.deepEqual(await c.run('SYNC_RESTORE',async()=>{restores+=1}),{status:'BUSY',owner:'BASE_UPDATE'});assert.equal(restores,0);p.resolve();await base;});
test('S8 — BUNDLE_RECOVERY pendente bloqueia BASE_UPDATE',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();const bundle=c.run('BUNDLE_RECOVERY',async()=>p.promise);await tick();assert.deepEqual(await c.run('BASE_UPDATE',async()=>undefined),{status:'BUSY',owner:'BUNDLE_RECOVERY'});p.resolve();await bundle;});
test('S9 — BASE_UPDATE pendente bloqueia Bundle antes de inspect/persist/recover',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();let calls=0;const base=c.run('BASE_UPDATE',async()=>p.promise);await tick();assert.deepEqual(await c.run('BUNDLE_RECOVERY',async()=>{calls+=1}),{status:'BUSY',owner:'BASE_UPDATE'});assert.equal(calls,0);p.resolve();await base;});
test('S10 — source hash igual ao active permite exatamente um PUT',async()=>{const sources=makeSources('A'),hash=await sourceStorageSnapshotManifestHash(sources),active=await build('BUILD_A',hash);let puts=0;const result=await cloudSyncTestHelpers.uploadCurrentDeviceSnapshotWithDependencies(identity,uploadDependencies({sources,actives:[active,active],onPut:()=>{puts+=1}}));assert.equal(result.active.motorBuildId,'BUILD_A');assert.equal(puts,1);assert.equal((sourceText('../src/canonical/cloudSync.ts').match(/method: 'PUT'/g)??[]).length,1);});
test('S11 — sources em transição abortam antes do PUT mesmo com active BUILD_A estável',async()=>{const sourcesA=makeSources('A'),sourcesB=makeSources('B'),active=await build('BUILD_A',await sourceStorageSnapshotManifestHash(sourcesA));let puts=0;await assert.rejects(()=>cloudSyncTestHelpers.uploadCurrentDeviceSnapshotWithDependencies(identity,uploadDependencies({sources:sourcesB,actives:[active,active],onPut:()=>{puts+=1}})),/SYNC_SNAPSHOT_CHANGED_DURING_CAPTURE/);assert.equal(puts,0);});
test('S12 — active mudando durante a captura aborta antes do PUT',async()=>{const sources=makeSources('A'),hash=await sourceStorageSnapshotManifestHash(sources),a=await build('BUILD_A',hash),b=await build('BUILD_B',hash);let puts=0;await assert.rejects(()=>cloudSyncTestHelpers.uploadCurrentDeviceSnapshotWithDependencies(identity,uploadDependencies({sources,actives:[a,b],onPut:()=>{puts+=1}})),/SYNC_SNAPSHOT_CHANGED_DURING_CAPTURE/);assert.equal(puts,0);});
test('S13 — dois envios manuais concorrentes resultam em um único PUT',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();let puts=0;const first=c.run('SYNC_SEND',async()=>{puts+=1;await p.promise});await tick();assert.deepEqual(await c.run('SYNC_SEND',async()=>{puts+=1}),{status:'BUSY',owner:'SYNC_SEND'});assert.equal(puts,1);p.resolve();await first;});
test('S14 — Restore e Send se bloqueiam nos dois sentidos',async()=>{const a=createSystemDataOperationCoordinator(),p1=deferred<void>(),r=a.run('SYNC_RESTORE',async()=>p1.promise);await tick();assert.deepEqual(await a.run('SYNC_SEND',async()=>undefined),{status:'BUSY',owner:'SYNC_RESTORE'});p1.resolve();await r;const b=createSystemDataOperationCoordinator(),p2=deferred<void>(),s=b.run('SYNC_SEND',async()=>p2.promise);await tick();assert.deepEqual(await b.run('SYNC_RESTORE',async()=>undefined),{status:'BUSY',owner:'SYNC_SEND'});p2.resolve();await s;});
test('S15 — STARTUP_REMOTE_RESTORE bloqueia Bases e libera após conclusão',async()=>{const c=createSystemDataOperationCoordinator(),p=deferred<void>();let bases=0;const startup=c.run('STARTUP_REMOTE_RESTORE',async()=>p.promise);await tick();assert.deepEqual(await c.run('BASE_UPDATE',async()=>{bases+=1}),{status:'BUSY',owner:'STARTUP_REMOTE_RESTORE'});assert.equal(bases,0);p.resolve();await startup;assert.equal((await c.run('BASE_UPDATE',async()=>{bases+=1})).status,'DONE');assert.equal(bases,1);});
test('S16 — erro da operação libera o gate para a próxima ação',async()=>{const c=createSystemDataOperationCoordinator();await assert.rejects(()=>c.run('SYNC_SEND',async()=>{throw new Error('SEND_FAILED')}),/SEND_FAILED/);assert.deepEqual(c.getState(),{busy:false,owner:null});assert.deepEqual(await c.run('BASE_UPDATE',async()=>'OK'),{status:'DONE',value:'OK'});});
test('S17 — sucesso da operação libera o gate para a próxima ação',async()=>{const c=createSystemDataOperationCoordinator();assert.deepEqual(await c.run('SYNC_SEND',async()=>'SENT'),{status:'DONE',value:'SENT'});assert.deepEqual(c.getState(),{busy:false,owner:null});assert.deepEqual(await c.run('BUNDLE_RECOVERY',async()=>'RECOVERED'),{status:'DONE',value:'RECOVERED'});assert.match(sourceText('../src/pages/admin/SincronizacaoPage.tsx'),/run\('SYNC_CREATE_AND_SEND'/);assert.match(sourceText('../src/pages/admin/SincronizacaoPage.tsx'),/run\('SYNC_PAIR_AND_RESTORE'/);});
