import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { loadCandidateList } from '../canonical/candidateLists';
import type { CanonicalList } from '../canonical/types';
import { useData } from '../store/DataContext';
import { PanelAlert, PanelCard, PanelEmptyState, PanelPage, PanelSectionHeader, PanelStat } from '../ui/pattern/PanelVisual';

const text=(value:unknown)=>String(value??'').trim();
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const download=(name:string,content:string)=>{const href=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=href;anchor.download=name;document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(href),30000)};

export function CriacaoComboPage() {
  const {activeCanonical}=useData();
  const [m1,setM1]=useState<CanonicalList|null>(null);const [m2,setM2]=useState<CanonicalList|null>(null);const [query,setQuery]=useState('');const [discount,setDiscount]=useState('0');const [products,setProducts]=useState<Set<string>>(new Set());const [clients,setClients]=useState<Set<string>>(new Set());const [notice,setNotice]=useState('');
  useEffect(()=>{if(!activeCanonical){setM1(null);setM2(null);return}let live=true;Promise.all([loadCandidateList('M1_ITEM_ESTOQUE'),loadCandidateList('M2_CLIENTE_RCA')]).then(([items,customers])=>{if(live){setM1(items);setM2(customers)}});return()=>{live=false}},[activeCanonical?.motorBuildId]);
  const eligible=useMemo(()=>(m1?.records??[]).filter(record=>Number(record.pVenda1_region11)>0),[m1]);
  const normalizedQuery=query.toLocaleLowerCase();const visible=eligible.filter(record=>!normalizedQuery||[record.description_internal,record.winthor_code,record.internal_ean].some(value=>text(value).toLocaleLowerCase().includes(normalizedQuery))).slice(0,100);const customerRows=(m2?.records??[]).slice(0,100);const pct=Math.max(0,Math.min(100,Number(discount)||0));
  const toggle=(setter:Dispatch<SetStateAction<Set<string>>>,key:string)=>setter(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next});
  const exportCombo=()=>{if(!products.size||!clients.size)return;const rows=['codigo;produto;preco_tabela;desconto_pct;preco_combo;clientes'];for(const record of eligible.filter(item=>products.has(text(item.item_canonical_id)))){const price=Number(record.pVenda1_region11)||0;rows.push([text(record.winthor_code),text(record.description_internal).replace(/;/g,','),price.toFixed(2),pct.toFixed(2),(price*(1-pct/100)).toFixed(2),clients.size].join(';'))}download(`blue-jacket-combo-${new Date().toISOString().slice(0,10)}.csv`,rows.join('\n'));setNotice('COMBO EXPORTADO — arquivo CSV gerado com produtos, preço e público selecionados.')};
  if(!activeCanonical)return <PanelPage title="Criação de Combo"><PanelEmptyState variant="page" title="Sem build canônico ativo" description="Atualize as bases antes de criar um combo."/></PanelPage>;
  if(!m1||!m2)return <PanelPage title="Criação de Combo"><PanelAlert>Lendo produtos, preços e clientes do build ativo…</PanelAlert></PanelPage>;
  return <PanelPage title="Criação de Combo" metricLabel="Produtos elegíveis" metricValue={eligible.length}><div className="panel-stack">
    {notice?<PanelAlert tone="success">{notice}</PanelAlert>:null}<div className="panel-stat-grid"><PanelStat label="Produtos selecionados" value={products.size}/><PanelStat label="Clientes selecionados" value={clients.size}/><PanelStat label="Desconto" value={`${pct}%`}/><PanelStat label="Clientes disponíveis" value={m2.records.length}/></div>
    <PanelCard><PanelSectionHeader eyebrow="COMBO OPERACIONAL" title="Produtos e preço praticado" description="Selecione itens com PVENDA1 da região 11 e aplique o desconto comercial."/><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar produto, código ou EAN"/><label>Desconto % <input value={discount} onChange={event=>setDiscount(event.target.value)} inputMode="decimal" style={{width:100}}/></label></div><div className="panel-table-wrap"><table className="panel-table"><thead><tr><th></th><th>Código</th><th>Produto</th><th>PVENDA1</th><th>Preço combo</th></tr></thead><tbody>{visible.map((record,index)=>{const id=text(record.item_canonical_id)||String(index),price=Number(record.pVenda1_region11)||0;return <tr key={id}><td><input type="checkbox" checked={products.has(id)} onChange={()=>toggle(setProducts,id)}/></td><td>{text(record.winthor_code)||'—'}</td><td>{text(record.description_internal)||'—'}</td><td>{money.format(price)}</td><td>{money.format(price*(1-pct/100))}</td></tr>})}</tbody></table></div></PanelCard>
    <PanelCard><PanelSectionHeader eyebrow="PÚBLICO" title="Clientes do combo" description="A seleção usa os CNPJs canônicos de M2."/><div className="panel-table-wrap"><table className="panel-table"><thead><tr><th></th><th>CNPJ</th><th>Cliente</th><th>Cidade</th><th>RCA</th></tr></thead><tbody>{customerRows.map((record,index)=>{const id=text(record.customer_canonical_id)||String(index);return <tr key={id}><td><input type="checkbox" checked={clients.has(id)} onChange={()=>toggle(setClients,id)}/></td><td>{text(record.cnpj)||'—'}</td><td>{text(record.trade_name||record.customer_name)||'—'}</td><td>{text(record.city)||'—'}</td><td>{text(record.rca_name)||'—'}</td></tr>})}</tbody></table></div><button className="panel-button" disabled={!products.size||!clients.size} onClick={exportCombo}>EXPORTAR COMBO CSV</button></PanelCard>
  </div></PanelPage>;
}
