import { useMemo, useState, type ReactNode } from 'react';
import type { CanonicalList } from '../canonical/types';
import { matchesProductSearch } from '../canonical/productSearch';
import { ASSORTMENT_RANGES, matchesAssortmentRanges } from '../canonical/assortment';
import { buildStockOverviewModel, type StockProductItem } from '../canonical/stockOverviewModel';
import { PanelCard, PanelEmptyState, PanelInfoRow, PanelPage, PanelSectionHeader } from '../ui/pattern/PanelVisual';
import './ProductCatalogPage.css';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const qty = new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 0 });
const boxes = new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 0 });
const date = (v: unknown) => /^\d{4}-\d{2}-\d{2}$/.test(String(v ?? '')) ? String(v).split('-').reverse().join('/') : '—';

export type ProductCatalogItem = StockProductItem;

const stockVolume = (units: number, unitsPerCase: number | null) => unitsPerCase ? `${boxes.format(Math.floor(units / unitsPerCase))} cx. · ${qty.format(units)} un.` : `${qty.format(units)} un. · Un/CX ausente`;

export function buildProductCatalog(m1: CanonicalList, m3: CanonicalList, m4?: CanonicalList): ProductCatalogItem[] {
  const emptyM4: CanonicalList = { ...m3, id: 'M4_HISTORICO_TRANSICAO', records: [], sources: [] };
  return buildStockOverviewModel({ m1, m3, m4: m4 ?? emptyM4 }).products;
}

function Cell({ label, children, className = '' }: { label: string; children: ReactNode; className?: string }) { return <div className={`product-cell ${className}`}><span>{label}</span><strong>{children}</strong></div>; }
function PriceCell({ item }: { item: ProductCatalogItem }) { return <div className="product-cell product-price-cell"><span>Preços de tabela</span><div><small>Sem ST<strong>{item.priceWithoutSt === null ? '—' : money.format(item.priceWithoutSt)}</strong></small><small>ST<strong>{item.stValue === null ? '—' : money.format(item.stValue)}</strong></small><small>Com ST<strong>{item.priceWithSt === null ? '—' : money.format(item.priceWithSt)}</strong></small></div></div>; }
function ProductAssortment({ item }: { item: ProductCatalogItem }) { return <section className="product-assortment"><div><span>SORTIMENTO POR FAIXA</span><strong>Em quais clientes este item deve aparecer</strong><small>A faixa cadastrada no cliente define a disponibilidade para o vendedor.</small></div>{item.assortment.length ? <div className="product-assortment-chips">{item.assortment.map(channel=><span key={channel.field}><strong>{channel.label}</strong><small>{channel.range}</small><em>{channel.classification}</em></span>)}</div> : <p>{item.assortmentMaterialized ? 'Item não recomendado nas faixas 1 a 6.' : 'Sortimento ainda não materializado para este item.'}</p>}</section>; }
export function ProductCatalogPage({ m1, m3, m4, launchesOnly = false }: { m1: CanonicalList; m3: CanonicalList; m4?: CanonicalList; launchesOnly?: boolean }) {
  const [query, setQuery] = useState(''); const [stock, setStock] = useState('all'); const [selectedRanges, setSelectedRanges] = useState<string[]>([]); const [open, setOpen] = useState<string | null>(null);
  const catalog = useMemo(() => buildProductCatalog(m1, m3, m4), [m1, m3, m4]);
  const rows = catalog.filter(item => (!launchesOnly || item.isLaunch) && (stock === 'all' || stock === 'available' && item.available > 0 || stock === 'portfolio' && item.inboundQty > 0 || stock === 'pending' && item.unregistered) && matchesProductSearch(item, query) && matchesAssortmentRanges(item.assortment, selectedRanges));
  const toggleRange = (range: string) => setSelectedRanges(current => current.includes(range) ? current.filter(value => value !== range) : [...current, range]);
  const title = launchesOnly ? 'Lançamentos' : 'Produtos';
  return <PanelPage title={title} metricLabel="ITENS ENCONTRADOS" metricValue={qty.format(rows.length)}><div className="panel-stack product-catalog-stack">
    <PanelCard compact><PanelSectionHeader eyebrow="CATÁLOGO OPERACIONAL" title={launchesOnly ? 'Itens da lista oficial de lançamentos' : 'Todos os itens disponíveis e em Carteira'} description="Volumes em caixas e Un/CX. Códigos e EAN exigem correspondência exata; descrição, marca e sub-brand aceitam busca parcial. Preços vêm da PCTABPR região 11." />
      <div className="product-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto, EAN ou código" aria-label="Buscar produto" /><select value={stock} onChange={e=>setStock(e.target.value)} aria-label="Filtrar situação"><option value="all">Todas as situações</option><option value="available">Com estoque disponível</option><option value="portfolio">Na Carteira</option><option value="pending">Aguarda cadastro</option></select></div>
      <fieldset className="product-range-filter"><legend>Filtrar por sortimento</legend><div><button type="button" className={selectedRanges.length === 0 ? 'is-active' : ''} aria-pressed={selectedRanges.length === 0} onClick={()=>setSelectedRanges([])}>Todas</button>{ASSORTMENT_RANGES.map(range=><button type="button" key={range} className={selectedRanges.includes(range) ? 'is-active' : ''} aria-pressed={selectedRanges.includes(range)} onClick={()=>toggleRange(range)}>{range}</button>)}</div><small>{selectedRanges.length ? `${selectedRanges.length} faixa(s) selecionada(s) · exibindo itens liberados em qualquer uma delas` : 'Exibindo itens de todas as faixas'}</small></fieldset>
    </PanelCard>
    {rows.length ? <div className="product-list">{rows.map(item => <article className="product-row" key={item.id}>
      <button className="product-row-main" type="button" onClick={()=>setOpen(open === item.id ? null : item.id)} aria-expanded={open === item.id}>
        <div className="product-name"><strong>{item.description}</strong><span className={item.isLaunch ? 'product-launch-badge' : ''}>{item.unregistered ? 'Aguarda cadastro · vindo da Carteira' : item.isLaunch ? 'Lançamento' : 'Item cadastrado'}</span><small>{[item.line, item.brand, item.subbrand].filter(Boolean).join(' · ') || 'Classificação não informada'} · Winthor {item.winthor || '—'} · Distribuidor {item.distributor || '—'} · EAN {item.ean || '—'}</small></div>
        <Cell label="Estoque disponível">{stockVolume(item.available, item.unitsPerCase)}</Cell><Cell label="Carteira">{item.inboundQty > 0 ? `${boxes.format(item.inboundQty)} cx.` : '0 cx.'}</Cell><Cell label="Un/CX">{item.unitsPerCase ? qty.format(item.unitsPerCase) : 'Não informado'}</Cell><PriceCell item={item} /><Cell label={`Giro mensal · base ${item.analysisDays} dias`}>{item.sold > 0 && item.unitsPerCase ? `${boxes.format(item.averageMonthlySales / item.unitsPerCase)} cx.` : 'Sem giro'}</Cell><Cell label="Cobertura">{item.coverage === null ? 'Sem giro' : `${Math.round(item.coverage)} dias`}</Cell><span className="product-chevron">⌄</span>
      </button>
      {open === item.id ? <div className="product-details"><ProductAssortment item={item} /><PanelInfoRow label="Estoque físico" value={stockVolume(item.physical, item.unitsPerCase)} /><PanelInfoRow label="Estoque reservado" value={stockVolume(item.reserved, item.unitsPerCase)} /><PanelInfoRow label="Estoque disponível" value={stockVolume(item.available, item.unitsPerCase)} /><PanelInfoRow label={`Giro líquido · base ${item.analysisDays} dias`} value={item.sold > 0 && item.unitsPerCase ? `${boxes.format(item.sold / item.unitsPerCase)} cx. · ${qty.format(item.sold)} un. · média ${boxes.format(item.averageMonthlySales / item.unitsPerCase)} cx./mês · última venda ${date(item.lastSale)}` : `Sem venda líquida positiva nos ${item.analysisDays} dias analisados`} /><PanelInfoRow label="Última entrada registrada" value={date(item.lastReceipt)} /><PanelInfoRow label="Carteira em aberto" value={item.inboundQty > 0 ? `${boxes.format(item.inboundQty)} cx. · ${qty.format(item.inboundUnits)} un. · NF ${item.invoices.join(', ') || 'não informada'}` : '0 cx. em aberto'} /><PanelInfoRow label="Projetado" value={stockVolume(item.projected, item.unitsPerCase)} /><PanelInfoRow label="Linha / marca / sub-brand" value={[item.line, item.brand, item.subbrand].filter(Boolean).join(' · ') || 'Não informado'} /><PanelInfoRow label="Categoria / conteúdo" value={[item.category, item.contents].filter(Boolean).join(' · ') || 'Não informado'} /><PanelInfoRow label="Embalagem" value={item.unitsPerCase ? `${qty.format(item.unitsPerCase)} unidades por caixa` : 'Não informada'} /><PanelInfoRow label="Tabela Colgate (base)" value={item.industryTablePrice === null ? 'Não informado' : money.format(item.industryTablePrice)} /><PanelInfoRow label="Preços PCTABPR região 11" value={`Sem ST ${item.priceWithoutSt === null ? 'Não informado' : money.format(item.priceWithoutSt)} · ST ${item.stValue === null ? 'Não informado' : money.format(item.stValue)} · Com ST ${item.priceWithSt === null ? 'Não informado' : money.format(item.priceWithSt)}`} /><PanelInfoRow label="Atividade" value={item.isLaunch ? 'Lançamento importado' : 'Nenhuma atividade/promoção foi importada'} /></div> : null}
    </article>)}</div> : <PanelEmptyState title={launchesOnly ? 'Lista de lançamentos ainda não materializada' : 'Nenhum item neste filtro'} description={launchesOnly ? 'O build ativo não contém itens da Lista Oficial de Lançamentos. Reprocesse o motor atual; se a fonte não estiver salva, atualize somente a base Lançamentos.' : 'Ajuste a busca ou a situação para ver os itens da fotografia ativa.'} />}
  </div></PanelPage>;
}
