import { useEffect, useMemo, useState } from 'react';
import { loadCandidateList } from '../canonical/candidateLists';
import { buildSellOutViewModel, buildTopNetworksViewModel, type SellOutRow, type SellOutViewModel } from '../canonical/operationalViewModels';
import { exportSellOutExcel, exportSellOutJson, exportTopNetworksExcel, exportTopNetworksJson } from '../canonical/operationalExporters';
import type { CanonicalList } from '../canonical/types';
import { useData } from '../store/DataContext';
import { PanelAlert, PanelCard, PanelEmptyState, PanelKpi, PanelPage, PanelSectionHeader } from '../ui/pattern/PanelVisual';

export const SELL_OUT_TABS = [{ id: 'resumo', label: 'Resumo' }, { id: 'redes', label: 'Redes' }, { id: 'gerencial', label: 'Gerencial' }];
export type SellOutView = (typeof SELL_OUT_TABS)[number]['id'];
const currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const percent = new Intl.NumberFormat('pt-BR', { style: 'percent', maximumFractionDigits: 1 });
const number = new Intl.NumberFormat('pt-BR');
const percentValue = (input: number | null) => input === null ? '—' : percent.format(input);

function Alerts({ model }: { model: SellOutViewModel }) { return <>{model.audits.map(audit => <PanelAlert key={audit.code} tone="warning"><strong>{audit.code}</strong> — {audit.message} {audit.action}</PanelAlert>)}</>; }

function Summary({ model }: { model: SellOutViewModel }) { return <>
  <div className="panel-grid panel-grid-auto"><PanelKpi label="Faturado" value={currency.format(model.totals.invoiced)} tone="green" detail="SALE · status FATURADO" /><PanelKpi label="A faturar" value={currency.format(model.totals.toInvoice)} tone="amber" detail="SALE · status A FATURAR" /><PanelKpi label="Sell Out" value={currency.format(model.totals.realized)} tone="blue" detail={`${model.sourceFacts.sales} fatos SALE`} /><PanelKpi label="Meta de vendas" value={currency.format(model.totals.salesTarget)} tone="purple" detail={`Atingimento ${percentValue(model.totals.salesAchievement)}`} /><PanelKpi label="Clientes positivos" value={number.format(model.totals.positiveCustomers)} detail={`Meta ${number.format(model.totals.positivityTarget)} · ${percentValue(model.totals.positivityAchievement)}`} /><PanelKpi label="Dias com venda" value={number.format(model.totals.daysWithSales)} detail="Calendário dos fatos SALE" /></div>
  <PanelCard><PanelSectionHeader eyebrow="RESUMO DO PERÍODO" title="Indicadores canônicos" description="Realizado vem exclusivamente de M3/Sale; metas vêm exclusivamente de M3/Target." action={<><button className="panel-button" onClick={() => exportSellOutExcel(model)}>Exportar Excel</button> <button className="panel-button" onClick={() => exportSellOutJson(model)}>Exportar JSON</button></>} /><div className="panel-table-wrap"><table className="panel-table"><thead><tr><th>Indicador</th><th>Valor</th><th>Universo</th></tr></thead><tbody><tr><td>Faturado</td><td>{currency.format(model.totals.invoiced)}</td><td>SALE com status FATURADO</td></tr><tr><td>A faturar</td><td>{currency.format(model.totals.toInvoice)}</td><td>SALE com status A FATURAR</td></tr><tr><td>Total Sell Out</td><td>{currency.format(model.totals.realized)}</td><td>Todos os {number.format(model.sourceFacts.sales)} SALE</td></tr><tr><td>Meta de vendas</td><td>{currency.format(model.totals.salesTarget)}</td><td>{number.format(model.sourceFacts.targets)} TARGET da Bússola</td></tr><tr><td>Positivação</td><td>{number.format(model.totals.positiveCustomers)} clientes</td><td>CNPJ/cliente canônico distinto em SALE</td></tr></tbody></table></div></PanelCard>
  <PanelCard><PanelSectionHeader eyebrow="TENDÊNCIA" title="Faturamento diário" description="Visualização passiva da série já presente no SellOutViewModel." /><div className="panel-table-wrap"><table className="panel-table"><thead><tr><th>Data</th><th>Faturado</th><th>A faturar</th><th>Total</th></tr></thead><tbody>{model.dailyRows.map(row => <tr key={row.date}><td>{row.date}</td><td>{currency.format(row.invoiced)}</td><td>{currency.format(row.toInvoice)}</td><td>{currency.format(row.realized)}</td></tr>)}</tbody></table></div></PanelCard>
  <PanelCard><PanelSectionHeader eyebrow="VENDA POR LINHA" title="Classificação de produto" description="SALE é relacionado somente ao item canônico; pendências permanecem explícitas no total." /><div className="panel-table-wrap"><table className="panel-table"><thead><tr><th>Linha</th><th>Faturado</th><th>A faturar</th><th>Sell Out</th><th>Participação</th><th>Status</th></tr></thead><tbody>{model.salesByLine.map(row => <tr key={row.line}><td>{row.line}</td><td>{currency.format(row.invoiced)}</td><td>{currency.format(row.toInvoice)}</td><td>{currency.format(row.realized)}</td><td>{percent.format(row.share)}</td><td>{row.resolutionStatus}</td></tr>)}</tbody></table></div></PanelCard>
  <PanelCard><PanelSectionHeader eyebrow="ESTOQUE" title="Posição física canônica" description="105 determina estoque físico; preço oficial materializado em M1." /><div className="panel-grid panel-grid-auto"><PanelKpi label="Itens" value={number.format(model.stock?.items ?? 0)} /><PanelKpi label="Unidades físicas" value={number.format(model.stock?.physicalUnits ?? 0)} /><PanelKpi label="Estoque a custo" value={model.stock ? currency.format(model.stock.atCost) : 'Não disponível'} /><PanelKpi label="Estoque a venda" value={model.stock ? currency.format(model.stock.atSale) : 'Não disponível'} /></div></PanelCard>
</>; }

function Networks({ model, m2, m3 }: { model: SellOutViewModel; m2: CanonicalList; m3: CanonicalList }) { const built = buildTopNetworksViewModel({ m2, m3, generatedAt: model.generatedAt }); const networks = { ...built, motorBuildId: model.motorBuildId, stagingManifestHash: model.stagingManifestHash, teamRows: model.vendorRows }; return <>
  <div className="panel-grid panel-grid-auto"><PanelKpi label="Redes com venda" value={number.format(networks.totals.networks)} tone="purple" detail="Somente clientes que pertencem a uma rede" /><PanelKpi label="Clientes vinculados" value={number.format(networks.totals.customers)} detail="CNPJ positivo com rede" /><PanelKpi label="Total nas redes" value={currency.format(networks.totals.realized)} tone="blue" detail="Clientes sem rede ficam naturalmente fora desta visão" /><PanelKpi label="Meta de redes" value="—" detail="Parâmetro manual não estava materializado no backup" /></div>
  <PanelCard><PanelSectionHeader eyebrow="TOP REDES" title="Realizado por rede" description="Rede vem de M2. Cliente sem rede não é erro e não é forçado para nenhuma rede." action={<><button className="panel-button" onClick={() => exportTopNetworksExcel(networks)}>Exportar Excel</button> <button className="panel-button" onClick={() => exportTopNetworksJson(networks)}>Exportar JSON</button></>} /><div className="panel-table-wrap"><table className="panel-table"><thead><tr><th>Rede</th><th>Clientes</th><th>Faturado</th><th>A faturar</th><th>Total</th><th>Participação</th><th>Status</th></tr></thead><tbody>{networks.rows.map(row => <tr key={row.network}><td>{row.network}</td><td>{number.format(row.customers)}</td><td>{currency.format(row.invoiced)}</td><td>{currency.format(row.toInvoice)}</td><td>{currency.format(row.realized)}</td><td>{percent.format(row.share)}</td><td>{row.resolutionStatus}</td></tr>)}</tbody></table></div></PanelCard>
</>; }

function VendorTable({ rows }: { rows: SellOutRow[] }) { return <div className="panel-table-wrap"><table className="panel-table"><thead><tr><th>RCA</th><th>Cód. atual</th><th>Cód. antigo</th><th>Meta</th><th>Faturado</th><th>A faturar</th><th>Total</th><th>Clientes positivos</th><th>Positivação</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr key={row.key}><td>{row.rcaName ?? row.label}</td><td>{row.rcaCurrentCode ?? '—'}</td><td>{row.rcaLegacyCode ?? '—'}</td><td>{currency.format(row.salesTarget)}</td><td>{currency.format(row.invoiced)}</td><td>{currency.format(row.toInvoice)}</td><td>{currency.format(row.realized)}</td><td>{number.format(row.positiveCustomers)}</td><td>{percentValue(row.positivityAchievement)}</td><td>{row.resolutionStatus}</td></tr>)}</tbody></table></div>; }

function Management({ model }: { model: SellOutViewModel }) {
  const [status, setStatus] = useState<'ALL' | 'RESOLVED' | 'UNRESOLVED'>('ALL');
  const [supervisor, setSupervisor] = useState('ALL');
  const supervisors = useMemo(() => [...new Map(model.vendorRows.map(row => { const key = row.supervisorCode ?? row.supervisorName ?? 'SEM_SUPERVISOR'; return [key, { key, code: row.supervisorCode, name: row.supervisorName }]; })).values()].sort((a, b) => (a.name ?? 'ZZZ').localeCompare(b.name ?? 'ZZZ') || (a.code ?? '').localeCompare(b.code ?? '')), [model]);
  const filtered = useMemo(() => model.vendorRows.filter(row => (status === 'ALL' || row.resolutionStatus === status) && (supervisor === 'ALL' || (row.supervisorCode ?? row.supervisorName ?? 'SEM_SUPERVISOR') === supervisor)), [status, supervisor, model]);
  const groups = useMemo(() => {
    const map = new Map<string, { code: string | null; name: string | null; rows: SellOutRow[] }>();
    for (const row of filtered) { const key = row.supervisorCode ?? row.supervisorName ?? 'SEM_SUPERVISOR'; const group = map.get(key) ?? { code: row.supervisorCode, name: row.supervisorName, rows: [] }; group.rows.push(row); map.set(key, group); }
    return [...map.values()].sort((a, b) => (a.name ?? 'ZZZ').localeCompare(b.name ?? 'ZZZ') || (a.code ?? '').localeCompare(b.code ?? ''));
  }, [filtered]);
  return <>
    <PanelCard><PanelSectionHeader eyebrow="GERENCIAL" title="Vendedores separados por supervisor" description="Nome, código RCA atual e código legado vêm do mesmo master NOVOS RCAS usado pelo motor canônico." action={<div style={{display:'flex',gap:12,flexWrap:'wrap'}}><label className="panel-muted">Supervisor <select value={supervisor} onChange={event => setSupervisor(event.target.value)}><option value="ALL">Todos</option>{supervisors.map(item => <option key={item.key} value={item.key}>{item.name ?? 'Sem supervisor'}{item.code ? ` · ${item.code}` : ''}</option>)}</select></label><label className="panel-muted">RCA <select value={status} onChange={event => setStatus(event.target.value as typeof status)}><option value="ALL">Todos</option><option value="RESOLVED">Resolvidos</option><option value="UNRESOLVED">Pendentes</option></select></label></div>} /></PanelCard>
    {groups.map(group => <PanelCard key={group.code ?? group.name ?? 'SEM_SUPERVISOR'}><PanelSectionHeader eyebrow="SUPERVISOR" title={`${group.name ?? 'Sem supervisor'}${group.code ? ` · Cód. ${group.code}` : ''}`} description={`${number.format(group.rows.length)} RCA(s) nesta supervisão`} /><VendorTable rows={group.rows} /></PanelCard>)}
  </>;
}

export function SellOutPage({ view = 'resumo' }: { view?: SellOutView }) {
  const { activeCanonical } = useData(); const [lists, setLists] = useState<{ m1: CanonicalList; m2: CanonicalList; m3: CanonicalList } | null>(null); const [error, setError] = useState('');
  useEffect(() => { if (!activeCanonical) { setLists(null); return; } let live = true; setLists(null); setError(''); Promise.all([loadCandidateList('M1_ITEM_ESTOQUE'), loadCandidateList('M2_CLIENTE_RCA'), loadCandidateList('M3_MOVIMENTO_VENDAS')]).then(([m1, m2, m3]) => { if (live) setLists({ m1, m2, m3 }); }).catch(reason => { if (live) setError(String(reason)); }); return () => { live = false; }; }, [activeCanonical]);
  if (!activeCanonical) return <PanelPage title="Sell Out"><PanelEmptyState variant="page" title="Sem bundle canônico ativo" description="Não existe fallback legado para esta tela." /></PanelPage>;
  if (error) return <PanelPage title="Sell Out"><PanelAlert tone="error">Erro ao carregar o bundle ativo: {error}</PanelAlert></PanelPage>;
  if (!lists) return <PanelPage title="Sell Out"><PanelEmptyState variant="page" title="Carregando bundle canônico" description="Leitura passiva de M2 e M3; nenhum parser ou motor é acionado." /></PanelPage>;
  const baseModel = buildSellOutViewModel(lists);
  const model: SellOutViewModel = { ...baseModel, motorBuildId: activeCanonical.motorBuildId, stagingManifestHash: activeCanonical.stagingManifestHash };
  return <PanelPage title="Sell Out" metricLabel="Build canônico" metricValue={activeCanonical.motorBuildId}><PanelAlert tone="success">BUILD ATIVO: {activeCanonical.motorBuildId}<br />stagingManifestHash: {activeCanonical.stagingManifestHash}</PanelAlert><div className="panel-stack"><Alerts model={model} />{view === 'redes' ? <Networks model={model} m2={lists.m2} m3={lists.m3} /> : view === 'gerencial' ? <Management model={model} /> : <Summary model={model} />}</div></PanelPage>;
}
