import { createWriteStream } from 'node:fs';
import { Zip, ZipDeflate, strToU8 } from 'fflate';

const escape=(x:unknown)=>String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const col=(n:number)=>{let s='';while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s};
const serial=(iso:string)=>Math.floor((Date.parse(`${iso}T00:00:00Z`)-Date.UTC(1899,11,30))/86400000);
const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="3"><numFmt numFmtId="164" formatCode="R$ #,##0.00"/><numFmt numFmtId="165" formatCode="0.00%"/><numFmt numFmtId="166" formatCode="yyyy-mm-dd"/></numFmts><fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="5"><xf xfId="0"/><xf xfId="0" numFmtId="164" applyNumberFormat="1"/><xf xfId="0" numFmtId="165" applyNumberFormat="1"/><xf xfId="0" numFmtId="166" applyNumberFormat="1"/><xf xfId="0" numFmtId="1" applyNumberFormat="1"/></cellXfs></styleSheet>`;
const contentTypes=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`;
const workbook=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="DATA" sheetId="1" r:id="rId1"/><sheet name="METADATA" sheetId="2" r:id="rId2"/></sheets></workbook>`;
const workbookRels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
const rootRels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;
export async function writeCanonicalXlsx(path:string,list:any,schema:Array<{field:string;type:string}>,metadata:Record<string,unknown>){return new Promise<void>((resolve,reject)=>{const out=createWriteStream(path);const zip=new Zip((err,data,final)=>{if(err)reject(err);else out.write(Buffer.from(data),()=>{if(final)out.end(resolve)})});const add=(name:string,body:string)=>{const f=new ZipDeflate(name);zip.add(f);f.push(strToU8(body),true)};add('[Content_Types].xml',contentTypes);add('_rels/.rels',rootRels);add('xl/workbook.xml',workbook);add('xl/_rels/workbook.xml.rels',workbookRels);add('xl/styles.xml',styles);const data=new ZipDeflate('xl/worksheets/sheet1.xml');zip.add(data);data.push(strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" state="frozen"/></sheetView></sheetViews><sheetData><row r="1">'+schema.map((f,i)=>`<c r="${col(i+1)}1" t="inlineStr"><is><t>${escape(f.field)}</t></is></c>`).join('')+'</row>'),false);for(let ri=0;ri<list.records.length;ri++){const row=list.records[ri],r=ri+2;let cells='';for(let ci=0;ci<schema.length;ci++){const f=schema[ci],v=row[f.field];if(v===null||v===undefined||v==='')continue;const ref=`${col(ci+1)}${r}`;if(['TEXT','CODE_TEXT','DOC_TEXT','CNPJ14_TEXT','GTIN_TEXT','ENUM_TEXT'].includes(f.type))cells+=`<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${escape(v)}</t></is></c>`;else if(f.type==='BOOLEAN')cells+=`<c r="${ref}" t="b"><v>${v?1:0}</v></c>`;else if(f.type==='DATE'&&typeof v==='string')cells+=`<c r="${ref}" s="3"><v>${serial(v)}</v></c>`;else {const style=f.type==='CURRENCY_BRL'?1:f.type==='PERCENT_DECIMAL'?2:f.type==='INTEGER'?4:0;cells+=`<c r="${ref}"${style?` s="${style}"`:''}><v>${Number(v)}</v></c>`}}data.push(strToU8(`<row r="${r}">${cells}</row>`),false)}data.push(strToU8('</sheetData><autoFilter ref="A1:'+col(schema.length)+'1"/></worksheet>'),true);const meta=new ZipDeflate('xl/worksheets/sheet2.xml');zip.add(meta);const entries=Object.entries(metadata);meta.push(strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>key</t></is></c><c r="B1" t="inlineStr"><is><t>value</t></is></c></row>'+entries.map(([k,v],i)=>`<row r="${i+2}"><c r="A${i+2}" t="inlineStr"><is><t>${escape(k)}</t></is></c><c r="B${i+2}" t="inlineStr"><is><t>${escape(v)}</t></is></c></row>`).join('')+'</sheetData></worksheet>'),true);zip.end();out.on('error',reject)})}
