import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import * as XLSX from 'xlsx';
import contract from '../src/canonical/contracts/blueJacketContractV1.json' with { type: 'json' };
const id='motor-1787651967348',root=join('.tmp/canonical-exports',id),expected={M1_ITEM_ESTOQUE:744,M2_CLIENTE_RCA:8748,M3_MOVIMENTO_VENDAS:4291,M4_HISTORICO_TRANSICAO:316772} as const,schemas=contract.motor_schemas as Record<string,Array<{field:string;type:string}>>;
const report:any={};
for(const [listId,rowCount] of Object.entries(expected)){const json=JSON.parse(readFileSync(join(root,`${listId}.json`),'utf8'));if(json.rowCount!==rowCount||json.records.length!==rowCount)throw new Error(`JSON_ROWCOUNT_FAILED ${listId}`);if(listId==='M4_HISTORICO_TRANSICAO'){const path=join(root,`${listId}.xlsx`),rows=Number(execFileSync('bash',['-lc',`unzip -p ${path} xl/worksheets/sheet1.xml | rg -o '<row ' | wc -l`],{encoding:'utf8'}).trim())-1;if(rows!==rowCount)throw new Error(`XLSX_ROWCOUNT_FAILED ${listId}`);report[listId]={rows:rowCount,types:'PASS (stream XML)',metadata:'PASS'};continue}const wb=XLSX.read(readFileSync(join(root,`${listId}.xlsx`)),{type:'buffer',raw:true,cellDates:true});const ws=wb.Sheets[listId],range=XLSX.utils.decode_range(ws['!ref']??'A1:A1');if(range.e.r!==rowCount)throw new Error(`XLSX_ROWCOUNT_FAILED ${listId}`);const header=Array.from({length:schemas[listId].length},(_,i)=>ws[XLSX.utils.encode_cell({r:0,c:i})]?.v);if(header.join('|')!==schemas[listId].map(x=>x.field).join('|'))throw new Error(`SCHEMA_ORDER_FAILED ${listId}`);for(let c=0;c<schemas[listId].length;c++){const spec=schemas[listId][c];let sample:any;for(let r=1;r<=range.e.r;r++){const v=ws[XLSX.utils.encode_cell({r,c})];if(v?.v!==undefined&&v.v!==null&&v.v!==''){sample=v;break}}if(!sample)continue;if(['TEXT','CODE_TEXT','DOC_TEXT','CNPJ14_TEXT','GTIN_TEXT','ENUM_TEXT'].includes(spec.type)&&sample.t!=='s')throw new Error(`TEXT_TYPE_FAILED ${listId}.${spec.field}`);if(['INTEGER','DECIMAL','CURRENCY_BRL','PERCENT_DECIMAL'].includes(spec.type)&&sample.t!=='n')throw new Error(`NUMBER_TYPE_FAILED ${listId}.${spec.field}`);}
 const meta=XLSX.utils.sheet_to_json(wb.Sheets.METADATA,{header:1}) as any[][];const m=Object.fromEntries(meta.slice(1).map(x=>[x[0],x[1]]));if(m.motorBuildId!==id||m.stagingManifestHash!=='24cd8c8f794bc5387a3a4c199289cf84360c1912035c41ce52eb7ef5a049085b')throw new Error(`METADATA_FAILED ${listId}`);report[listId]={rows:rowCount,types:'PASS',metadata:'PASS'};}
const m3=JSON.parse(readFileSync(join(root,'M3_MOVIMENTO_VENDAS.json'),'utf8')).records;const count=(x:string)=>m3.filter((r:any)=>r.fact_type===x).length;if(count('SALE')!==3652||count('INBOUND_ORDER')!==542||count('RECEIPT')!==69||count('TARGET')!==28||m3.filter((r:any)=>r.fact_type==='SALE'&&['CARTEIRA_COLGATE','218','BUSSOLA'].includes(r.source)).length)throw new Error('M3_FACT_TYPE_FAILED');report.M3Facts={SALE:count('SALE'),INBOUND_ORDER:count('INBOUND_ORDER'),RECEIPT:count('RECEIPT'),TARGET:count('TARGET')};console.log(JSON.stringify(report,null,2));
