import type { CanonicalClientResult, CanonicalCoordinatorResult, CanonicalDailyMovement, CanonicalHistorySummary, CanonicalInventoryProduct, CanonicalLineResult, CanonicalNetworkResult, CanonicalNetworkStore, CanonicalSellOutSummary, CanonicalState, CanonicalStockSummary, CanonicalVendorResult, LineName, ManualConfiguration } from '../../domain/canonical';
import type { InboundOrderFactRecord, ItemMasterRecord, SalesFactRecord, UnifiedDataLayer } from '../../domain/unified';
import { classifyLine, normalizeText } from '../canonical/utils';

const ratio=(value:number,target:number)=>target>0?value/target:0;
const gap=(target:number,value:number)=>Math.max(target-value,0);
const sum=<T>(rows:T[],value:(row:T)=>number)=>rows.reduce((total,row)=>total+(Number(value(row))||0),0);
const distinct=(values:string[])=>new Set(values.filter(Boolean)).size;

export interface UnifiedCalculationSummary { invoiced:number; toInvoice:number; sellOut:number; invoicedPositivation:number; totalPositivation:number; industryTarget:number; industryPositivityTarget:number; assignedTarget:number; unassignedTarget:number; }

export function calculateUnifiedSummary(unified:UnifiedDataLayer):UnifiedCalculationSummary {
  const invoicedRows=unified.salesFacts.filter(row=>row.salesStatus==='FATURADO');const toInvoiceRows=unified.salesFacts.filter(row=>row.salesStatus==='A FATURAR');const industryTarget=sum(unified.targets,row=>row.salesTarget);const industryPositivityTarget=sum(unified.targets,row=>row.positivityTarget);const assignedTarget=sum(unified.targets.filter(row=>row.assignmentStatus==='RESOLVED'),row=>row.salesTarget);
  return{invoiced:sum(invoicedRows,row=>row.value),toInvoice:sum(toInvoiceRows,row=>row.value),sellOut:sum(unified.salesFacts,row=>row.value),invoicedPositivation:distinct(invoicedRows.map(row=>row.cnpj)),totalPositivation:distinct(unified.salesFacts.map(row=>row.cnpj)),industryTarget,industryPositivityTarget,assignedTarget,unassignedTarget:Math.max(industryTarget-assignedTarget,0)};
}

function vendorPositivity(rows:SalesFactRecord[]){const invoiced=new Set(rows.filter(row=>row.salesStatus==='FATURADO').map(row=>row.cnpj).filter(Boolean));const total=new Set(rows.map(row=>row.cnpj).filter(Boolean));let future=0;total.forEach(cnpj=>{if(!invoiced.has(cnpj))future+=1});return{invoiced:invoiced.size,total:total.size,future};}

function buildVendors(unified:UnifiedDataLayer,base:CanonicalState):CanonicalVendorResult[]{
  const targetsByRca=new Map<string,{sales:number;positivity:number}>();unified.targets.filter(row=>row.rcaCanonicalId).forEach(row=>{const current=targetsByRca.get(row.rcaCanonicalId)||{sales:0,positivity:0};current.sales+=row.salesTarget;current.positivity+=row.positivityTarget;targetsByRca.set(row.rcaCanonicalId,current)});
  const salesByRca=new Map<string,SalesFactRecord[]>();unified.salesFacts.filter(row=>row.rcaCanonicalId).forEach(row=>{const current=salesByRca.get(row.rcaCanonicalId)||[];current.push(row);salesByRca.set(row.rcaCanonicalId,current)});const businessTotal=Math.max(base.sellOut.businessDaysTotal,0),elapsed=Math.max(base.sellOut.businessDaysElapsed,0),remaining=Math.max(base.sellOut.businessDaysRemaining,0);
  return unified.rcas.filter(rca=>rca.isColgate).map(rca=>{const rows=salesByRca.get(rca.rcaCanonicalId)||[],target=targetsByRca.get(rca.rcaCanonicalId)||{sales:0,positivity:0};const invoiced=sum(rows.filter(row=>row.salesStatus==='FATURADO'),row=>row.value),total=sum(rows,row=>row.value),toInvoice=total-invoiced,pos=vendorPositivity(rows);const idealSalesToday=businessTotal>0?target.sales*(elapsed/businessTotal):0,idealPositivityToday=businessTotal>0?target.positivity*(elapsed/businessTotal):0;return{newCode:rca.currentRcaCode,oldCode:rca.legacyRcaCode,name:rca.rcaName,coordinatorCode:rca.coordinatorCode,coordinatorName:rca.coordinatorName,salesTarget:target.sales,positivityTarget:target.positivity,invoiced,toInvoice,total,attainment:ratio(total,target.sales),invoicedPositivation:pos.invoiced,futurePositivation:pos.future,totalPositivation:pos.total,positivityAttainment:ratio(pos.total,target.positivity),idealSalesToday,salesGapToIdeal:gap(idealSalesToday,total),salesGapToTarget:gap(target.sales,total),idealPositivationToday:idealPositivityToday,positivityGapToIdeal:gap(idealPositivityToday,pos.total),positivityGapToTarget:gap(target.positivity,pos.total),positivityDailyTarget:remaining>0?gap(target.positivity,pos.total)/remaining:gap(target.positivity,pos.total)}});
}

function buildCoordinators(vendors:CanonicalVendorResult[]):CanonicalCoordinatorResult[]{const grouped=new Map<string,CanonicalVendorResult[]>();vendors.forEach(vendor=>{const key=vendor.coordinatorCode||vendor.coordinatorName||'SEM_COORDENADOR';const rows=grouped.get(key)||[];rows.push(vendor);grouped.set(key,rows)});return Array.from(grouped.entries()).map(([code,rows])=>({code,name:rows[0]?.coordinatorName||code,salesTarget:sum(rows,row=>row.salesTarget),positivityTarget:sum(rows,row=>row.positivityTarget),invoiced:sum(rows,row=>row.invoiced),toInvoice:sum(rows,row=>row.toInvoice),total:sum(rows,row=>row.total),attainment:ratio(sum(rows,row=>row.total),sum(rows,row=>row.salesTarget)),invoicedPositivation:sum(rows,row=>row.invoicedPositivation),futurePositivation:sum(rows,row=>row.futurePositivation),totalPositivation:sum(rows,row=>row.totalPositivation),positivityAttainment:ratio(sum(rows,row=>row.totalPositivation),sum(rows,row=>row.positivityTarget)),vendors:rows}));}

function buildClients(unified:UnifiedDataLayer):CanonicalClientResult[]{const grouped=new Map<string,SalesFactRecord[]>();unified.salesFacts.filter(row=>row.cnpj).forEach(row=>{const rows=grouped.get(row.cnpj)||[];rows.push(row);grouped.set(row.cnpj,rows)});const customerByCnpj=new Map(unified.customers.map(row=>[row.cnpj,row]));const latestClass=new Map<string,string>();unified.customerClassifications.forEach(row=>{if(row.premiseNetwork)latestClass.set(row.cnpj,row.premiseNetwork)});return Array.from(grouped.entries()).map(([cnpj,rows])=>({cnpj,name:customerByCnpj.get(cnpj)?.customerName||'',city:customerByCnpj.get(cnpj)?.city||'',network:latestClass.get(cnpj)||'',invoiced:sum(rows.filter(row=>row.salesStatus==='FATURADO'),row=>row.value),toInvoice:sum(rows.filter(row=>row.salesStatus==='A FATURAR'),row=>row.value),total:sum(rows,row=>row.value)}));}
function buildDaily(unified:UnifiedDataLayer):CanonicalDailyMovement[]{const grouped=new Map<string,SalesFactRecord[]>();unified.salesFacts.forEach(row=>{const rows=grouped.get(row.movementDate)||[];rows.push(row);grouped.set(row.movementDate,rows)});return Array.from(grouped.entries()).map(([date,rows])=>{const invoicedRows=rows.filter(row=>row.salesStatus==='FATURADO');return{date,invoiced:sum(invoicedRows,row=>row.value),toInvoice:sum(rows.filter(row=>row.salesStatus==='A FATURAR'),row=>row.value),total:sum(rows,row=>row.value),invoicedPositivation:distinct(invoicedRows.map(row=>row.cnpj)),totalPositivation:distinct(rows.map(row=>row.cnpj))}}).sort((a,b)=>a.date.localeCompare(b.date));}

function monthKey(date:string){return date.slice(0,7)}
function shiftMonth(key:string,delta:number){const[y,m]=key.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+delta,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`}
function buildHistory(unified:UnifiedDataLayer,referenceDate:string):CanonicalHistorySummary{const grouped=new Map<string,{grossSales:number;returns:number;value:number}>();unified.historicalSalesFacts.filter(row=>row.movementClass!=='OTHER').forEach(row=>{const key=monthKey(row.movementDate);const current=grouped.get(key)||{grossSales:0,returns:0,value:0};if(row.movementClass==='SALE')current.grossSales+=row.valueRaw;else current.returns+=row.valueRaw;current.value+=row.signedValue;grouped.set(key,current)});const months=Array.from(grouped.entries()).map(([key,row])=>({key,year:Number(key.slice(0,4)),month:Number(key.slice(5,7)),value:row.value,grossSales:row.grossSales,returns:row.returns})).sort((a,b)=>a.key.localeCompare(b.key));const currentKey=referenceDate.slice(0,7),lastYear=`${Number(currentKey.slice(0,4))-1}-${currentKey.slice(5,7)}`,averageKeys=[shiftMonth(currentKey,-3),shiftMonth(currentKey,-2),shiftMonth(currentKey,-1)];const values=averageKeys.map(key=>grouped.get(key)?.value).filter((value):value is number=>typeof value==='number');return{months,sameMonthLastYear:grouped.get(lastYear)?.value??null,sameMonthLastYearKey:lastYear,average3ClosedMonths:values.length===3?values.reduce((a,b)=>a+b,0)/3:null,average3MonthKeys:averageKeys};}

function itemLine(item:ItemMasterRecord):LineName|''{return classifyLine(item.internalDescription||item.industryDescription,item.manufacturerCode||item.industrySku)}
function buildLines(unified:UnifiedDataLayer,sellOutTarget:number,config:ManualConfiguration):CanonicalLineResult[]{const itemById=new Map(unified.items.map(item=>[item.itemCanonicalId,item]));const totals=new Map<LineName,number>();unified.salesFacts.forEach(row=>{const item=itemById.get(row.itemCanonicalId);if(!item)return;const line=itemLine(item);if(!line)return;totals.set(line,(totals.get(line)||0)+row.value)});return(Object.keys(config.lineShares) as LineName[]).map(name=>{const share=config.lineShares[name]||0,target=sellOutTarget*share,total=totals.get(name)||0;const invoiced=unified.salesFacts.filter(row=>{if(row.salesStatus!=='FATURADO')return false;const item=itemById.get(row.itemCanonicalId);return Boolean(item&&itemLine(item)===name)}).reduce((s,row)=>s+row.value,0);return{name,share,target,invoiced,toInvoice:total-invoiced,total,attainment:ratio(total,target)}});}

function openInbound(row:InboundOrderFactRecord){return row.inboundStatus!=='RECEIVED_BY_MILENIO'}
export function buildInventoryFromUnified(unified:UnifiedDataLayer,referenceDate:string,config:ManualConfiguration):{inventory:CanonicalInventoryProduct[];stock:CanonicalStockSummary}{const inboundByItem=new Map<string,InboundOrderFactRecord[]>();unified.inboundOrders.filter(openInbound).forEach(row=>{const rows=inboundByItem.get(row.itemCanonicalId)||[];rows.push(row);inboundByItem.set(row.itemCanonicalId,rows)});const inventory=unified.items.map(item=>{const inbound=inboundByItem.get(item.itemCanonicalId)||[];let pendingQty=0,pendingCases=0,pendingCost=0,pendingSale=0;inbound.forEach(row=>{const factor=item.industryUnitsPerCase||0;const remaining=row.remainingInTransitUnits??row.pipelineUnits;const hasUnits=remaining!==null;const units=hasUnits?Math.max(remaining||0,0):0;const cases=hasUnits&&factor>0?units/factor:Math.max(row.pipelineQtyCases,0);const fraction=hasUnits&&row.pipelineUnits&&row.pipelineUnits>0?Math.min(Math.max(units/row.pipelineUnits,0),1):1;pendingQty+=units;pendingCases+=cases;pendingCost+=Math.max(row.netValue,0)*fraction;pendingSale+=hasUnits&&units>0&&item.salePricePvenDa1!==null?units*item.salePricePvenDa1:Math.max(row.netValue,0)*fraction*(1+Math.max(config.portfolioSaleMarkup,0))});return{code:item.winthorCode||item.itemCanonicalId,description:item.internalDescription||item.industryDescription,ean:item.internalEan||item.industryEan,quantity:item.physicalStockUnits,costUnit:item.costUnit105,saleUnit:item.salePricePvenDa1??0,pendingQty,pendingCases,pendingCost,pendingSale,isLaunch:item.isLaunch,hasWinthor:item.hasWinthor,factoryCode:item.manufacturerCode||item.industrySku,physicalCases:item.physicalCases8013,physicalUnits:item.physicalStockUnits,grossKg:item.grossKg8013} as CanonicalInventoryProduct});const costValue=sum(inventory,row=>row.quantity*row.costUnit),saleValue=sum(inventory,row=>row.quantity*row.saleUnit),pendingPurchaseCost=sum(inventory,row=>row.pendingCost),pendingPurchaseSale=sum(inventory,row=>row.pendingSale);const history=buildHistory(unified,referenceDate),average=Math.max(history.average3ClosedMonths||0,0);const coverageCurrentDays=average>0?Math.round(saleValue/average*30):0,coverageProjectedDays=average>0?Math.round((saleValue+pendingPurchaseSale)/average*30):0,coverageCostCurrentDays=average>0?Math.round(costValue/average*30):0,coverageCostProjectedDays=average>0?Math.round((costValue+pendingPurchaseCost)/average*30):0;return{inventory,stock:{costValue,saleValue,pendingPurchaseCost,pendingPurchaseSale,projectedCostValue:costValue+pendingPurchaseCost,projectedSaleValue:saleValue+pendingPurchaseSale,physicalUnits:sum(inventory,row=>row.quantity),physicalCases:sum(inventory,row=>row.physicalCases||0),grossKg:sum(inventory,row=>row.grossKg||0),coverageCurrentDays,coverageProjectedDays,coverageCostCurrentDays,coverageCostProjectedDays,coverageTargetDays:config.coverageTargetDays}};}

function buildNetworks(unified:UnifiedDataLayer,config:ManualConfiguration):CanonicalNetworkResult[]{const latest=new Map<string,string>();unified.customerClassifications.forEach(row=>{if(row.premiseNetwork)latest.set(row.cnpj,row.premiseNetwork)});const salesByCnpj=new Map<string,SalesFactRecord[]>();unified.salesFacts.forEach(row=>{if(!row.cnpj)return;const rows=salesByCnpj.get(row.cnpj)||[];rows.push(row);salesByCnpj.set(row.cnpj,rows)});const topsByNetwork=new Map<string,typeof unified.topRetailerSnapshots>();unified.topRetailerSnapshots.forEach(row=>{const key=row.topRetailerNetwork||'SEM_REDE_TOP';const rows=topsByNetwork.get(key)||[];rows.push(row);topsByNetwork.set(key,rows)});const networks=new Map<string,string[]>();latest.forEach((network,cnpj)=>{const rows=networks.get(network)||[];rows.push(cnpj);networks.set(network,rows)});return Array.from(networks.entries()).map(([name,cnpjs])=>{const rows=cnpjs.flatMap(cnpj=>salesByCnpj.get(cnpj)||[]),invoiced=sum(rows.filter(row=>row.salesStatus==='FATURADO'),row=>row.value),total=sum(rows,row=>row.value),key=normalizeText(name)||name,target=Math.max(config.networkTargets[key]??config.networkTargets[name]??0,0),topRows=topsByNetwork.get(name)||[],topTarget=sum(topRows,row=>row.target);const stores:CanonicalNetworkStore[]=topRows.map(store=>{const storeSales=salesByCnpj.get(store.cnpj)||[],storeInvoiced=sum(storeSales.filter(row=>row.salesStatus==='FATURADO'),row=>row.value);return{cnpj:store.cnpj,name:store.storeName,fantasyName:store.topTradeName,city:store.topCity,managerCnpj:store.managerCnpj,groupingCode:store.groupCode,tier:store.topCategory,storeType:store.storeType,topTarget:store.target,invoiced:storeInvoiced,toInvoice:sum(storeSales,row=>row.value)-storeInvoiced,total:sum(storeSales,row=>row.value)}});return{key,name,teamCode:'',vendorCode:'',detectedNetworkTarget:0,networkTarget:target,topTarget,invoiced,toInvoice:total-invoiced,total,networkAttainment:ratio(total,target),topAttainment:ratio(total,topTarget),gapToNetworkTarget:gap(target,total),gapToTopTarget:gap(topTarget,total),clients:cnpjs.length,stores}});}

function toTransactions(unified:UnifiedDataLayer):CanonicalState['transactions']{const itemById=new Map(unified.items.map(item=>[item.itemCanonicalId,item])),customerByCnpj=new Map(unified.customers.map(row=>[row.cnpj,row])),rcaById=new Map(unified.rcas.map(row=>[row.rcaCanonicalId,row]));return unified.salesFacts.map(row=>{const item=itemById.get(row.itemCanonicalId),customer=customerByCnpj.get(row.cnpj),rca=rcaById.get(row.rcaCanonicalId);return{date:row.movementDate,status:row.salesStatus,clientCode:row.winthorCustomerCode,clientName:customer?.customerName||'',cnpj:row.cnpj,city:customer?.city||'',vendorCode:rca?.currentRcaCode||row.transactionRcaCode,vendorName:rca?.rcaName||'',supervisorCode:rca?.coordinatorCode||'',supervisorName:rca?.coordinatorName||'',manufacturerCode:item?.manufacturerCode||row.industrySku,ean:item?.internalEan||item?.industryEan||'',internalProductCode:item?.winthorCode||row.winthorProductCode,productDescription:item?.internalDescription||item?.industryDescription||'',cases:row.cases,units:row.units,value:row.value,saleType:row.saleType,line:item?itemLine(item):''}});}

export function projectCanonicalFromUnified(base:CanonicalState,unified:UnifiedDataLayer,config:ManualConfiguration):CanonicalState {const summary=calculateUnifiedSummary(unified),sellOutTarget=config.sellOutTarget>0?config.sellOutTarget:base.sellOut.sellOutTarget,remaining=Math.max(base.sellOut.businessDaysRemaining,0),elapsed=Math.max(base.sellOut.businessDaysElapsed,0),totalDays=Math.max(base.sellOut.businessDaysTotal,0),actualTotal=summary.sellOut;const sellOut:CanonicalSellOutSummary={...base.sellOut,invoiced:summary.invoiced,toInvoice:summary.toInvoice,total:actualTotal,sellOutTarget,attainment:ratio(actualTotal,sellOutTarget),invoicedPositivation:summary.invoicedPositivation,futurePositivation:Math.max(summary.totalPositivation-summary.invoicedPositivation,0),totalPositivation:summary.totalPositivation,industryPositivityTarget:summary.industryPositivityTarget,positivityAttainment:ratio(summary.totalPositivation,summary.industryPositivityTarget),ticketAverage:summary.totalPositivation>0?actualTotal/summary.totalPositivation:0,invoicedDailyAverage:elapsed>0?summary.invoiced/elapsed:0,totalDailyAverage:elapsed>0?actualTotal/elapsed:0,neededDailyAverage:remaining>0?gap(sellOutTarget,actualTotal)/remaining:gap(sellOutTarget,actualTotal),invoicedTrend:elapsed>0?summary.invoiced/elapsed*totalDays:0,totalTrend:elapsed>0?actualTotal/elapsed*totalDays:0};const vendors=buildVendors(unified,base),coordinators=buildCoordinators(vendors),history=buildHistory(unified,base.referenceDate),inventoryProjection=buildInventoryFromUnified(unified,base.referenceDate,config);const warnings=[...base.warnings.filter(w=>!w.startsWith('Motor unificado:'))];if(unified.qualityIssues.length)warnings.push(`Motor unificado: ${unified.qualityIssues.filter(i=>i.severity==='ERROR').length} erro(s), ${unified.qualityIssues.filter(i=>i.severity==='WARNING').length} alerta(s) e ${unified.qualityIssues.filter(i=>i.severity==='INFO').length} informação(ões) de qualidade; fatos não resolvidos foram preservados.`);return{...base,transactions:toTransactions(unified),inventory:inventoryProjection.inventory,daily:buildDaily(unified),history,industryTarget:summary.industryTarget,industryPositivityTarget:summary.industryPositivityTarget,sellOut,stock:inventoryProjection.stock,vendors,coordinators,clients:buildClients(unified),networks:buildNetworks(unified,config),lines:buildLines(unified,sellOutTarget,config),warnings};}
