import type * as XLSX from 'xlsx';
import type { DataQualityIssue, InboundOrderFactRecord, ItemMasterRecord, ReceiptHeaderRecord, ReceiptItemRecord, RcaMasterRecord, SalesFactRecord, TargetFactRecord } from '../../domain/unified';
import type { OperationalSourceState } from '../operationalSources';
import type { Row } from '../canonical/runtime';
import { cleanCode, cleanDigits, normalizeCnpj, normalizeText, parseNumber, toIsoDate } from '../canonical/utils';
import { parseCompassTargets } from '../canonical/support';
import { parseInvoiceIdentity } from '../../domain/invoiceIdentity';

const validCnpj=(v:string)=>/^\d{14}$/.test(v);
const headerMap=(r:Row)=>new Map(r.map((v,i)=>[normalizeText(v),i]).filter(([k])=>Boolean(k)) as Array<[string,number]>);
const idx=(m:Map<string,number>,...names:string[])=>{for(const n of names){const v=m.get(normalizeText(n));if(v!==undefined)return v}return-1};
const cell=(r:Row,i:number)=>i>=0?r[i]:'';

export interface SalesMotorResult { salesFacts:SalesFactRecord[]; inboundOrders:InboundOrderFactRecord[]; receiptHeaders:ReceiptHeaderRecord[]; receiptItems:ReceiptItemRecord[]; targets:TargetFactRecord[]; qualityIssues:DataQualityIssue[]; }

function itemIndexes(items:ItemMasterRecord[]){return{byWinthor:new Map(items.filter(i=>i.winthorCode&&i.hasWinthor).map(i=>[i.winthorCode,i])),bySku:new Map(items.filter(i=>i.industrySku).map(i=>[i.industrySku,i])),byEan:new Map(items.flatMap(i=>[i.internalEan,i.industryEan].filter(Boolean).map(e=>[cleanDigits(e),i] as const)))};}

export function parseSales8022(rows:Row[],items:ItemMasterRecord[],rcas:RcaMasterRecord[]){
  const facts:SalesFactRecord[]=[];const qualityIssues:DataQualityIssue[]=[];if(!rows.length)return{facts,qualityIssues};
  const hi=rows.findIndex(r=>{const v=r.map(normalizeText);return v.includes('DATA MOVIMENTO')&&v.includes('STATUS PEDIDO')&&v.includes('VALOR R$ NF')});
  if(hi<0)return{facts,qualityIssues:[{id:'8022_SCHEMA',domain:'SALES',severity:'ERROR',code:'SALES_8022_SCHEMA_NOT_RECOGNIZED',message:'8022 sem cabeçalho transacional esperado.',source:'8022'} as DataQualityIssue]};
  const h=headerMap(rows[hi]);const ix=itemIndexes(items);const rcaByCurrent=new Map(rcas.map(r=>[r.currentRcaCode,r]));
  for(let i=hi+1;i<rows.length;i++){
    const r=rows[i];const status=normalizeText(cell(r,idx(h,'STATUS PEDIDO')));if(status!=='FATURADO'&&status!=='A FATURAR')continue;const saleType=normalizeText(cell(r,idx(h,'TIPO VENDA')));if(saleType&&saleType!=='VENDA')continue;const value=parseNumber(cell(r,idx(h,'VALOR R$ NF')));if(!value)continue;
    const rawCnpj=String(cell(r,idx(h,'CNPJ/CPF CLIENTE'))??'').trim();const nc=normalizeCnpj(rawCnpj,{declaredCnpj:rawCnpj.replace(/\D/g,'').length>=12});const cnpj=validCnpj(nc.canonical)?nc.canonical:'';const seller=cleanCode(cell(r,idx(h,'COD. VENDEDOR')));const rca=rcaByCurrent.get(seller);const winthor=cleanCode(cell(r,idx(h,'CODPROD. WINTHOR')));const sku=cleanCode(cell(r,idx(h,'CODIGO FABRICANTE')));const ean=cleanDigits(cell(r,idx(h,'EAN PRODUTO'))||cell(r,idx(h,'EAN CADASTRO')));const item=ix.byWinthor.get(winthor)||ix.bySku.get(sku)||ix.byEan.get(ean);const date=toIsoDate(cell(r,idx(h,'DATA MOVIMENTO')));
    facts.push({salesFactId:`8022:${date}:${cleanCode(cell(r,idx(h,'NUMERO PED. WINTHOR')))}:${winthor}:${i}`,movementDate:date,customerCanonicalId:cnpj?`CNPJ:${cnpj}`:'',winthorCustomerCode:cleanCode(cell(r,idx(h,'COD. CLIENTE'))),cnpj,rcaCanonicalId:rca?.rcaCanonicalId||'',transactionRcaCode:seller,rcaAssignmentStatus:rca?'RESOLVED':seller?'NON_COLGATE':'UNRESOLVED',itemCanonicalId:item?.itemCanonicalId||'',winthorProductCode:winthor,industrySku:sku,orderWinthor:cleanCode(cell(r,idx(h,'NUMERO PED. WINTHOR'))),orderRca:cleanCode(cell(r,idx(h,'NUMERO PED. RCA'))),invoiceNumber:cleanCode(cell(r,idx(h,'NUMERO NOTA FISCAL'))),invoiceDate:toIsoDate(cell(r,idx(h,'DATA EMISSAO NF'))),rawOrderStatus:String(cell(r,idx(h,'STATUS PEDIDO'))??'').trim(),rawBlockStatus:String(cell(r,idx(h,'STATUS BLOQUEIO'))??'').trim(),salesStatus:status as SalesFactRecord['salesStatus'],units:parseNumber(cell(r,idx(h,'UNIDADES VENDIDAS'))),cases:parseNumber(cell(r,idx(h,'CAIXAS VENDIDAS'))),grossWeightKg:parseNumber(cell(r,idx(h,'PESO BRUTO KG'))),netWeightKg:parseNumber(cell(r,idx(h,'PESO LIQUIDO KG'))),weightTons:parseNumber(cell(r,idx(h,'PESO T'))),value,saleType:String(cell(r,idx(h,'TIPO VENDA'))??'').trim(),line:'',source:'8022'});
    if(!cnpj)qualityIssues.push({id:`8022_CNPJ:${i}`,domain:'SALES',severity:'WARNING',code:'SALES_CUSTOMER_UNRESOLVED',message:'Venda preservada sem CNPJ canônico; não conta em positivação.',source:'8022',entityKey:rawCnpj});
    if(!item)qualityIssues.push({id:`8022_ITEM:${i}`,domain:'SALES',severity:'WARNING',code:'SALES_ITEM_UNRESOLVED',message:'Venda preservada sem ITEM_MASTER resolvido.',source:'8022',entityKey:winthor||sku||ean});
    if(seller&&!rca)qualityIssues.push({id:`8022_RCA:${i}`,domain:'RCA',severity:'WARNING',code:'SALES_RCA_NOT_OFFICIAL',message:'Venda preservada, mas o vendedor não está no RCA_MASTER oficial.',source:'8022',entityKey:seller});
  }
  return{facts,qualityIssues};
}

export function buildTargets(workbook:XLSX.WorkBook|null,rcas:RcaMasterRecord[],referenceDate:string){
  const qualityIssues:DataQualityIssue[]=[];if(!workbook)return{targets:[] as TargetFactRecord[],qualityIssues};const byLegacy=new Map(rcas.filter(r=>r.legacyRcaCode).map(r=>[r.legacyRcaCode,r]));const competence=referenceDate.slice(0,7);
  const targets=parseCompassTargets(workbook).map((raw,index)=>{const legacyRcaCode=cleanCode(raw.oldCode);const rca=byLegacy.get(legacyRcaCode);if(!rca)qualityIssues.push({id:`TARGET_RCA:${legacyRcaCode}:${index}`,domain:'TARGET',severity:'WARNING',code:'TARGET_UNASSIGNED_RCA',message:'Meta preservada no total da indústria sem RCA oficial resolvido.',source:'BUSSOLA',entityKey:legacyRcaCode});return{targetFactId:`BUSSOLA:${competence}:${legacyRcaCode}:${index}`,competence,industry:'COLGATE',legacyRcaCode,rcaCanonicalId:rca?.rcaCanonicalId||'',salesTarget:Number(raw.salesTarget)||0,positivityTarget:Number(raw.positivityTarget)||0,assignmentStatus:rca?'RESOLVED':'UNRESOLVED_RCA',source:'BUSSOLA'} as TargetFactRecord});
  return{targets,qualityIssues};
}

export function buildInboundFacts(rows:Row[],items:ItemMasterRecord[],operational:OperationalSourceState){
  const qualityIssues:DataQualityIssue[]=[];const ix=itemIndexes(items);const inboundOrders:InboundOrderFactRecord[]=[];const hi=rows.findIndex(r=>{const v=r.map(normalizeText);return v.includes('ORDER DATE')&&v.includes('MATERIAL')&&v.includes('ORDER QTY')&&v.includes('BILL QTY')});
  const receiptHeaders:ReceiptHeaderRecord[]=operational.currentInvoices.map((n,i)=>({receiptId:`218:${n.invoiceNormalized||n.invoice}:${i}`,receiptDate:n.entryDate,entryTransactionNumber:'',invoiceRaw:n.invoiceRaw||n.invoice,invoiceNormalized:n.invoiceNormalized||n.invoice,entryType:'',series:n.invoiceSeries||'',invoiceIssueDate:n.issueDate,branch:'',supplier:'COLGATE',supplierCnpj:'',uf:'',totalValue:n.totalValue,ipiValue:0,source:'218'}));
  const receiptId=new Map(receiptHeaders.map(h=>[h.invoiceNormalized,h.receiptId]));const receiptItems:ReceiptItemRecord[]=operational.receiptItems.map((r,i)=>{const item=ix.byWinthor.get(cleanCode(r.sku));return{receiptId:receiptId.get(r.invoiceNormalized||r.invoice)||`218:${r.invoiceNormalized||r.invoice}:${i}`,itemCanonicalId:item?.itemCanonicalId||'',winthorProductCode:cleanCode(r.sku),description:r.product,branch:'',pack:'',unit:'UN',receivedUnits:r.units,unitPrice:r.unitPrice,previousFinancialCost:0,currentFinancialCost:0,fiscalCode:'',operationCode:'',inboundMatchStatus:'UNMATCHED'}});
  const received=new Map<string,number>();operational.receiptItems.forEach(r=>{const item=ix.byWinthor.get(cleanCode(r.sku));const key=`${r.invoiceNormalized||r.invoice}|${item?.itemCanonicalId||cleanCode(r.sku)}`;received.set(key,(received.get(key)||0)+r.units)});
  if(hi>=0){const h=headerMap(rows[hi]);for(let i=hi+1;i<rows.length;i++){const r=rows[i];const material=cleanCode(cell(r,idx(h,'Material')));const orderQty=Math.max(parseNumber(cell(r,idx(h,'Order Qty'))),0);const billQty=Math.max(parseNumber(cell(r,idx(h,'Bill Qty'))),0);const netValue=Math.max(parseNumber(cell(r,idx(h,'Net Value ( ZINV )'))),0);if(!material||(orderQty<=0&&billQty<=0&&netValue<=0))continue;const item=ix.bySku.get(material)||ix.byWinthor.get(material);const factor=item?.industryUnitsPerCase||null;const cases=orderQty+billQty;const units=factor?cases*factor:null;const invoiceRaw=String(cell(r,idx(h,'Nota Fiscal Number'))??'').trim();const invoiceNormalized=parseInvoiceIdentity(invoiceRaw).normalized;const receivedUnits=invoiceNormalized?(received.get(`${invoiceNormalized}|${item?.itemCanonicalId||material}`)||0):0;const remaining=units===null?null:Math.max(units-receivedUnits,0);let status:InboundOrderFactRecord['inboundStatus']='OPEN_INBOUND';if(billQty>0&&receivedUnits<=0)status='BILLED_BY_COLGATE_IN_TRANSIT';else if(receivedUnits>0&&units!==null&&receivedUnits<units)status='PARTIALLY_RECEIVED';else if(receivedUnits>0&&units!==null&&receivedUnits>=units)status='RECEIVED_BY_MILENIO';else if(orderQty>0&&billQty===0)status='ORDERED_FROM_COLGATE';inboundOrders.push({inboundFactId:`CARTEIRA:${cleanCode(cell(r,idx(h,'Order Number')))}:${material}:${i}`,orderDate:toIsoDate(cell(r,idx(h,'Order Date'))),colgateCustomerNumber:cleanCode(cell(r,idx(h,'Customer Number'))),orderNumber:cleanCode(cell(r,idx(h,'Order Number'))),itemCanonicalId:item?.itemCanonicalId||'',industrySku:material,orderQtyCases:orderQty,billQtyCases:billQty,pipelineQtyCases:cases,pipelineUnits:units,netValue,invoiceRaw,invoiceNormalized,billingType:String(cell(r,idx(h,'Billing Type'))??'').trim(),billingDate:toIsoDate(cell(r,idx(h,'Billing Date'))),grossWeight:parseNumber(cell(r,idx(h,'Gross Weight'))),receivedUnits,remainingInTransitUnits:remaining,inboundStatus:status,source:'CARTEIRA_COLGATE'});if(!item)qualityIssues.push({id:`INBOUND_ITEM:${i}`,domain:'INBOUND',severity:'WARNING',code:'INBOUND_ITEM_UNRESOLVED',message:'Linha da Carteira preservada sem ITEM_MASTER resolvido.',source:'CARTEIRA_COLGATE',entityKey:material});if(cases>0&&!factor)qualityIssues.push({id:`INBOUND_PACK:${i}`,domain:'INBOUND',severity:'WARNING',code:'INDUSTRIAL_PACK_MISSING',message:'Carteira em caixas preservada sem inventar unidades.',source:'CARTEIRA_COLGATE',entityKey:material})}}
  const byInvoiceItem=new Map(inboundOrders.filter(r=>r.invoiceNormalized).map(r=>[`${r.invoiceNormalized}|${r.itemCanonicalId}`,r]));receiptItems.forEach(r=>{const h=receiptHeaders.find(x=>x.receiptId===r.receiptId);const inbound=h?byInvoiceItem.get(`${h.invoiceNormalized}|${r.itemCanonicalId}`):undefined;if(!inbound){r.inboundMatchStatus='UNMATCHED';return}if(inbound.pipelineUnits===null){r.inboundMatchStatus='MATCHED';return}r.inboundMatchStatus=r.receivedUnits>inbound.pipelineUnits?'OVERAGE':r.receivedUnits<inbound.pipelineUnits?'PARTIAL':'MATCHED'});
  return{inboundOrders,receiptHeaders,receiptItems,qualityIssues};
}

export function runSalesMotor(input:{salesRows:Row[];portfolioRows:Row[];items:ItemMasterRecord[];rcas:RcaMasterRecord[];compassWorkbook:XLSX.WorkBook|null;operational:OperationalSourceState;referenceDate:string}):SalesMotorResult{
  const sales=parseSales8022(input.salesRows,input.items,input.rcas);const inbound=buildInboundFacts(input.portfolioRows,input.items,input.operational);const targets=buildTargets(input.compassWorkbook,input.rcas,input.referenceDate);return{salesFacts:sales.facts,inboundOrders:inbound.inboundOrders,receiptHeaders:inbound.receiptHeaders,receiptItems:inbound.receiptItems,targets:targets.targets,qualityIssues:[...sales.qualityIssues,...inbound.qualityIssues,...targets.qualityIssues]};
}
