import type { CanonicalSupportData } from '../../domain/canonical';
import type {
  DataQualityIssue,
  InboundOrderFactRecord,
  ItemMasterRecord,
  ReceiptHeaderRecord,
  ReceiptItemRecord,
  RcaMasterRecord,
  SalesFactRecord,
  TargetFactRecord,
} from '../../domain/unified';
import type { OperationalSourceState } from '../operationalSources';
import type { Row } from '../canonical/runtime';
import { cleanCode, cleanDigits, normalizeCnpj, normalizeText, parseNumber, toIsoDate } from '../canonical/utils';
import { parseInvoiceIdentity } from '../../domain/invoiceIdentity';

const validCnpj=(value:string)=>/^\d{14}$/.test(value);
const headerMap=(row:Row)=>new Map(row.map((cell,index)=>[normalizeText(cell),index]).filter(([name])=>Boolean(name)) as Array<[string,number]>);
const idx=(map:Map<string,number>,...names:string[])=>{for(const name of names){const found=map.get(normalizeText(name));if(found!==undefined)return found}return-1};
const cell=(row:Row,index:number)=>index>=0?row[index]:'';

export interface SalesMotorResult { salesFacts:SalesFactRecord[]; inboundOrders:InboundOrderFactRecord[]; receiptHeaders:ReceiptHeaderRecord[]; receiptItems:ReceiptItemRecord[]; targets:TargetFactRecord[]; qualityIssues:DataQualityIssue[]; }

function itemIndexes(items:ItemMasterRecord[]){
  return {byWinthor:new Map(items.filter(i=>i.winthorCode).map(i=>[i.winthorCode,i])),bySku:new Map(items.filter(i=>i.industrySku).map(i=>[i.industrySku,i])),byEan:new Map(items.flatMap(i=>[i.internalEan,i.industryEan].filter(Boolean).map(e=>[cleanDigits(e),i] as const)))};
}

export function parseSales8022(rows:Row[],items:ItemMasterRecord[],rcas:RcaMasterRecord[]):{facts:SalesFactRecord[];qualityIssues:DataQualityIssue[]}{
  const facts:SalesFactRecord[]=[];const qualityIssues:DataQualityIssue[]=[];const headerIndex=rows.findIndex(row=>{const v=row.map(normalizeText);return v.includes('DATA MOVIMENTO')&&v.includes('STATUS PEDIDO')&&v.includes('VALOR R$ NF')});if(headerIndex<0)return{facts,qualityIssues:[{id:'8022_SCHEMA',domain:'SALES',severity:'ERROR',code:'SALES_8022_SCHEMA_NOT_RECOGNIZED',message:'8022 sem cabeçalho transacional esperado.',source:'8022'}]};
  const h=headerMap(rows[headerIndex]);const itemIndex=itemIndexes(items);const rcaByCurrent=new Map(rcas.map(r=>[r.currentRcaCode,r]));
  for(let i=headerIndex+1;i<rows.length;i++){const row=rows[i];const statusRaw=normalizeText(cell(row,idx(h,'STATUS PEDIDO')));if(statusRaw!=='FATURADO'&&statusRaw!=='A FATURAR')continue;const saleType=normalizeText(cell(row,idx(h,'TIPO VENDA')));if(saleType&&saleType!=='VENDA')continue;const value=parseNumber(cell(row,idx(h,'VALOR R$ NF')));if(!value)continue;
    const rawCnpj=String(cell(row,idx(h,'CNPJ/CPF CLIENTE'))??'').trim();const normalized=normalizeCnpj(rawCnpj,{declaredCnpj:rawCnpj.replace(/\D/g,'').length>=12});const cnpj=validCnpj(normalized.canonical)?normalized.canonical:'';const transactionRcaCode=cleanCode(cell(row,idx(h,'COD. VENDEDOR')));const rca=rcaByCurrent.get(transactionRcaCode);const winthor=cleanCode(cell(row,idx(h,'CODPROD. WINTHOR')));const manufacturer=cleanCode(cell(row,idx(h,'CODIGO FABRICANTE')));const ean=cleanDigits(cell(row,idx(h,'EAN PRODUTO'))||cell(row,idx(h,'EAN CADASTRO')));const item=itemIndex.byWinthor.get(winthor)||itemIndex.bySku.get(manufacturer)||itemIndex.byEan.get(ean);const movementDate=toIsoDate(cell(row,idx(h,'DATA MOVIMENTO')));const invoice=cleanCode(cell(row,idx(h,'NUMERO NOTA FISCAL')));
    const id=`8022:${movementDate}:${cleanCode(cell(row,idx(h,'NUMERO PED. WINTHOR')))}:${winthor}:${i}`;facts.push({salesFactId:id,movementDate,customerCanonicalId:cnpj?`CNPJ:${cnpj}`:'',winthorCustomerCode:cleanCode(cell(row,idx(h,'COD. CLIENTE'))),cnpj,rcaCanonicalId:rca?.rcaCanonicalId||'',transactionRcaCode,rcaAssignmentStatus:rca?'RESOLVED':transactionRcaCode?'NON_COLGATE':'UNRESOLVED',itemCanonicalId:item?.itemCanonicalId||'',winthorProductCode:winthor,industrySku:manufacturer,orderWinthor:cleanCode(cell(row,idx(h,'NUMERO PED. WINTHOR'))),orderRca:cleanCode(cell(row,idx(h,'NUMERO PED. RCA'))),invoiceNumber:invoice,invoiceDate:toIsoDate(cell(row,idx(h,'DATA EMISSAO NF'))),rawOrderStatus:String(cell(row,idx(h,'STATUS PEDIDO'))??'').trim(),rawBlockStatus:String(cell(row,idx(h,'STATUS BLOQUEIO'))??'').trim(),salesStatus:statusRaw as SalesFactRecord['salesStatus'],units:parseNumber(cell(row,idx(h,'UNIDADES VENDIDAS'))),cases:parseNumber(cell(row,idx(h,'CAIXAS VENDIDAS'))),grossWeightKg:parseNumber(cell(row,idx(h,'PESO BRUTO KG'))),netWeightKg:parseNumber(cell(row,idx(h,'PESO LIQUIDO KG'))),weightTons:parseNumber(cell(row,idx(h,'PESO T'))),value,saleType:String(cell(row,idx(h,'TIPO VENDA'))??'').trim(),line:'',source:'8022'});
    if(!cnpj)qualityIssues.push({id:`8022_CNPJ:${i}`,domain:'SALES',severity:'WARNING',code:'SALES_CUSTOMER_UNRESOLVED',message:'Venda preservada sem CNPJ canônico; não conta em positivação.',source:'8022',entityKey:rawCnpj});if(!item)qualityIssues.push({id:`8022_ITEM:${i}`,domain:'SALES',severity:'WARNING',code:'SALES_ITEM_UNRESOLVED',message:'Venda preservada sem ITEM_MASTER resolvido.',source:'8022',entityKey:winthor||manufacturer||ean});if(transactionRcaCode&&!rca)qualityIssues.push({id:`8022_RCA:${i}`,domain:'RCA',severity:'WARNING',code:'SALES_RCA_NOT_OFFICIAL',message:'Venda preservada, mas o código do vendedor não está no RCA_MASTER oficial desta fotografia.',source:'8022',entityKey:transactionRcaCode});
  }
  return{facts,qualityIssues};
}

export function buildTargets(support:CanonicalSupportData,rcas:RcaMasterRecord[],referenceDate:string):{targets:TargetFactRecord[];qualityIssues:DataQualityIssue[]}{
  const qualityIssues:DataQualityIssue[]=[];const rcaByLegacy=new Map(rcas.filter(r=>r.legacyRcaCode).map(r=>[r.legacyRcaCode,r]));const competence=referenceDate.slice(0,7);const targets=(support.vendorTargets||[]).map((raw,index)=>{const legacyRcaCode=cleanCode(raw.oldCode);const rca=rcaByLegacy.get(legacyRcaCode);if(!rca)qualityIssues.push({id:`TARGET_RCA:${legacyRcaCode}:${index}`,domain:'TARGET',severity:'WARNING',code:'TARGET_UNASSIGNED_RCA',message:'Meta Colgate preservada no total da indústria, mas sem RCA oficial resolvido nesta fotografia.',source:'BUSSOLA',entityKey:legacyRcaCode});return{targetFactId:`BUSSOLA:${competence}:${legacyRcaCode}:${index}`,competence,industry:'COLGATE',legacyRcaCode,rcaCanonicalId:rca?.rcaCanonicalId||'',salesTarget:Number(raw.salesTarget)||0,positivityTarget:Number(raw.positivityTarget)||0,assignmentStatus:rca?'RESOLVED':'UNRESOLVED_RCA',source:'BUSSOLA'} as TargetFactRecord});return{targets,qualityIssues};
}

export function buildInboundFacts(rows:Row[],items:ItemMasterRecord[],operational:OperationalSourceState):{inboundOrders:InboundOrderFactRecord[];receiptHeaders:ReceiptHeaderRecord[];receiptItems:ReceiptItemRecord[];qualityIssues:DataQualityIssue[]}{
  const qualityIssues:DataQualityIssue[]=[];const indexes=itemIndexes(items);const headerIndex=rows.findIndex(row=>{const v=row.map(normalizeText);return v.includes('ORDER DATE')&&v.includes('MATERIAL')&&v.includes('ORDER QTY')&&v.includes('BILL QTY')});const inboundOrders:InboundOrderFactRecord[]=[];
  const receiptHeaders:ReceiptHeaderRecord[]=operational.currentInvoices.map((invoice,index)=>({receiptId:`218:${invoice.invoiceNormalized||invoice.invoice}:${index}`,receiptDate:invoice.entryDate,entryTransactionNumber:'',invoiceRaw:invoice.invoiceRaw||invoice.invoice,invoiceNormalized:invoice.invoiceNormalized||invoice.invoice,entryType:'',series:invoice.invoiceSeries||'',invoiceIssueDate:invoice.issueDate,branch:'',supplier:'COLGATE',supplierCnpj:'',uf:'',totalValue:invoice.totalValue,ipiValue:0,source:'218'}));
  const receiptIdByInvoice=new Map(receiptHeaders.map(h=>[h.invoiceNormalized,h.receiptId]));const receiptItems:ReceiptItemRecord[]=operational.receiptItems.map((row,index)=>{const item=indexes.byWinthor.get(cleanCode(row.sku));return{receiptId:receiptIdByInvoice.get(row.invoiceNormalized||row.invoice)||`218:${row.invoiceNormalized||row.invoice}:${index}`,itemCanonicalId:item?.itemCanonicalId||'',winthorProductCode:cleanCode(row.sku),description:row.product,branch:'',pack:'',unit:'UN',receivedUnits:row.units,unitPrice:row.unitPrice,previousFinancialCost:0,currentFinancialCost:0,fiscalCode:'',operationCode:'',inboundMatchStatus:'UNMATCHED'}});
  const receivedByInvoiceItem=new Map<string,number>();operational.receiptItems.forEach(row=>{const item=indexes.byWinthor.get(cleanCode(row.sku));const key=`${row.invoiceNormalized||row.invoice}|${item?.itemCanonicalId||cleanCode(row.sku)}`;receivedByInvoiceItem.set(key,(receivedByInvoiceItem.get(key)||0)+row.units)});
  if(headerIndex>=0){const h=headerMap(rows[headerIndex]);for(let i=headerIndex+1;i<rows.length;i++){const row=rows[i];const material=cleanCode(cell(row,idx(h,'Material')));const orderQty=Math.max(parseNumber(cell(row,idx(h,'Order Qty'))),0);const billQty=Math.max(parseNumber(cell(row,idx(h,'Bill Qty'))),0);const netValue=Math.max(parseNumber(cell(row,idx(h,'Net Value ( ZINV )')),0);if(!material||(orderQty<=0&&billQty<=0&&netValue<=0))continue;const item=indexes.bySku.get(material)||indexes.byWinthor.get(material);const factor=item?.industryUnitsPerCase||null;const pipelineCases=orderQty+billQty;const pipelineUnits=factor?pipelineCases*factor:null;const invoiceRaw=String(cell(row,idx(h,'Nota Fiscal Number'))??'').trim();const invoiceNormalized=parseInvoiceIdentity(invoiceRaw).normalized;const receivedUnits=invoiceNormalized?(receivedByInvoiceItem.get(`${invoiceNormalized}|${item?.itemCanonicalId||material}`)||0):0;const remaining=pipelineUnits===null?null:Math.max(pipelineUnits-receivedUnits,0);let inboundStatus:InboundOrderFactRecord['inboundStatus']='OPEN_INBOUND';if(billQty>0&&receivedUnits<=0)inboundStatus='BILLED_BY_COLGATE_IN_TRANSIT';else if(receivedUnits>0&&pipelineUnits!==null&&receivedUnits<pipelineUnits)inboundStatus='PARTIALLY_RECEIVED';else if(receivedUnits>0&&pipelineUnits!==null&&receivedUnits>=pipelineUnits)inboundStatus='RECEIVED_BY_MILENIO';else if(orderQty>0&&billQty===0)inboundStatus='ORDERED_FROM_COLGATE';inboundOrders.push({inboundFactId:`CARTEIRA:${cleanCode(cell(row,idx(h,'Order Number')))}:${material}:${i}`,orderDate:toIsoDate(cell(row,idx(h,'Order Date'))),colgateCustomerNumber:cleanCode(cell(row,idx(h,'Customer Number'))),orderNumber:cleanCode(cell(row,idx(h,'Order Number'))),itemCanonicalId:item?.itemCanonicalId||'',industrySku:material,orderQtyCases:orderQty,billQtyCases:billQty,pipelineQtyCases:pipelineCases,pipelineUnits,netValue,invoiceRaw,invoiceNormalized,billingType:String(cell(row,idx(h,'Billing Type'))??'').trim(),billingDate:toIsoDate(cell(row,idx(h,'Billing Date'))),grossWeight:parseNumber(cell(row,idx(h,'Gross Weight'))),receivedUnits,remainingInTransitUnits:remaining,inboundStatus,source:'CARTEIRA_COLGATE'});if(!item)qualityIssues.push({id:`INBOUND_ITEM:${i}`,domain:'INBOUND',severity:'WARNING',code:'INBOUND_ITEM_UNRESOLVED',message:'Linha da Carteira Colgate preservada sem ITEM_MASTER resolvido.',source:'CARTEIRA_COLGATE',entityKey:material});if(pipelineCases>0&&!factor)qualityIssues.push({id:`INBOUND_PACK:${i}`,domain:'INBOUND',severity:'WARNING',code:'INDUSTRIAL_PACK_MISSING',message:'Carteira em caixas preservada; unidades não foram inventadas sem Un/CX industrial.',source:'CARTEIRA_COLGATE',entityKey:material})}}
  const inboundByInvoiceItem=new Map(inboundOrders.filter(r=>r.invoiceNormalized).map(r=>[`${r.invoiceNormalized}|${r.itemCanonicalId}`,r]));receiptItems.forEach(row=>{const header=receiptHeaders.find(h=>h.receiptId===row.receiptId);const inbound=header?inboundByInvoiceItem.get(`${header.invoiceNormalized}|${row.itemCanonicalId}`):undefined;if(!inbound){row.inboundMatchStatus='UNMATCHED';return}if(inbound.pipelineUnits===null){row.inboundMatchStatus='MATCHED';return}row.inboundMatchStatus=row.receivedUnits>inbound.pipelineUnits?'OVERAGE':row.receivedUnits<inbound.pipelineUnits?'PARTIAL':'MATCHED'});
  return{inboundOrders,receiptHeaders,receiptItems,qualityIssues};
}

export function runSalesMotor(input:{salesRows:Row[];portfolioRows:Row[];items:ItemMasterRecord[];rcas:RcaMasterRecord[];support:CanonicalSupportData;operational:OperationalSourceState;referenceDate:string}):SalesMotorResult{
  const sales=parseSales8022(input.salesRows,input.items,input.rcas);const inbound=buildInboundFacts(input.portfolioRows,input.items,input.operational);const targets=buildTargets(input.support,input.rcas,input.referenceDate);return{salesFacts:sales.facts,inboundOrders:inbound.inboundOrders,receiptHeaders:inbound.receiptHeaders,receiptItems:inbound.receiptItems,targets:targets.targets,qualityIssues:[...sales.qualityIssues,...inbound.qualityIssues,...targets.qualityIssues]};
}
